### ISSUE TITLE
[Validator] Document each constraint code

### ISSUE THREAD

**Issue by lyrixx** [symfony/symfony-docs#10001]
Hello.

Each constraints in Symfony have an unique code (uuid, for machine reading).
But those codes are not "documented". I mean, there are no pages on symfony.com which
list all theses code and there associated error.

Is has already been suggested [here](https://github.com/symfony/symfony/pull/22150#issuecomment-291250171) and [here](https://github.com/symfony/symfony/pull/15154)

Why may wonder why we need that. Actually I'm working on an API, and I had to manually document each code :/ I would be nice to document it just once (on symfony.com).

---

I'm not sure how to build this documentation page

1. manually in a .rst file
2. automatically with a parser

**Comment by javiereguiluz** [comment]
I'm afraid I'm going to close this as "won't fix" because of the following reasons.

The constraint error UUIDs look like this:

```php
class CardScheme extends Constraint
{
    const NOT_NUMERIC_ERROR = 'a2ad9231-e827-485f-8a1e-ef4d9a6d5c2e';
    const INVALID_FORMAT_ERROR = 'a8faedbf-1c2f-4695-8d22-55783be8efed';

    // ...
}
```

There are literally hundreds of constraints like that ... and that's the only available information: constant name + UUID value.

1) If you are asking us to document this manually ... that's impossible for us. We have lots and lots of pending features to document, lots of existing articles to review, etc. We don't have time for this, I'm sorry.

2) If you are asking us to document this automatically ... as you can see, there's no information about the errors. With an automatic parser we can do something like this: `a2ad9231-e827-485f-8a1e-ef4d9a6d5c2e = "Not numeric error"` ... that's too similar to the constant name.

So, maybe, instead we need some utility in the Symfony code to get the constant name of the given UUID. Maybe there's already something like that?

In any case, I hope you understand this decision 🙏
