### ISSUE TITLE
Remove Silex references from framework introduction

### ISSUE THREAD

**Issue by muffe** [symfony/symfony-docs#10136]
In the introduction for 'Why would you like to create your own framework' there is a reference to Silex to get startet faster.

See https://github.com/symfony/symfony-docs/blame/4.1/create_framework/introduction.rst#L44

In my opinion we either should entirely remove that tip block or update it to reference Flex in any way.

Though I'm not entirely sure what would be the right approach here.

**Comment by ricknox** [comment]
I think this is a good idea, but I have my reservations about the implementation. I rather see it replaced by Flex since there are still indications about Silex at various places in the documentation:

[/components/http_kernel.rst@`4.1`#L12 (blame)](https://github.com/symfony/symfony-docs/blame/4.1/components/http_kernel.rst#L12)
[/create_framework/dependency_injection.rst@`4.1`#L253 (blame)](https://github.com/symfony/symfony-docs/blame/4.1/create_framework/dependency_injection.rst#L253)

But you are right. Silex was in maintenance mode and is EOL since June 2018.

Perhaps a note about Silex references to http://symfony.com/blog/the-end-of-silex would be a option when all these files have been changed?

**Comment by ricknox** [comment]
You are right. Silex was in maintenance mode and is EOL since June 2018.

I think this is a good idea, but I have my reservations about the implementation. I rather see it replaced by Flex than deleted since there are still indications about Silex at various places in the documentation:

[/components/http_kernel.rst@`4.1`#L12 (blame)](https://github.com/symfony/symfony-docs/blame/4.1/components/http_kernel.rst#L12)
[/create_framework/dependency_injection.rst@`4.1`#L253 (blame)](https://github.com/symfony/symfony-docs/blame/4.1/create_framework/dependency_injection.rst#L253)

Perhaps a note about Silex linking to http://symfony.com/blog/the-end-of-silex would be a option when all these files have been changed?
