### ISSUE TITLE
HTTP 404 on authentication-guard-methods.svg image

### ISSUE THREAD

**Issue by Seb33300** [symfony/symfony-docs#10210]
On this page: https://symfony.com/doc/current/security/guard_authentication.html

The image https://symfony.com/doc/current/_images/security/authentication-guard-methods.svg is not displayed: 404 Not found

The image is displayed properly on master and other version of the documentation.

**Comment by javiereguiluz** [comment]
Thanks for reporting this issue. Sadly there were some issues with the SVG images in Symfony Docs. This is because the Sphinx doc build tool we use treats them differently than the other image types. We've just merged a fix for this into symfony.com and once is deployed, this error will be probably fixed. Thanks!

**Comment by ThomasLandauer** [comment]
This looks fixed for me now; the picture is on again, see: https://symfony.com/doc/current/security/guard_authentication.html#the-guard-authenticator-methods
