### ISSUE TITLE
Symfony Messenger Page containers broken links

### ISSUE THREAD

**Issue by jorge07** [symfony/symfony-docs#10270]
I noticed that https://symfony.com/doc/current/components/messenger.html#adding-metadata-to-messages-envelopes contains some broken links, I don't know how to fix it so at least I can let you know:
 
https://api.symfony.com/4.1/Symfony/Component/Messenger/Envelope.html
https://api.symfony.com/4.1/Symfony/Component/Messenger/Transport/Serialization/SerializerConfiguration.html
https://api.symfony.com/4.1/Symfony/Component/Messenger/Middleware/Configuration/ValidationConfiguration.html

**Comment by javiereguiluz** [comment]
@jorge07 you are right! Thanks for reporting this issue. Sadly this is a known error. We can't regenerate the API docs until we finish some changes on production server. Luckily, those changes will be made "soon" now, so this and all the other related issues will be fixed.

I'm closing this issue because we have another one in the private symfony.com repository where we track this issue until it's solved. Thanks again for your help!

**Comment by jorge07** [comment]
Awesome. Thanks!
