### ISSUE TITLE
add more published doc formats (pdf, epub)

### ISSUE THREAD

**Issue by c33s** [symfony/symfony-docs#1029]
> The documentation strategy (instead of a large book, the Symfony2 documentation is split into small chapters about specific topics);
> Fabien Potencier
> http://symfony.com/blog/symfony2-documentation

i think, it would be very important to also create and provide the symfony2 docs in "book" form -> pdf / epub.

why?
- no, we don't have a internet connection everywhere
- ebook reader doesn't handle rst
- for people who want to print it out
- ...

of course the format of the symfony docs opens all doors to do it myself (http://symfony.com/doc/2.0/contributing/documentation/format.html), 
i only need Sphinx and then i can create pdfs. wait, i have to install rst2pdf. easy

```
ImportError: No module named setuptools
http://www.happylife.sg/index.php/2010/04/25/importerror-no-module-named-setuptools/
```

and so on...

what i want to say is, that its not a 5 minute act to create a pdf and if i just want to learn a framework it doesn't mean i want to learn how to convert rst in pdf (or have the time to).

it would be a great thing, to add the conversion to pdf/epub to the docment website build/deploy process, so the problem is solved one time and the users of symfony can focus on symfony instead of building pdf files.

before anyone answer with "we don't need that", "it is ok how it is",... don't forget we are talking about digital/virtual stuff, so if i would ask to print a book in paperback insted of hardcover this would be a decision where only one way would be possible  course you can if you look at the costs but in the virtual world we just can deploy both with nearly no overhead.
we don't need to choose between this or that way, we can take both ways at the same time.

to provide a one (all the docs) or three (book, cookbook, components) file(s) doc would really help to use it mobile.

please help the developers to keep focus on developing with php and symfony not sphinx and other stuff.

**Comment by zanardigit** [comment]
@stof this version is now built automatically every day: http://symfonyepub.gibilogic.com. 
P.S. it's just a temporary place, if you want me to FTP / rsync / push somewhere else, I'll be happy to,

@xabbuh I have made some steps forward just by updating the tools. Now the ebook is complete and correctly sorted, and there's no need to use Calibre anymore.

**Comment by xabbuh** [comment]
@zanardigit Well, I still need to convert it to be able to use it on a mobi-only device.

**Comment by zanardigit** [comment]
@xabbuh you're right, you still need to use Calibre. But I think that's outside the scope of this issue:

* as far as i read (see https://github.com/symfony/symfony-docs/issues/1029#issuecomment-5112493) the target was only the EPUB. 
* MOBI format is not direcly supported in Sphinx so I can only assume that requires a bit more work
* converting from EPUB to MOBI via Calibre is really easy and user-friendly anyway, so it's probably not worth it to do the conversion ourselves.

Hope this makes sense! :-)

**Comment by xabbuh** [comment]
@zanardigit Of course, I didn't meant to criticise you about that. :) Having an epub book would actually be huge step at all. :)

**Comment by gaetan-petit** [comment]
@zanardigit: the result is not bad, could you add a build for french version of the documentation? thanks.

**Comment by zanardigit** [comment]
@gaetan-petit done

**Comment by gaetan-petit** [comment]
@zanardigit :+1:

**Comment by zanardigit** [comment]
So, now we have an epub built automatically each day. What are the next steps required to close this issue? More versions? More language? Publish the epubs on Symfony website?

**Comment by gaetan-petit** [comment]
Yes, Yes, Yes.

Maybe get Sensio lab add it's css styles would be better.

**Comment by 16nsk** [comment]
:+1: to publish on the Symfony website

**Comment by Einenlum** [comment]
:+1: @16nsk

**Comment by typomedia** [comment]
@fabpot , where is the promised epub now?

**Comment by typomedia** [comment]
Ok, this site still seems to work with daily builds: http://symfonyepub.gibilogic.com

**Comment by zanardigit** [comment]
@typomedia in fact I just noticed it's broken since a few weeks. I will fix it now, so I will also remove EOL versions and add 2.8.

**Comment by weaverryan** [comment]
Thanks @zanardigit - that's awesome. @javiereguiluz could we link to that site for people who want ePub? It's great a community member solved this, I think we can help tell people about it.

**Comment by zanardigit** [comment]
@weaverryan glad to help. Before linking to the site please wait a couple of days so that I will be able to fix (I have a Sphinx version issue due to Ubuntu repo not being up-to-date).

**Comment by javiereguiluz** [comment]
@weaverryan @zanardigit I'm sorry for telling you this and I hope you understand it well: we cannot link to this alternative version from the official website. The reason is the same we applied when we decided to not link to external blog posts: the site can be down or hacked, the content can be hacked or change without our knowledge, the site can suddenly change to include contents, ads, etc. that don't comply with our policies, etc.

We can't control a third-party website, that's why we cannot link to it. I'm only talking about "content websites". Obviously we link to official project pages, GitHub repositories, etc.

**Comment by WouterJ** [comment]
@javiereguiluz so then, isn't it possible to publish epub formats on symfony.com? @zanardigit seems to have a generation script that works good, can't this be integrated into the site the same way as PDFs are integrated?

**Comment by javiereguiluz** [comment]
@WouterJ if @zanardigit kindly shares his script with me (javier.eguiluz @ sensiolabs.com) I can try to use it or adapt it for symfony.com server. I can't promise a solution, but I can guarantee that I'll try it.

**Comment by zanardigit** [comment]
@javiereguiluz as I already mentioned before in this same issue, that site was meant to be temporary and I'm totally ok with your proposal. 

To make things easier for you, what if I publish the resulting epubs on a GitHub repo? You could just get them without having to setup the whole build script.

**Comment by javiereguiluz** [comment]
@zanardigit thanks for understanding this decision. To be honest it would be better to have the script, so we can add some book covers to the books and to update their styles when needed. Thanks!

**Comment by Einenlum** [comment]
@WouterJ & @javiereguiluz  :+1: for having the script directly on the official website.

**Comment by gaetan-petit** [comment]
Finally :+1: make it happen @javiereguiluz !

**Comment by zanardigit** [comment]
@javiereguiluz the script is available at https://gist.github.com/zanardigit/84f0bd8f2948c57d6d2d. If you need any additional info, let me know.

**Comment by ethernal** [comment]
@zanardigit I noticed that the site is missing 2.8/3.0 version of the docs, any way you could provide us the files.

I tried building the docs myself (I have no access to proper Linux machine at the moment sadly).

Also when I tried building the docs with Jinja 2.8 manually I'm getting lots of errors due to Sphinx PHP extensions. If I comment 'from string import upper' in bestpractices.py

     File "d:\dev\tools\python\3.5\lib\site-packages\jinja2\compiler.py", line 427, in fail raise TemplateAssertionError(msg, lineno, self.name, self.filename) jinja2.exceptions.TemplateAssertionError: no test named 'index'

if I then change (in layout.html in _templates dir of docs)

    {% set isIndex = pagename is index %}
to
    {% set isIndex = pagename %}

this error shows up

    File "[...........]\python\3.5\lib\site-packages\jinja2\compiler.py", line 427, in fail raise TemplateAssertionError(msg, lineno, self.name, self.filename) jinja2.exceptions.TemplateAssertionError: no filter named 'get_type'

I have no knowledge of Python so I'm not confident about the changes I make but it seems that the extensions are not compatible with versions of software I'm using or at least I hope that's all.

Using Phyton 3.5.1
Jinja 2.8

**Comment by zanardigit** [comment]
@ethernal since @javiereguiluz asked me the script I just assumed he would go on publishing it on the Symonfy site, so I stopped managing my temporary site (and in fact I will remove it shortly). I think you should ask him about the progress of the task.

**Comment by kamilsk** [comment]
still open :(

**Comment by weaverryan** [comment]
I'll bring this up at our next docs meeting :). It's out of the hands of most of us contributors because the logic would live on symfony.com itself.

**Comment by mitas** [comment]
:+1: epub

**Comment by michaelperrin** [comment]
@mitas I opened a PR for epub: #7347

**Comment by NetaLev** [comment]
+epub

Maybe an updated epub to symfony3, please?

Thanks!

**Comment by kkarkus** [comment]
+epub

**Comment by sadok-f** [comment]
+epub

**Comment by michaelperrin** [comment]
@sadok-f Since https://github.com/symfony/symfony-docs/pull/9972, I realize it is quite easy to generate an ePub file!
Here is one that I generated for the `master` branch of the docs: http://www.michaeperrin.fr/SymfonyFrameworkDocumentation.epub

I may explain how I generated it :)

**Comment by sadok-f** [comment]
@michaelperrin Thank for the link!
(it's missing an `l` in the url [michael])

**Comment by michaelperrin** [comment]
@sadok-f Thanks, fixed!

**Comment by pawel-slowik** [comment]
The `builder` docker container currently supports and successfully builds docs in the EPUB format with `make -C _build epub`. I have tested the output file on a rather old e-reader (a Nook from 2011) and it is nearly perfect, with some very minor CSS issues.

I guess publishing the EPUB on the website is now mostly a matter of CI and procedural arrangements. For example, what do you do if the HTML build succeeds, but the EPUB fails? This should't really happen as Sphinx is quite reliable, but still...

For anyone wanting to generate the EPUB on their own, here's a recipe:

1) Build the documentation:

        docker build . -t symfony-docs

2) Find the `builder` docker image. It's the one that was created right before the `symfony-docs` image and has no repository name. For example:

        docker images

Output:

        REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
        symfony-docs        latest              a898d4c9dc74        25 minutes ago      155MB
        <none>              <none>              f82c133b78fc        26 minutes ago      1.12GB
        nginx               latest              5a3221f0137b        6 days ago          126MB
        python              2-stretch           62f3f5e37c61        7 days ago          916MB
        hello-world         latest              fce289e99eb9        7 months ago        1.84kB

In the above example `f82c133b78fc` is the ID of the builder image.

3) Reuse the builder image to create an EPUB file:

        mkdir /tmp/epub_output
        docker run -i -t -v /tmp/epub_output:/tmp/epub_output f82c133b78fc /bin/bash

Inside the container:

        make -C _build epub
        cp _build/epub/SymfonyFrameworkDocumentation.epub /tmp/epub_output
        exit

The EPUB file is now in `/tmp/epub_output/SymfonyFrameworkDocumentation.epub` .

**Comment by javiereguiluz** [comment]
We have an important update about this issue.

During the past [SymfonyCon Amsterdam 2019](https://amsterdam2019.symfony.com/) conference, the Symfony Docs Team held a meeting to discuss about Symfony Docs and make some decisions.

One of the most important decisions that we made was to no longer support alternative formats such as PDF (and to not introduce new formats such as ePub). The main reason was that we don't have the resources to make this work as good as it should work. The second reason is that most of Symfony developers don't need that because they have a reliable Internet connection whenever they need to look for the Symfony Docs. A final reason is that given the huge activity of this repository, any downloaded PDF/ePub doc is "wrong" (contains bugs or it's incomplete) just a few hours after being downloaded (so you need to download it again continuously).

In addition to closing this issue, we're locking it. We rarely lock issues, but this kind of decisions usually lead to heated reactions, so we'd like to prevent that. If you want to freely express your opinion about this (including your strong disagreement, if that's what you think), please use Symfony's Slack: https://symfony.com/slack  Thank you!
