### ISSUE TITLE
Do not allow selecting special symbols in the beginning of code lines

### ISSUE THREAD

**Issue by bocharsky-bw** [symfony/symfony-docs#10301]
Hi everyone! This is a request for improving https://symfony.com/doc/. Could you add [user-select: none;](https://developer.mozilla.org/en-US/docs/Web/CSS/user-select#CSS) CSS property for `+`/`-`  symbols in the beginning of code lines? It will allow users not selecting these extra symbols and copy/paste already valid code.

<img width="704" alt="screen shot 2018-09-08 at 00 54 17" src="https://user-images.githubusercontent.com/3317635/45244743-d71ad800-b301-11e8-9b56-aa0ba84211f6.png">

Cheers!

**Comment by javiereguiluz** [comment]
@bocharsky-bw thanks for this proposal to improve docs.

However, after thinking about this, I'm closing it as "won't fix". Why? Although the example you showed only contains `+` lines, the normal use case in `diff` examples is to have `+` and `-` mixed together:

![diff-example](https://user-images.githubusercontent.com/73419/65409438-03f43d00-dde8-11e9-9266-a15d3d7c91b1.png)

Copying this code is already questionable (because you should only copy the `+` lines, not all of them) and that's why we don't display the "Copy Code" button which is displayed in the other code listings. But, if we implement the proposal you made here, the situation would be even worse, because you copy both `+` and `-` lines ... but you no longer know which one is `+` or `-`, so you don't know what to add or remove.

In any case, thanks for your proposal and please, keep them coming!
