### ISSUE TITLE
[Website] Inconsistent descriptions about community

### ISSUE THREAD

**Issue by zanbaldwin** [symfony/symfony-docs#10315]
It's a little tiny thing, and only noticed it because I'm using the website as a reference to write about the community. There are two descriptions regarding the Symfony community:

> *"A huge community of Symfony fans committed to take PHP to the next level."* – [What is Symfony?](https://symfony.com/what-is-symfony)

> *"Symfony Community is a passionate group of over 600,000 developers from more than 120 countries, all committed to helping PHP surpass the impossible."* – [Symfony Community](https://symfony.com/community)

Would it be a good idea to combine these descriptions such as *committed to taking PHP to the next level and surpass the impossible*?

It's not a problem for the average person browsing the website but when I wanted to reference the Symfony website on its definition of the community, I didn't know which quote to use.

**Comment by javiereguiluz** [comment]
Zan, thanks for reporting this. I agree that this is inconsistent. Actually, instead of merging both descriptions, we're thinking about reusing the one found in the "Community" page for the description in the "What's Symfony" page. I'll keep you posted here about the changes related to this.

Thank you again for helping us improve the Symfony website. I'm a big fan of removing inconsistencies, so I liked your issue a lot!

**Comment by javiereguiluz** [comment]
Quick update: we finally merged the proposal mentioned above, so we'll use in the "What's Symfony" page the same description as in the "Community" page. Changes will be online after the next deploy. Thanks!
