### ISSUE TITLE
Confusing documentation regarding TWIG if you start with "skeleton" vs "website-skeleton"

### ISSUE THREAD

**Issue by viion** [symfony/symfony-docs#10405]
Hello,

I think the documentation for **Create your First Page** needs some form of notice regarding `skeleton` and `website-skeleton`. The page assumes the user installed `website-skeleton`. If the user install `skeleton` they will not have `maker` or `twig` and run into blocking issues following the documentation.

I would be happy to do a PR that amends it, some ideas:
- A note at the top informing them of bundles required to forful the steps in the documentation if the user installed `symfony/skeleton`
- A code example similar to **Annotations** that lists the `composer require X` command.

I remember bringing this issue up in slack several months ago when I was thinking of doing a page edit and was told there were going to be big changes to the docs so I wrote on a stickynote `composer req twig` and forgot about it. Until i lost my stickynote (or the cleaner at my office ran into this same issue and took it!) and today started a new micro-service, jumping into the same issues I always have.

### Journey

On the Symfony 4 install: 
> If you are building a microservice, console application or API: install `symfony/skeleton`

This is also recommended on the **Setup** page. A microservice can contain HTML/templates, so I might choose this one or I may just want to pick the bare minimum for now and add on as I need more.

With this installed I follow the documentation and get to the second part: **Create your First Page in Symfony**. This is where problems arise, this entire page *assumes* you picked `website-skeleton`, if you choose the `skeleton` package then expect lots of problems, for example:

#### Create controllers faster by using make
It did not tell me to install any kind of `make` bundle.
```
Command "make" is not defined.
```

#### Rendering a template
Because you would not have Twig installed at this point you get errors. It does have a confusing note: 
> Fortunately, Symfony comes with Twig! 

It comes with Symfony 4: `website-skeleton` however it does not come with Symfony 4: `skeleton`, so the page will not render and theres no template folder.

I think the documentation could be a lot clearer here and needs to either not assume we're on `website-skeleton` or should include some kind of note to make the user aware. Or maybe I'm the only one running into this issue 💃 

*Side note ...*

Googling on how to fix this brings up the official Twig site, is there any difference between `require twig` vs `require twig/twig`?, I got confused as I need the `twig-bundle`... below that result is another seemlingly unrelated page: *Quick Tour*? It happens to list `composer require twig` just what we need! Maybe I'm blind but I can't find a link to the quick tour anywhere, it's not on the Documentation page, or the Download page.

**Comment by javiereguiluz** [comment]
@viion thanks a lot for reporting this detailed issue. Even if we didn't reply to you, you were absolutely right and these past months we've been busy improving the error messages and adding help tips everywhere.

For example, if you create a skeleton-based project and try to run any `make` command, you now see this useful error message:

![image](https://user-images.githubusercontent.com/73419/65319554-314eaa00-dba0-11e9-9779-559ed65d5561.png)

And if you try to run certain `make` commands that require extra annotations, you keep getting useful error messages:

![image](https://user-images.githubusercontent.com/73419/65319685-838fcb00-dba0-11e9-897f-66d6fa3e05d5.png)

Same if you try to render a template but don't have Twig installed. You see this error page:

![image](https://user-images.githubusercontent.com/73419/65319776-b4700000-dba0-11e9-8a72-76f73211e819.png)

So, I'm glad to close this issue as "fixed" because we've added a ton of help messages in errors and exceptions. If you find new issues, please create a new issue and share some details so we can fix it.

Again, thanks a lot for your great issue report. It helped us a lot!
