### ISSUE TITLE
Tell about russian translation of the Symfony doc

### ISSUE THREAD

**Issue by nicolas-grekas** [symfony/symfony-docs#10591]
Today at http://2018.symfonycamp.org.ua/, I met with @luchaninov and he told me about the work he's doing translating the Symfony doc as a hobby. Here it is:
http://symfony.com.ua/doc/current/index.html

The source code is not yet public but should be very soon on github.
I know we don't want to maintain that ourselves.
But can we still link to this somehow?

**Comment by llaakkkk** [comment]
Hello @nicolas-grekas !
I know English and Russian so it would be great to be one of the maintainers for me.

**Comment by javiereguiluz** [comment]
I'm closing this as "won't fix". In the past we received similar proposals for other languages ... and we always had to reject because of the same reason: due to the high activity of Symfony Docs, it's impossible to keep translations updated.

A non-updated translation is much worse than not having a translation. A non-updated translation contains bugs and doesn't mention new Symfony features, so it's not helping neither the Symfony project nor the reader of the docs.

I can understand if you are disappointed, but I hope you understand the reasoning behind this. Thank you.
