### ISSUE TITLE
Aggregate changelog entries by component

### ISSUE THREAD

**Issue by DanieleGBX** [symfony/symfony-docs#10636]
Currently the automatically generated changelogs are in a random (chronological?) order, since we do have a tag on some of them identifying the component they apply to, should we perhaps pseudo-aggregate by sorting by component?

**Comment by javiereguiluz** [comment]
Thanks for sending this proposal. Although I'm not in charge of generating those changelogs, I guess it would be difficult to implement because some features don't have a component associated and others are related to multiple components/bundles.

In files generated manually (such as https://github.com/symfony/symfony/blob/master/UPGRADE-4.2.md) we take care of separating things by component. Not sure we can do the same with the automatically generated files.

**Comment by DanieleGBX** [comment]
Yeah, not tagged entries should probably be treated as a pseudocomponent, meaning sorted to the top or the bottom. Multiple components, should be either repeated or sorted by first component listed, trusting that whoever tags them does a good job at that.

**Comment by javiereguiluz** [comment]
I'm sorry but I'm going to close this as "won't fix" for now. As explained, changelogs are generated automatically and improving that won't be easy because of all the "edge cases" (changes that belong to two components or to one component and one core bundle, or general changes that don't belong to any specific component, etc.)

In any case, thanks for your proposal and please keep proposing future improvements. Thanks!
