### ISSUE TITLE
TagAwareAdapter documentation wrong detail

### ISSUE THREAD

**Issue by flaushi** [symfony/symfony-docs#10647]
Here, https://symfony.com/doc/3.4/components/cache/cache_invalidation.html#tag-aware-adapters, there is a wrong clause:

> the first required one is used to store cached items; the second optional one is used to store tags and their invalidation version number (conceptually similar to their latest invalidation date). When only one adapter is used, items and tags are all stored in the same place. 

I only used one adapter and then `cache.app` was used as fallback, not the first one. see also https://stackoverflow.com/questions/53199769/autowiring-a-tagawarecache-and-injecting-into-service

**Comment by xabbuh** [comment]
I don't see how the `TagAwareAdapter` should be able to always fall back to `cache.app` if that's not the cache pool that should be used to store the items.

Here is the code in question: https://github.com/symfony/symfony/blob/6ba18034c8dbfe6cf6648983c98aa1589cb42a6e/src/Symfony/Component/Cache/Adapter/TagAwareAdapter.php#L45

**Comment by flaushi** [comment]
Yes, I agree, I also studied this code and could not understand. That's why I am here to report this. Look at the two screenshots, the only difference is the additional cache pool definition and the second argument to the TagAwareCache service.

**Comment by xabbuh** [comment]
Are you sure that there is no other cache pool making use of tags too where tags are stored using the app cache? If not, this would be a bug and I'd like to ask you to open an issue in the code repository with a small example application that allows to reproduce the issue.

But since the behaviour is expected to be as described in the docs we can close here and if it turns out to be necessary continue in the code repository. Thank you for understanding.
