### ISSUE TITLE
4.2: The Container is not clear

### ISSUE THREAD

**Issue by chiqui3d** [symfony/symfony-docs#10744]
Hello,
I started using the stable version of **Symfony** 4.2, but it's not clear to me how to use `$this->container`, since all the documentation of 4.2 used it, but I haven't really been able to use it.

Example:

```
//services.yml
    app.theme:
        class: App\Service\Theme
        public: true
        autowire: true
```
Error:

```
Service "app.theme" not found: even though it exists in the app's container, the container inside "App\Controller\Front\BlogController" is a smaller service locator that only knows about the "doctrine", "form.factory", "http_kernel", "parameter_bag", "request_stack", "router", "security.authorization_checker", "security.csrf.token_manager", "security.token_storage", "serializer", "session", "templating" and "twig" services.Try using dependency injection instead.
```

That combination together with many other combinations, has not worked for me, so not being what happens in the `Container`, I have followed everything from **documentation**, but there are many more that refer to the `Container`, but not if your intention is to **remove** it completely.

So, my question is if I can make use of the container or what is really happening, please hope you can help me understand.

Reference:
https://symfony.com/doc/current/service_container.html#public-versus-private-services
https://symfony.com/doc/master/service_container/alias_private.html#aliasing
https://symfony.com/doc/master/service_container/autowiring.html#an-autowiring-example
https://symfony.com/doc/current/service_container/calls.html

Well, almost everything related to the container is not clear.

**Comment by tomtomau** [comment]
Hi there!

It's generally not recommend to inject the entire Container and instead inject each dependency you require.

I'm assuming the issue you're facing is that you a working with the Container from `AbstractController`.

As per [the docs](https://symfony.com/doc/current/service_container.html#service-parameters), the Container autoconfigured for you in AbstractController has a limited scope [and only has certain services injected into it](https://github.com/symfony/symfony/blob/7b03bff57a2782edc6558d57df7ccff99ed0f1a9/src/Symfony/Bundle/FrameworkBundle/Controller/AbstractController.php#L74):

```php
public function new()
{
    // ...

    // this ONLY works if you extend the base Controller
    $adminEmail = $this->container->getParameter('admin_email');

    // or a shorter way!
    // $adminEmail = $this->getParameter('admin_email');
}
```

If your controller extends `\Symfony\Bundle\FrameworkBundle\Controller\Controller` rather than `\Symfony\Bundle\FrameworkBundle\Controller\AbstractController` then you should be ok.

I would however strongly recommend that you inject your service into the constructor (or method) instead. If you're coming from earlier versions of Symfony, you might be accustomed to manually registering your service and pulling it from the container manually in your controller method.

These days, the default configuration of Symfony is to autoconfigure and autowire, so you should be able to simply:

```php

class BlogController extends AbstractController
{
    public function myMethod(Theme $theme): Response
    {
        // The framework will autoinject Theme for us
        $theme->callSomeMethod();
    }
}

```

**Comment by chiqui3d** [comment]
Hello @tomtomau ,

First of all, thank you for taking the time to answer.

Yes exactly I use `AbstractController` and when installing version 4.2 I have no choice because `Controller` was deprecated like with `setter Inejction`, then I understand that the best way is to do it by the constructor and that's as I'm doing it. But I'm doing tests to know the options I have on the Container and nothing works for me when I look at the documentation of the **Service Container**, so you should be much clearer, there are about 20 documents that talk about the **Service Container**, but it's not really clear, you really have to predict or guess where **Symfony** wants to drive me, it's true that I'm not an expert and I may be making a mess, but that has to be clearer, and really that could be summarized in two documents not in 20 as it has now, because I'm surfing in the documentation the Container without having a clear idea.

Thanks :)

**Comment by laurentiu1981** [comment]
Here's what I did, for symfony 4.2, considering that I wanted a service with some configurable arguments.

in services.yaml:

```
services:
    ....

    my.service:
        class: Your\Service\ClassName
        arguments:
        - arg: '%env(config_arg)%'
          second_arg: '%env(config_second_arg)%'

    Your\Service\ClassName: '@my.service'
```

In a controller:
```
use Your\Service\ClassName;

class MyController extends AbstractController {
  public function myAction(ClassName $service) { 
     ...
  }
}
```

**Comment by ahmetelcik** [comment]
if we using dynamic services? what can i do?


<img width="432" alt="Ekran Resmi 2019-11-02 01 55 38" src="https://user-images.githubusercontent.com/6485654/68061069-1bdaad00-fd14-11e9-8f47-3e1e8871ff69.png">

modules services example:
<img width="431" alt="Ekran Resmi 2019-11-02 01 57 59" src="https://user-images.githubusercontent.com/6485654/68061104-4d537880-fd14-11e9-91b3-5b8a1d80d242.png">

**Comment by xabbuh** [comment]
For support, please refer to one of the [support channels](https://symfony.com/support). Thank you for understanding.

**Comment by tobalsan** [comment]
Hey @ahmetelcik 

I had the exact same issue, and found a simple solution. You just have to [use Symfony's service locator](https://symfony.com/doc/current/service_container/service_subscribers_locators.html).
