### ISSUE TITLE
Somehow rewording a statement to lightning it up a bit

### ISSUE THREAD

**Issue by BentCoder** [symfony/symfony-docs#11048]
https://symfony.com/doc/current/contributing/code/core_team.html#core-membership-revocation

> Upon decision of the Project Leader.

This statement makes the "Project Leader" sound more like a "dictator"! Do what he/she says otherwise .....

You get the picture!

**Comment by javiereguiluz** [comment]
@BentCoder I understand your concern ... but this description is absolutely precise according to how things work. Symfony has a nice [Core Team](https://symfony.com/doc/current/contributing/code/core_team.html) but the Project Leader, has the last word on all decisions. This is a governance model called [Benevolent dictator for life](https://en.wikipedia.org/wiki/Benevolent_dictator_for_life), which Symfony, and many other big and small open source projects follow too.

We all (happily) accept this on the Core Team and so far it has worked fantastically. That's why I'm closing this issue. Thanks for understanding.
