### ISSUE TITLE
Logging doesn't seem to work (p13)

### ISSUE THREAD

**Issue by pentool** [symfony/symfony-docs#11050]
Hello,

Reading the 'Quick Tour' PDF book (https://symfony.com/pdf/Symfony_quick_tour_4.2.pdf).

On page 13/14 there's a code sample for using logging.
```
public function index($name, LoggerInterface $logger) {
    $logger->info("Saying hello to $name!");
}

The new log message will be written to var/log/dev.log.
```
I have never worked with Symfony before (hence reading the Quick Tour book) so I am not sure why logging is not happening. There's nothing in the 'var/log' directory.

**Comment by javiereguiluz** [comment]
@pentool thanks for reporting this issue. I've checked the code and it looks correct. The error may be caused by something else. Usually, this is a permission issue (Symfony wants to write that log message, but it doesn't have permission to create the log file in that directory).

* Check out this article: https://symfony.com/doc/current/setup/file_permissions.html
* If the error persists, you can try asking in the `#support` channel of Symfony Slack (https://symfony.com/slack)

Also, since you are starting with Symfony, you may find the [Symfony Demo app](https://github.com/symfony/demo) useful as a learning resource.
