### ISSUE TITLE
Example - View transformers

### ISSUE THREAD

**Issue by seb-jean** [symfony/symfony-docs#11052]
Hi,
On page https://symfony.com/doc/current/form/data_transformers.html, there is an example of Model transformers but not of View transformers.
It might be interesting to have an example of when and how to Use View transformers.

**Comment by javiereguiluz** [comment]
Thanks for your proposal ... but I'm closing this as "won't fix" ... because in this section https://symfony.com/doc/current/form/data_transformers.html#about-model-and-view-transformers we mention those "view transformers" and we explain that everything is the same as above but you need to use the `addViewTransformer()` method. Thanks for understanding.
