### ISSUE TITLE
[Workflow] Document Guards

### ISSUE THREAD

**Issue by pbowyer** [symfony/symfony-docs#11214]
Needed to close https://github.com/symfony/symfony-docs/issues/8499.

### To include

* What is a guard
* Why you would use a guard
* Guards as classes (event subscribers)
* Guards as ExpressionLanguage expressions (`guard:` in YAML config)
* Available parameters
    * subject etc

### Existing online resources

https://codereviewvideos.com/course/symfony-workflow-component-tutorial/video/workflow-guards-part-1 has an excellent series (written for Symfony 3.3)

**Comment by noniagriconomie** [comment]
@pbowyer cc @xabbuh @javiereguiluz (from #8499) I can do a doc on this

should it create a new file? or improve this sub section? https://symfony.com/doc/current/workflow/usage.html#guard-events

Thank you

**Comment by pbowyer** [comment]
I have no strong feeling. The Workflow docs will need re-organising soon, so a separate file would be helpful.

**Comment by javiereguiluz** [comment]
@noniagriconomie if the new contents are super long, then we could create a new article. Otherwise, please update the section of the existing article. We try to avoid creating small article because they break the reading flow too much and people end up with 5 open tabs in their browsers to read 5 small articles instead of reading just one.

**Comment by javiereguiluz** [comment]
Fixed by #11433.
