### ISSUE TITLE
[logs] missing cookbook about logrotate

### ISSUE THREAD

**Issue by brikou** [symfony/symfony-docs#1161]
Configuring logrotate is maybe an off topic but it could be great to add a cookbook on how to configure logrotate to deal with logs (sometimes it can become huge)... Symfony needs more real cookbook about productions topics ;)

Cheer

**Comment by javiereguiluz** [comment]
As suggested by @weaverryan, there are two things to do:

  * Mention `logrotate` and the problem of the log file size: done in #5006  I've added this tip in the Cookbook because the Book doesn't really explain the log files anywhere, so it felt more natural to add it the cookbook.
  * We should decide if it's worth it to create a new Reference for Monolog Handlers. Opinions?

**Comment by WouterJ** [comment]
> We should decide if it's worth it to create a new Reference for Monolog Handlers. Opinions?

This is now alreadyd ocumented in the API docs of Monolog. Besides this, we might want to move everything to the bundle docs: #4983

**Comment by javiereguiluz** [comment]
@WouterJ great! So after #5006 gets merged, this issue can be closed. Thanks.

**Comment by weaverryan** [comment]
This can be closed technically.... though I'd *love* to see a note about `rotating_file` added in addition to #5006.
