### ISSUE TITLE
Add docs for: [Form] deprecate int/float for string input in NumberTy..

### ISSUE THREAD

**Issue by fabpot** [symfony/symfony-docs#11808]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#32130
| PR author(s) | @xabbuh

**Comment by javiereguiluz** [comment]
Closing as "won't fix" because the `input` option is perfectly explained in https://symfony.com/doc/current/reference/forms/types/number.html#input and we don't need to complicate the docs with these details ... which users can't miss because Symfony generates very clear deprecation messages about it.
