### ISSUE TITLE
Installation of Symfony 3.4

### ISSUE THREAD

**Issue by Mynyx** [symfony/symfony-docs#11800]
In the download section of the website (https://symfony.com/download) is for Symfony 3.4 the installation of symfony/website-skeleton or symfony/skeleton recommended.

But the documentation for Symfony 3.4 is based on the Symfony Standard Edition. Also the setup chapter in the documentation (https://symfony.com/doc/3.4/setup.html) describes the installation of the Symfony Standard Edition.

If installing Symfony 3,4 as described in the download section, you will run into trouble when using the documentation, because there are many differences.

It would be sensible if in in the download section for Symfony 3.4 also the Symfony Standard Version would be recommended as in the documentation.

**Comment by javiereguiluz** [comment]
This is complicated.

First, we decided to keep 3.4 docs with the "old Symfony philosophy" and change everything for 4.0 and higher versions. We can't update 3.4 docs now. It would be too much work, specially considering that 3.4 support will end in November 2020.

On the other hand, you can use the great and modern Symfony philosophy in 3.4 versions. That's why symfony.com shows the new way of installing it.

So, this looks confusing ... but it's actually made like that to avoid confusion:

* Are you working on an existing 3.4 app? It's probably using the legacy Symfony ideas ... so docs do that too.
* Are you creating a new app based on 3.4? You probably want the new Symfony ideas, to ease the upgrade to 4.x. That's why the download page helps you doing that.

**Comment by Mynyx** [comment]
I think the first problem is that it is not pointed out that there are two different ways to start a Symfony 3.4 project. If you haven't read the blog article (which usually won't be the case), you would probably only find out if you visit the link "Using Symfony Flex to Manage Symfony Applications" at the end of the setup documentation out of curiosity.

I can understand that it is not possible to update the documentation. But currently it is a coincidence whether you use the setup documentation or the download page for the installation. And if you've used the download page, you'll encounter a lot of differences when using the documentation without having an explanation.

Therefore, my suggestion to recommend the Symfony Standard Version uniformly. Regarding your advice that starting with Symfony Flex would make upgrading to Symfony 4.x easier, it might be an idea to add a conspicuous hint that it is also possible to install Symfony 3.4 as Symfony Flex skeleton, but you should be prepared for differences in the documentation in this case.

**Comment by javiereguiluz** [comment]
After having thought about this ... we're going to keep the existing docs for 3.4 version. We have updated the 4.x docs to always use both Symfony Flex and the Symfony local web server (#11939).

I'm sorry if this disappoints you ... but luckily, we're so late in the Symfony 3.4 cycle, that almost nobody creates new Symfony 3.4 apps nowadays. Moreover, the new LTS version (4.4) releases in just 4 months, so 3.4 won't be used very soon. Thanks.
