### ISSUE TITLE
symfony 3.4 using Iterable with PHP 7.0

### ISSUE THREAD

**Issue by max4ever** [symfony/symfony-docs#11818]
Hi,
on this page the example https://symfony.com/doc/3.4/service_container/tags.html#reference-tagged-services suggests using _iterable_, but that is **not present in PHP 7.0**

> Iterable is a pseudo-type introduced in PHP 7.1

> Symfony 3.4 requires PHP 5.5.9 or higher to run.

Am I missing something?

Thank you

**Comment by javiereguiluz** [comment]
Although you are right, there are two things to consider:

* For Symfony code, there are some strict minimums that code must comply with. In 3.4, we can't use PHP features higher than 5.5.9. But you can run Symfony 3.4 with any higher PHP version, up to 7.4.
* For Symfony docs, we are more liberal and we use more advanced PHP features, not only the minimum required by Symfony. According to the [latest PHP usage stats](https://blog.packagist.com/php-versions-stats-2019-1-edition/) published by Composer, 89.35% of PHP developers use PHP 7.0 or higher. So we think it's OK to keep doing that in docs.

In any case, thanks for your message because it makes us revisit our decisions. Cheers!
