### ISSUE TITLE
Requirements Symfony 3.4

### ISSUE THREAD

**Issue by Mynyx** [symfony/symfony-docs#11826]
According to the site "Requirements for Running Symfony" Symfoy 3.4 requires PHP 5.5.9 or higher (https://symfony.com/doc/3.4/reference/requirements.html).

That is correct for symfony/framework-standard-edition, but symfony/skeleton requires PHP 7.0.8 or higher (https://packagist.org/packages/symfony/skeleton#v3.4.28.3).

**Comment by javiereguiluz** [comment]
As we explained in https://github.com/symfony/symfony-docs/issues/11800#issuecomment-504463062, this is tricky for Symfony 3.4 version.

However, in this specific case, I think it's OK to briefly mention the two different PHP requirements. We can't update the 3.4 docs to always explain the two possible alternatives (standard edition vs skeleton) because that would be too much work ... but we can do that for selected articles. Thanks.

**Comment by javiereguiluz** [comment]
Closing as fixed by #11832.
