### ISSUE TITLE
DateIntervalType months, days, etc options

### ISSUE THREAD

**Issue by adrx** [symfony/symfony-docs#11925]
I do not know whether this is a documentation issue or a bug.

Using sf4.2

When I followed the example in the documentation for setting the range of months that can be selected -- by setting the 'months' option to range(1,12) -- I expected to get a select box in which the values and labels are both in the range 1 through 12. Instead, I got a select box with values 1 to 12 labelled as 0 through 11. I am not sure why anyone would expect or want that.

To get the labels to match the values I have to set the 'months' option to 

array_combine(range(1, 12), range(1, 12))

Perhaps the documentation should at least make it clear that the 'months' option is used as the 'choices' option for the 'months' child form, and that setting it as an array that is not explicitly indexed will have the unexpected result mentioned above.

**Comment by javiereguiluz** [comment]
The problem is that when you pass `range(1, 12)` as the `choices` you are in fact passing this array:

```php
array(
    0 => 1,
    1 => 2,
    3 => 3,
    // ...
    11 => 12,
);
```

`Choice` uses the array keys as visible labels and array values as the internal values for the form field. We're rewording the docs about this a bit (see https://github.com/symfony/symfony-docs/pull/12054/files) to avoid future confusions.

Thanks.
