### ISSUE TITLE
[Messenger] supervisor caution

### ISSUE THREAD

**Issue by spike31** [symfony/symfony-docs#11935]
Hi,

I would like to share something with supervisor. @weaverryan wrotes a good section about supervisor. (https://symfony.com/doc/current/messenger.html#supervisor-configuration)

But Recently I came across a situation that can happen to anyone.

I have a worker with a limit of 50 messages. So supervisor runs the worker and wait. Except that he is waiting with a project instance at the time he was executed.
That is, my-project is on version V1.2, so the worker too.

In the meantime I update to V1.3. But the worker is still waiting and stays on his version V1.2!

I wanted to know if we should not document this risk in the documentation, because it is very vicious ...

**Comment by weaverryan** [comment]
Hi there! 

This is a very real situation. But, if you look in the deploy section of the docs (please tell me if I’m wrong, as in on my phone currently), we talk about running a command on deploy that will automatically restart all your workers so that they get the updated code. That should handle this problem.

If I’m mistaken and the docs don’t mention this clearly, please let me know.

Cheers!

**Comment by spike31** [comment]
Oh you're right
I stayed focused on the supervisord part and did not even see that there was a section deploy on production and a task to stop the workers

I think the problem is solved, sorry and thanks for your answer
