### ISSUE TITLE
[Routing] Deprecate ServiceRouterLoader and ObjectRoute..

### ISSUE THREAD

**Issue by nicolas-grekas** [symfony/symfony-docs#12010]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#32582
| PR author(s) | @fancyweb
| Merged in    | 4.4

**Comment by OskarStark** [comment]
@nicolas-grekas it looks, that your `gh`-tool is not up-to-date.

The `Merged in` is missing in the table, like here for example: https://github.com/symfony/symfony-docs/issues/12009

**Comment by OskarStark** [comment]
I updated the "merged in" branch manually 👍

**Comment by javiereguiluz** [comment]
I'm closing this because I can't find any occurrence of the deprecated `routing.loader.service`, `ServiceRouterLoader` and `ObjectRouterLoader` in the docs.

We have an article about "custom route loaders" but we only talk about `routing.loader` and not `routing.loader.service`. So, I'm closing this one ... and opening #12016 to see if we have to document them anywhere.
