### ISSUE TITLE
Missing annotation routing config when not using flex

### ISSUE THREAD

**Issue by linaori** [symfony/symfony-docs#12218]
In (legacy) applications that have yet to migrate, or never will use flex, it's a bit cumbersome to get annotation routings to work. On https://symfony.com/doc/current/routing.html#creating-routes it's explained that you can do `composer require annotations`, but this only works when you have flex.

When searching for `symfony annotation routing`, you either get flex tutorials, the page I just linked, or the SensioFrameworkExtraBundle documentation for routing. This while basically the code example + explanation from the next link would be sufficient in combination with the required packages (doctrine annotations?): https://symfony.com/doc/current/best_practices/controllers.html#routing-configuration

**Comment by javiereguiluz** [comment]
@linaori thanks for reporting this issue. Symfony Docs assume that the reader is using Flex and we cannot change that because ti'd complicate the docs too much.

However, I think we can reword the routing docs a bit to explain things with a bit more detail. Not enough to complicate things ... but enough to shed some light into this. See #12336.
