### ISSUE TITLE
Clarify Examples as Snippets or add <?php

### ISSUE THREAD

**Issue by JWPapi** [symfony/symfony-docs#12352]
When going through the doc, I found a couple of section a bit miss-leading, since a controller works without <?php and a service not. There were sections that were meant to make a point of a specific method but were quoted quite completely so one could assume it is a full file. For example the MessageGenerator would work as full file with <?php. 

So I'm suggesting either make clearer it is not a full file or add <?php.

Also the error that comes up (can't find class) is miss-leading. Especially the first entries and the getting started section should be as beginner friendly as possible to get as many users as possible in this great project ;)

**Comment by tarlepp** [comment]
Hmm, this could work on cases when the all of the code is on those snippets, but how to handle cases that snippet only contain a part of code and not all?

**Comment by JWPapi** [comment]
I think this section is a good example:
https://symfony.com/doc/current/routing.html#creating-routes

1st snippet is clear to be a terminal command
2nd is a clear code snippet
3rd I would expect to be a file, but the only thing from it working would be adding <?php in the beginning. 

So changes to current docs would be something like everytime there is the namespace and the use section also add a <?php tag on top.

If not it's obvious a snippet not a file.

**Comment by javiereguiluz** [comment]
@JWPapi thanks for this proposal. We've discussed internally about this a lot in the Symfony Docs team. At the end we decided to not include the opening `<?php` except in some selected articles aimed to newcomers.

Moreover, we can't do this change now because it would be a huge amount of work. However, we're testing a new "doc builder" which could help us with things like this (e.g. adding the `<?php` automatically). In any case, it's still very early to know if we finally use that new builder, so we cannot promise to change this anytime soon. I'm sorry.
