### ISSUE TITLE
Documentation 'Trademark & Licenses' contains wrong link

### ISSUE THREAD

**Issue by vmeijer** [symfony/symfony-docs#12377]
Hello,
the link 'See documentation license details' in the article [Trademark & Licenses - Symfony Documentation](https://symfony.com/license) is pointing to the page `https://symfony.com/doc/master/contributing/doc/license.html`, which does not exist.

I think it is meant to be identical to the url used for 'license of the Symfony documentation' in the article [Symfony Code License - Other Symfony Licenses](https://symfony.com/doc/current/contributing/code/license.html#other-symfony-licenses): `https://symfony.com/doc/current/contributing/documentation/license.html`

I ran a search through this repository, but it seems there is no way of editing the article  [Trademark & Licenses](https://symfony.com/license). That's why I have opened this issue (instead of creating a pull request).

**Comment by javiereguiluz** [comment]
@vmeijer another great catch! You explained the problem perfectly but, as you said, you can't edit this content yourself because the symfony.com source code is not public. But thanks for reporting this issue, because we fixed it as you suggested and the fix will be online after the next deploy. Cheers!
