### ISSUE TITLE
event_dispatcher documentation

### ISSUE THREAD

**Issue by capaio** [symfony/symfony-docs#12411]
Hi, 
I'm working on listeners priority. The documentation says "the higher the number, the earlier a listener is executed" but when i run my code the listener with priority 25 is executed AFTER the listener with priority 0. If I change the priority from 25 to -25 then it is executed before the priority 0. Is the documentation wrong or I am missing something?

thanks!

Carlo

**Comment by javiereguiluz** [comment]
Hi! I think that the current docs are correct ... and that's why for example the reason why the Profiler shows the events in this order: from higher to lower:

![image](https://user-images.githubusercontent.com/73419/66138183-7b06ae00-e5fe-11e9-9c8f-1c90b6a8b3a0.png)

I've asked in the #support channel of Symfony Slack to double check and they told me that they think that what docs say is correct.

So, could you please double check your code and if the unexpected behavior persists, give us some code to reproduce the issue to see what's happening and help you? Thanks!

**Comment by capaio** [comment]
hello,today it seems to work as it is supposed to. Sorry for false alarm :)
