### ISSUE TITLE
Additional performance tips for your Symfony app (per component)

### ISSUE THREAD

**Issue by dkarlovi** [symfony/symfony-docs#12438]
On the [Performance](https://symfony.com/doc/current/performance.html) page, all the performance related tips could be collected / linked to in a checklist form, example:

https://symfony.com/blog/new-in-symfony-4-1-faster-serializer

This is valuable information which you can completely miss if you haven't followed the blog.

There is, I expected, much more content like this all over the blog and docs, having it in one place would be a great resource for any Symfony dev.

**Comment by javiereguiluz** [comment]
Thanks for this proposal. We've started to do this for some of the new features (see an example here: https://github.com/symfony/symfony-docs/pull/13124/files).

I'm closing this issue as "fixed" because it's a "never-ending issue" (this is something we must keep doing) so there's no need to keep it open forever. Thanks.
