### ISSUE TITLE
Security: Explain best way to redirect to login form after logging out

### ISSUE THREAD

**Issue by ThomasLandauer** [symfony/symfony-docs#12547]
What do end-users expect after clicking a "Logout" button? My answer:
1. a success message ("You were logged out")
1. the login form (in case they forgot something, or logged out accidentally)

In Symfony's terms: They should be redirected to the login page, with the success message displayed there.

Since this is not covered on https://symfony.com/doc/current/security.html#logging-out I'm suggesting to include a best-practice example there - instead of having each user come up with their own solution:

* Adding a routing parameter (e.g. `@Route("/login/{loggedOut}", name="login")` doesn't work, since `logout: target:` (in `security.yaml`) needs to be a scalar, so you can't pass the routing parameter.
* So it looks like you need to set up a Controller for `target`. This would either redirect to `login/logged-out`, or add a flash message to the session and redirect to `login`. Both feels hacky due to the 2 consecutive redirects.

I'm sure this is a common use-case, so you should give an example.

**Comment by javiereguiluz** [comment]
Thomas, I'm afraid I must close this proposal as "won't fix". The reason is the same I mentioned in another of your issues: it looks more like a tutorial or custom business logic rather than a general-purpose doc.

The idea of Symfony Docs is only to explain each tool (how to add logout to your app; how to configure where to go after logout; how to render templates; how to display temporary messages (flash messages); etc.). Then you can build a custom feature using several of those individual tools. *(Please note that in the existing docs there might be cases where we don't follow this rule strictly, but it's the general rule)*.

I know that my answer may be disappointing ... but we have literally hundreds of features pending of being documented *(223 issues at the moment of writing this comment)* so hopefully you will understand this decision. Thanks.
