### ISSUE TITLE
Missing documentation about getConfig() and getOptions() methods

### ISSUE THREAD

**Issue by o-alquimista** [symfony/symfony-docs#12815]
For instance, if you want to retrieve the form options array within a Form Events listener:
```
$event->getForm()->getConfig()->getOptions();
```
Or to retrieve a specific option:
```
$event->getForm()->getConfig()->getOption('optionName');
```

But I couldn't find any instance of these two methods anywhere in the Symfony Docs (4.4 and 5.0).

**Comment by xabbuh** [comment]
Developers usually should not need to make use of the methods provided by the `FormConfigInterface`. So I'd rather not document it all.

@HeahDude What do you think?

**Comment by HeahDude** [comment]
This seems to be a really advanced use case, because options are available when registering/creating listeners in a type and are generally passed to it with `use` for lambda or through constructor when using subscribers.
The defined options should not leak outside the scope of a type since there are used to dynamically configure the form and the view, even the listeners themselves.

So I tend to agree with @xabbuh here.

**Comment by o-alquimista** [comment]
It's okay. I did not know about [inheriting variables from the parent scope](https://www.php.net/manual/en/functions.anonymous.php) in anonymous functions. I'll try to use this instead of getConfig().

Thanks. I'm closing this then.
