### ISSUE TITLE
[Messenger] Show message & handler(s) class description in debug:messen…

### ISSUE THREAD

**Issue by fabpot** [symfony/symfony-docs#13310]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#35978
| PR author(s) | @ogizanagi
| Merged in    | 5.1-dev

**Comment by javiereguiluz** [comment]
I don't understand this new feature well, but the only place where we show the output of `debug:messenger` is at the end of this article: https://github.com/symfony/symfony-docs/blob/master/messenger/multiple_buses.rst

@ogizanagi should we update that article? Thanks.

**Comment by ogizanagi** [comment]
Actually I didn't think this feature was worth a documentation update, but since we're showing its output, why not.

This feature adds in the output the messages & handlers descriptions from their docblock, allowing to document the use-cases they cover in the application. In a similar fashion as the `debug:autowiring` command showing autowirable interfaces description.
