### ISSUE TITLE
[Security] Add full example for "magic link" login system

### ISSUE THREAD

**Issue by ThomasLandauer** [symfony/symfony-docs#13407]
By "magic link" I mean an url containing a token, e.g. example.com/sadklfjdsf87897sadjfdsf897

Magic links are an important use case for two reasons:
* They're becoming more popular as a "full" way of logging in
* Everybody using a traditional login form also needs a magic link system for password recovery

So I'm suggesting to add a full example, in addition to the existing "login form" and "API token" examples: https://symfony.com/doc/current/security/form_login_setup.html and https://symfony.com/doc/current/security/guard_authentication.html

Question:
What's the advantage of setting up a custom Authenticator over just doing it like explained at https://gist.github.com/azhararmar/0a952cf03b1cfbd2a5b059089b764491 ? Which (dis)advantages does each approach have?

**Comment by ThomasLandauer** [comment]
I created a gist which could be used as a starting point: https://gist.github.com/ThomasLandauer/668d7353dc5794da62be4cec9e8091ab

**Comment by javiereguiluz** [comment]
Thomas, thanks for your proposal ... but I'm afraid we can't add docs like that. The reason is that it looks more like a tutorial, and in the Symfony Docs we prefer to only document Symfony features instead of a tutorial.

I know that some existing articles look like a tutorial (e.g. the login form setup) but they are describing step-by-step a built-in Symfony feature. This "magic link" tutorial, although cool, would be describing a custom-made feature not provided by Symfony. That's why I'm afraid it's out of the scope of Symfony Docs.

**Comment by wouterj** [comment]
However, please feel free to write a blog post about it! The scope of documentation is rather small. Blogposts cover a wide range of articles and topics (from close to not-so-close related to Symfony) & can help the community just as much as documentation can.
