### ISSUE TITLE
[Security] Idea for restructuring the docs

### ISSUE THREAD

**Issue by ThomasLandauer** [symfony/symfony-docs#13413]
Here's an idea to restructure https://symfony.com/doc/current/security.html completely - sort of a follow-up of https://github.com/symfony/symfony-docs/issues/11505

* Start with a *minimal* `security.yaml`, then explain the options for the three main components:
* User
* Login: Guard or Controller. Voters or Roles or Controller.
* Routes: `security.yaml` or Controller

For each of these, explain which approaches are available and what pros and cons they have. Always start with a minimal approach (i.e. doing it "manually" in the controller), then show the advantages of professionalizing it.

**Comment by javiereguiluz** [comment]
Hi. Thanks for your proposal Thomas. We appreciate your dedication to help us improve the docs.

However, the security docs are a bit special. They are extremely critical (any mistake in the docs can make your app vulnerable), extremely important and extremely complex to write. That's why we're working on them privately in the Symfony Docs team. Our friend @wouterj is working together with @weaverryan in a complete revamp of the Security code and features. Once that is finished, we'll discuss internally in the Symfony Docs team how to proceed with the total revamp of the Security docs.

We'll take into account your comments (and others added in the past by other community members) ... but meanwhile we're going to close this to not open the public discussion about this yet. Thanks for understanding ... and thanks again for all your help!!!

**Comment by ThomasLandauer** [comment]
@wouterj @weaverryan I just created a gist for a "magic link" login system, which (I think) should be covered in the new docs.
