### ISSUE TITLE
Adding NGINX Unit to the list of web servers in setup/web_server_configuration.rst

### ISSUE THREAD

**Issue by artemkonev** [symfony/symfony-docs#13596]
Hi,

Will the community welcome a pull request adding a NGINX Unit section (https://unit.nginx.org) to the list of web servers in [web_server_configuration.rst](https://github.com/symfony/symfony-docs/blob/5.0/setup/web_server_configuration.rst)? I imagine something similar to this: https://unit.nginx.org/howto/symfony/

**Comment by javiereguiluz** [comment]
Hi Artem!

Sorry for the late reply and thanks for your proposal. I've asked internally about this ... and we prefer to not add these docs directly to the Symfony Docs. The reason is that we don't have the knowledge or resources to know if these docs are outdated or if they need any maintenance.

Instead, I propose you to publish these docs in your own site and we'll be glad to link to that reference article from the Symfony Docs. We already do that with lots and lots of technologies in the current docs, so we think it would work here too. Thanks!

**Comment by artemkonev** [comment]
Hi, Javier,
That's an entirely reasonable approach. Here's the link, then: https://unit.nginx.org/howto/symfony/
If the howto requires any changes in terms of setting up Symfony itself, please let me know.

**Comment by javiereguiluz** [comment]
Closing as fixed by #13687.  The change will be online in a few hours, after the entire Symfony Docs are rebuilt. Thanks.

**Comment by artemkonev** [comment]
Great, thank you, @javiereguiluz !
