### ISSUE TITLE
Translation component docs not accessible

### ISSUE THREAD

**Issue by flack** [symfony/symfony-docs#13661]
if you click on the Docs link for the Translation component here:

https://symfony.com/components

It's supposed to take you to 

https://symfony.com/doc/current/components/translation.html

But instead you get a 301 redirect to

https://github.com/symfony/translation

Does that mean that there is no documentation on how to use Translation outside of the fullstack framework? If so, maybe just remove the link or point it to https://symfony.com/doc/current/translation.html instead

**Comment by javiereguiluz** [comment]
@flack you guessed it right: we've removed the Translation component docs (see https://github.com/symfony/symfony-docs/pull/12861). We're going to do that with all components that have different docs for stand-alone usage and "inside Symfony" usage. We decided to do that because the current docs are unmaintainable otherwise. Thanks for understanding.
