### ISSUE TITLE
[Notifier] Notifier component is missing on component list page

### ISSUE THREAD

**Issue by Steveb-p** [symfony/symfony-docs#13711]
As seen here: https://symfony.com/doc/master/components/index.html

![image](https://user-images.githubusercontent.com/3183926/82964810-ae031500-9fc6-11ea-84b9-ef64eac8437c.png)

There is no Notifier component visible. 

And yes, I use dark scheme and I love it :heart:

**Comment by wouterj** [comment]
You are correct. We're removing the current component docs in favor of better docs for framework users + guidance in the components' README. This is a slow process, as we don't want to remove any usefull docs - so we slowly read all component docs and move relevant pieces to other places before removing the docs. That's why the component list at the moment appears to be incomplete.

So unfortunately, there won't be any Notifier component docs (at least for now). There is docs on how to use it in the framework: https://symfony.com/doc/current/notifier.html

If you want to use it outside the component, you're a bit on your own. As a start, you can checkout the `Texter`, `Chatter`,  `Notifier` and `Transport` classes in the `Symfony\Component\Notifier`, that should help you get the component initialized :)

**Comment by Steveb-p** [comment]
> You are correct. We're removing the current component docs in favor of better docs for framework users + guidance in the components' README.

Then this issue is moot :) I wasn't aware of it and I agree completely.

Thanks @wouterj
