### ISSUE TITLE
MicroKernel documentation

### ISSUE THREAD

**Issue by Knallcharge** [symfony/symfony-docs#13827]
**Symfony version(s) affected**: 4.4.0+

**Description**  
The documentation about "Building your own Framework with the MicroKernelTrait" has an error in the import-function for loading annotations:
https://symfony.com/doc/4.4/configuration/micro_kernel_trait.html#advanced-example-twig-annotations-and-the-web-debug-toolbar

**How to reproduce**  
use the import-function as stated in the documentation: $routes->import(__DIR__.'/../src/Controller/', '/', 'annotation');

**Possible Solution**  
use the import-function as given: $routes->import(__DIR__.'/../src/Controller/', 'annotation');
see https://github.com/symfony/symfony/blob/4.4/src/Symfony/Component/Routing/Loader/Configurator/RoutingConfigurator.php
The second parameter is $type, so "annotation" should be given here, not "/".

**Comment by xabbuh** [comment]
FYI, I have transferred the issue to the documentation repository.

**Comment by javiereguiluz** [comment]
I'm closing this because it's probably fixed after these changes made by @wouterj -> https://github.com/symfony/symfony-docs/pull/13919#issuecomment-654843699

@Knallcharge the change you mention is correct ... but not for 4.4 branch but for 5.1 branch an up. If you check the same doc but in 5.1, you'll see that now we're using the right method signature: https://symfony.com/doc/current/configuration/micro_kernel_trait.html#advanced-example-twig-annotations-and-the-web-debug-toolbar  Thanks for reporting this issue!
