### ISSUE TITLE
[HttpClient] Add MockResponse::getRequestMethod() and getRequestUrl() t…

### ISSUE THREAD

**Issue by fabpot** [symfony/symfony-docs#13929]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#36487
| PR author(s) | @javespi
| Merged in    | 5.2-dev

**Comment by javiereguiluz** [comment]
In Symfony Docs we don't document every method of every component. It would be simply impossible. So, I propose to close this as "won't document". First, because it doesn't look essential. Second, because discoverability is trivial (you don't need to configure or install anything, your IDE will show the methods).
