### ISSUE TITLE
[Profiler] Missing documentation about how to style profiler pages

### ISSUE THREAD

**Issue by nusje2000** [symfony/symfony-docs#14467]
Symfony defines a handful of classes that can be used to style a profiler page. This isn't documented though so using this styling is mostly done by looking at other profilers and copying stuff. It would be nice to have some form of documentation about how to style these pages.

## Proposal
Add a "How to style custom profilers" documentation page containing an explanation for things like tables, metrics, collapsing blocks, etc.

**Comment by javiereguiluz** [comment]
@nusje2000 thanks for proposing this change. However, we must close this as "won't fix".

The main reason is that Symfony doesn't provide a "UI toolkit" with visual components or widgets that you can reuse in your own profiler panels. It's true that we have some of those widgets that we reuse in the built-in panels ... but it's an internal thing without any guarantee (they can change or be removed without notice).

That's why I'm afraid that the recommended way is to check existing panels (e.g. Symfony's built-in ones) and adapt those to your needs ... but there's no formal doc about that and we're not planning to add it. Sorry for the disappointing answer but I cannot give you a better one. Thanks for understanding!
