### ISSUE TITLE
Stopwatch missing completely in current versions' docs

### ISSUE THREAD

**Issue by ThomasLandauer** [symfony/symfony-docs#14476]
This page doesn't have a version > 3.4: https://symfony.com/doc/3.4/components/stopwatch.html
Searching for "stopwatch" doesn't find anything: https://symfony.com/doc/4.4/index.html
And no Stopwatch in the list at https://symfony.com/doc/4.4/components/index.html

**Comment by wouterj** [comment]
It's now documented here: https://github.com/symfony/stopwatch#getting-started and here: https://symfony.com/doc/4.4/performance.html#profiling-applications (the only build in framework usage of stopwatch is within the profiler)

**Comment by ThomasLandauer** [comment]
Is this the new plan to move components docs away from symfony.com to their GitHub page?

https://symfony.com/components/Stopwatch is empty (i.e. useless), and https://github.com/symfony/stopwatch#getting-started replaces all the information that was at https://symfony.com/doc/3.4/components/stopwatch.html by one single code block.

Is this the future of Symfony documentation?

**Comment by wouterj** [comment]
The plan is to focus on framework usage and remove component documentation from symfony.com. So instead of documenting how to use a component standalone, we document how to use a component in the Symfony framework. Then, for our standalone users, we add an code example to the README to introduce them to how to set-up the component in a non-Symfony application.
Some utility components, like HttpClient, are more focused on standalone usage and get a little more attention for standalone usage in the Symfony docs.

Most of the component docs has been moved to https://symfony.com/doc/4.4/performance.html#profiling-applications , it's still documented

**Comment by ThomasLandauer** [comment]
> the only build in framework usage of stopwatch is within the profiler

Well, that's not true. I'm using the Stopwatch in *Console Commands* within the Framework. I certainly wouldn't call that "profiling" - it's just measuring time using a, well, stopwatch ;-)

Suggestion:
Could you redesign the component pages like https://symfony.com/components/Stopwatch :
* Move the "Resources" sidebar to the center, right under "Installation" (it's certainly more important than the list of projects)
* Have **two** links there: "Documentation for Framework Users" and "Documentation for Standalone Users"
* Merge https://symfony.com/doc/4.4/components/index.html into https://symfony.com/components and link "Components" in the breadcrumb navigation to this page.
