### ISSUE TITLE
"How to Use PdoSessionHandler to Store Sessions in the Database" should redirect or be pointed to new page

### ISSUE THREAD

**Issue by ansien** [symfony/symfony-docs#14482]
**Problem:** When you do a google search for: "How to store sessions in database Symfony" the first result that shows up points to the old page. This way of configuring the PdoSessionHandler causes  problems when running any console command (because while the container is being built there needs to be a valid database connection due to the getWrappedConnection).

**Solution:** Redirect old page to new page, or place a clear notice somewhere on the page.

**Old page (< Symfony 4.3):** https://symfony.com/doc/4.0/doctrine/pdo_session_storage.html
**New page:** https://symfony.com/doc/current/contributing/documentation/overview.html

**Comment by pableu** [comment]
@ansien Did you mean to propose https://symfony.com/doc/current/session/database.html as the "new page" URL?

And I don't know how they usually solve that in the docs. Is the notice at the top of the page not good enough?

> WARNING: You are browsing the documentation for Symfony 4.0 which is not maintained anymore. Consider upgrading your projects to Symfony 5.2.

**Comment by javiereguiluz** [comment]
Sadly this is out of our control. We do as much as we can (e.g. we carefully define "canonical pages" so Google doesn't show duplicated results, etc.) but then this is under Google's control. When I make this search for example, I get different results, because the new page is shown first:

![image](https://user-images.githubusercontent.com/73419/102625842-58e74600-4146-11eb-84a2-c188ce2c2419.png)

So, we're closing this. Thanks!
