### ISSUE TITLE
[Intl] deprecate polyfills in favor of symfony/polyfill-intl-icu

### ISSUE THREAD

**Issue by nicolas-grekas** [symfony/symfony-docs#14532]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#38974
| PR author(s) | @nicolas-grekas
| Merged in    | 5.x

**Comment by javiereguiluz** [comment]
I'm closing this one as "nothing to fix" because, as mentioned in the original issue (https://github.com/symfony/symfony/issues/37758):

> The only impact would be on projects requiring symfony/polyfill-intl-icu and actually using the symfony/intl APIs without noticing they don't define a requirement for them, as symfony/intl might not be installed anymore. But the symfony/polyfill-intl-icu package does not document that these APIs become available due to the implementation details.

**Comment by Tobion** [comment]
I think https://symfony.com/doc/5.3/components/intl.html needs to be updated for this. So maybe it's good to reopen this.

**Comment by javiereguiluz** [comment]
I don't understand the changes we need to do in https://symfony.com/doc/5.3/components/intl.html:

* Instead of `composer require symfony/intl` we must tell developer to install `symfony/polyfill-intl-icu`?
* Should we tell them to install `symfony/polyfill-intl-icu` but only if they need to access to Country/Language/etc. data?
* Does this `symfony/polyfill-intl-icu` package must be installed but only optionally if you want to access to Country/Language/etc. data and your local PHP installation doesn't provide it?

Thanks!

**Comment by Tobion** [comment]
> This component provides access to the localization data of the ICU library. It also provides a PHP replacement layer for the C intl extension.

Only the first sentence in the documentation is correct. The polyfill for the intl extension is deprecated and people should use symfony/polyfill-intl-icu instead.

So this part of the intl component doc can also be removed
> If you install the component via Composer, the following classes and functions of the intl extension will be automatically provided if the intl extension is not loaded: ...
