### ISSUE TITLE
[Documentation] On page "Configuring a Web Server", a configuration directive is missing/incorrect for apache

### ISSUE THREAD

**Issue by BarthDELUY** [symfony/symfony-docs#14615]
Hi,

I've encoutered a bug in Symfony's documentation tonight.
Current setup : Symfony 5.2 running on Apache 2.4.37, on up-to-date CentOS 8 with php-fpm (version 8.0, but the bug happens also in 7.4, it's linked to a bad apache configuration).

I've setup Symfony for the fist time tonight, and I've spent too much time trying to understand a "No route for Get img/logo.png".

I followed the doc here : https://symfony.com/doc/5.2/setup/web_server_configuration.html

In paragraph "Adding Rewrite Rules", there is the following statement : 

> In production servers, you should move the .htaccess rules into the main Apache configuration file to improve performance. To do so, copy the .htaccess contents inside the <Directory> configuration associated to the Symfony application public/ directory (and replace AllowOverride All by AllowOverride None):

And in the sample configuration file below, line 8, there is 
> \# Copy .htaccess contents here

The .htaccess content needs to be modified when copied into the apache vhost file : 
> RewriteCond %{REQUEST_FILENAME} !-f

needs to be tweaked to 

> RewriteCond **%{DOCUMENT_ROOT}/**%{REQUEST_FILENAME} !-f

Otherwise, Apache 2.4 won't find the files, and redirects the requests to index.php no matter what : https://stackoverflow.com/a/29321034

I feel like this information should be inserted in Symfony's documentation as the documentation is incorrect in its current version (or remove the "copy .htaccess" paragraph since it's misleading).
The problem is present in the documentation for all maintained versions of Symfony (4.4, 5.1, 5.2, 5.3).

**Comment by javiereguiluz** [comment]
@BarthDELUY thanks for reporting this. Sadly we cannot change this here in the Symfony Docs, because the contents to copy come from a "Symfony recipe" related to Apache; this one --> https://github.com/symfony/recipes-contrib/blob/master/symfony/apache-pack/1.0/public/.htaccess

Checking its contents I see this: https://github.com/symfony/recipes-contrib/blob/3e81695f75df528a1c5656b87514ed0f270100cb/symfony/apache-pack/1.0/public/.htaccess#L23-L31

In theory, that config should solve your issue too. Can you please check if the contents that you copied are the same as in the latest version of that Symfony Apache config? If the error still persists, please open an issue at https://github.com/symfony/recipes-contrib/issues to mention that the Apache recipe doesn't work in some cases. Thanks!
