### ISSUE TITLE
[Stopwatch] missing maintained versions pages

### ISSUE THREAD

**Issue by RyanFarrah67** [symfony/symfony-docs#14654]
The `Stopwatch` component described here : https://symfony.com/doc/5.0/components/stopwatch.html don't have the documentation pages for the currents maintained versions.  
As you will see, the 4.4, 5.1, 5.2 and 5.3 aren't present.

The same problem appears here : https://symfony.com/doc/5.0/components/index.html, as you will see the component is missing for the currents maintained versions.

**Comment by javiereguiluz** [comment]
@RyanFarrah67 we've removed the standalone docs for the Stopwatch component because we intend to remove all standalone component docs and integrate them in the rest of the Symfony Docs.

In an ideal world we'd document components and Symfony apps separately ... but we don't have the resources to do so, so we decided to focus on Symfony Docs only. The newer docs for the Stopwatch component can be found integrated in the Performance article: https://symfony.com/doc/current/performance.html#profiling-symfony-applications
