### ISSUE TITLE
[Routing] Recommended way to define routing

### ISSUE THREAD

**Issue by MrYamous** [symfony/symfony-docs#14764]
In the [current routing documentation](https://symfony.com/doc/current/routing.html#creating-routes), attributes are indicated as the recommended way to define routing, with a link to Symfony Best Practices doc.
In the current [Symfony Best Practices](https://symfony.com/doc/current/best_practices.html#use-attributes-or-annotations-to-configure-routing-caching-and-security), attributes and annotations seem to be considered as equals.

Should one of these ways be considered more recommended than the other?

**Comment by wouterj** [comment]
They are equal (in routing, they even use the same class IIRC).

Attributes were introduced in PHP 8. Because of that, they cannot be used in a PHP 7.4 or lower environment. If you're on PHP 8, I would say the native attributes are probably more recommended than the non-native annotations as it requires less packages. Performance isn't affected, as the routing configuration is optimized and dumped as PHP code in the production environment (so no annotations, attributes or config is read upon each request).

**Comment by MrYamous** [comment]
It's clear and makes sense to me, thx for your time 👍
