### ISSUE TITLE
A clue how to deal with datetime validation errors with single HTML5 text input

### ISSUE THREAD

**Issue by jontjs** [symfony/symfony-docs#14985]
See https://symfony.com/doc/current/reference/forms/types/date.html#rendering-a-single-html5-text-box , the final paragraph. 

"This can be tricky..." is comforting, but not very helpful! It would be useful to provide at least a clue how to tackle the problem. I've not yet thought very hard about it, but no simple solutions come to mind. 

Or maybe this is more of an issue with the built-in DateType not coping gracefully with badly-formatted data, and I should submit an issue (and PR, ideally!) for that?

regards,
Jon

**Comment by javiereguiluz** [comment]
Unless I'm missing something, the clue that you are looking for is provided in the "caution box" below that paragraph:

![note-tricky](https://user-images.githubusercontent.com/73419/122240492-1e2a5480-cec2-11eb-9aaf-d0e817389735.png)

The "tricky" part is to know which is the right format to use in the JavaScript datepicker to match the exact format Symfony expects. But we cannot document this more in detail because it all depends on the date formatting options of the datepicker being used.

So, I'm closing this ... but please tell me if I missed something. Thanks.
