### ISSUE TITLE
[Validator] Note about mandatory value is not precise?

### ISSUE THREAD

**Issue by wkania** [symfony/symfony-docs#15040]
Description of NotBlank constraint:
>  Validates that a value is not blank - meaning not equal to a blank string, a blank array, false or null (null behavior is configurable). 

Many constraints have this info:

> As with most of the other constraints, null and empty strings are considered valid values. This is to allow them to be optional values. If the value is mandatory, a common solution is to combine this constraint with NotBlank.

This applies to 2 of 4 NotBlank cases. All (probably) the constraints that have this note are invalid when the value is an empty array. But some like String Constraints accept `false` as an optional value; On the other hand `false` is invalid for Date, Country, or File.

Should there be a second type of note like this?
> As with most of the other constraints, false, null, and empty strings are considered valid values. This is to allow them to be optional values. If the value is mandatory, a common solution is to combine this constraint with NotBlank.

**Comment by xabbuh** [comment]
I have the feeling that also listing `false` here would be rather confusing. It's true that `false` would be treated as valid by many string-related constraint as it is validated the same as the empty string due to the type cast that is done.

However, I don't believe this is relevant to often in practice where you already have mechanisms which ensure some kind of type-safety. If that's not the case, I'd recommend to always use the `Type` constraint in addition.

**Comment by javiereguiluz** [comment]
Let's close this one for the reasons given by @xabbuh and we can reopen this in the future if we receive more reports. Thanks!
