### ISSUE TITLE
[ClockMock] Mocking Stopwatch seems to not work as described

### ISSUE THREAD

**Issue by denisvmedia** [symfony/symfony-docs#15127]
Given that I have Symfony 5.2 installed, I'm trying to work with time sensitive tests according to [this doc](https://symfony.com/doc/current/components/phpunit_bridge.html#time-sensitive-tests). Unfortunately, the given example doesn't work for me. But this is how it works:

```php
<?php

namespace App\Tests\Unit;

use PHPUnit\Framework\TestCase;
use Symfony\Bridge\PhpUnit\ClockMock;
use Symfony\Component\Stopwatch\Stopwatch;
use Symfony\Component\Stopwatch\StopwatchPeriod;

/**
 * @group time-sensitive
 */
class MyTest extends TestCase
{
    public function testSomething()
    {
        ClockMock::register(StopwatchPeriod::class); // without this line the test remains transient
        $stopwatch = new Stopwatch();

        $stopwatch->start('event_name');
        sleep(10);
        $duration = $stopwatch->stop('event_name')->getDuration();

        $this->assertEquals(10000, $duration);
    }
}
```

My `phpunit.xml.dist`:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- https://phpunit.readthedocs.io/en/latest/configuration.html -->
<phpunit xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="https://schema.phpunit.de/9.3/phpunit.xsd" backupGlobals="false" colors="true" bootstrap="tests/bootstrap.php">
  <coverage processUncoveredFiles="true">
    <include>
      <directory suffix=".php">src</directory>
    </include>
    <exclude>
      <directory suffix=".php">src/DataFixtures</directory>
      <directory suffix=".php">src/Test</directory>
      <file>src/Kernel.php</file>
    </exclude>
  </coverage>
  <php>
    <ini name="error_reporting" value="-1"/>
    <server name="APP_ENV" value="test" force="true"/>
    <server name="SHELL_VERBOSITY" value="-1"/>
    <server name="SYMFONY_PHPUNIT_REMOVE" value=""/>
    <server name="SYMFONY_PHPUNIT_VERSION" value="9.5"/>
  </php>
  <testsuites>
    <testsuite name="Project Test Suite">
      <directory>tests</directory>
    </testsuite>
  </testsuites>
  <listeners>
    <listener class="Symfony\Bridge\PhpUnit\SymfonyTestsListener"/>
  </listeners>
</phpunit>
```

Is it a documentation issue or am I doing it wrong?

P.S. I also noticed that Stopwatch itself lost its own documentation page in Symfony. I hope, it will not be abandoned.

**Comment by vinobastine** [comment]
@denisvmedia  clock mock cant work

**Comment by javiereguiluz** [comment]
I think there's been some misunderstanding.

In the docs: https://symfony.com/doc/current/components/phpunit_bridge.html#clock-mocking. you can read that calling `ClockMock::register()` is needed when the class that needs clock mocking is not the one directly related to your test. In this case, you want to mock `StopwatchPeriod`, which is not your class and that's why you need to call this.

About the missing docs, the basic docs related to the Stopwatch component are now in the README of the component: https://github.com/symfony/stopwatch and the docs about how to use it with Symfony have been moved to the Performance page: https://symfony.com/doc/current/performance.html#profiling-symfony-applications

This is a change that we plan to do to all docs related to components: move their docs to the normal docs related to the entire Symfony framework and leave the component-only usage details for the README of their repos.
