### ISSUE TITLE
[Form] Translation parameters are missing

### ISSUE THREAD

**Issue by micheh** [symfony/symfony-docs#15292]
In Symfony 4.3, the three config options `label_translation_parameters`, `help_translation_parameters`, and `attr_translation_parameters` were added to define custom translation parameters (see the [blog post](https://symfony.com/blog/new-in-symfony-4-3-improved-form-translation)).

But somehow they do not appear in the form type reference.

**Comment by javiereguiluz** [comment]
Thanks for reporting this issue ... but maybe there's been some misunderstanding.

These three options are already documented. See for example https://symfony.com/doc/current/reference/forms/types/choice.html, https://symfony.com/doc/current/reference/forms/types/entity.html, etc.

Maybe they are missing in some form types ... that's because the "inherited options" are handled manually and we make some mistakes. Please note that we're not going to fix that now, because we want to move to another tool to build/manage docs and we hope to automate this to not make any other mistakes. Thanks!
