### ISSUE TITLE
DotEnv: the link “the updated version of this page” leads to a missing page

### ISSUE THREAD

**Issue by alexislefebvre** [symfony/symfony-docs#15570]
On this page: https://symfony.com/doc/3.4/components/dotenv.html

When I click on the “the updated version of this page” link.

I see “Page not found”.

**Comment by jperovic** [comment]
Let me fill in some blanks here :) 

Via Google, I arrived to page https://symfony.com/doc/4.1/components/dotenv.html. Since this is currently not the latest version, it shows a friendly reminder that I should switch:

![image](https://user-images.githubusercontent.com/1048965/139349089-941f81df-17c6-4f5e-a4c0-ef3d666e9770.png)

Upon selecting a v5.3 from the drop-down I am being forwarded to: https://symfony.com/doc/current/https://github.com/symfony/dotenv.html

I figured it should have led me to https://symfony.com/doc/current/components/dotenv.html instead, which actually redirects to the part of the invalid URL from above: https://github.com/symfony/dotenv.html

**Comment by javiereguiluz** [comment]
@jperovic thanks for reporting this issue. We've just deployed some changes, so this should be fixed now.
