### ISSUE TITLE
[documentation] Localize Symfony documentation

### ISSUE THREAD

**Issue by madess11** [symfony/symfony-docs#15579]
Symfony is a powerful framework with very well-elaborated documentation.

However, I think that a localized documentation will allow us to make the framework more accessible to developers.
So, I propose that we write the documentation in at least two news languages.
I need your opinion please.

**Comment by wouterj** [comment]
Hi @madess11! Thanks for your suggestion :)

We've had translated documentations many years ago, but removed them. The reality is that this repository has so much activity that a small team of translators cannot keep their docs in sync (more PRs are merged in this docs repo than in most other libraries code repo). Outdated docs do a lot more harm to a community than only english docs.

However, there is a very valuable resource that is more stable. This is the Fast Track book, which is only updated every 6 months. Because of this, it does have active translators and it is translated in many languages: https://symfony.com/doc/current/index.html (see the "read it for free" tooltip). The book, writing more in a tutorial style, covers many aspects of the Symfony framework.
