### ISSUE TITLE
The documentation doesn't seem to explain how to use bundles

### ISSUE THREAD

**Issue by ghost** [symfony/symfony-docs#15772]
The Symfony documentation seems to not clearly document how to use bundles.

It tells how to register a bundle and create a bundle, but does not tell how to access it from the controllers.

Maybe there should be answers to some faq-like questions, such as "what is a bundle?", "how do I access bundles after injecting them", etc.

**Comment by dbrumann** [comment]
The doc page on [bundles](https://symfony.com/doc/current/bundles) contains a small introduction what a bundle is, but I guess it could be improved. Do you have any suggestions what you are missing from the description?

> It tells how to register a bundle and create a bundle, but does not tell how to access it from the controllers.

A bundle is not accessed from controllers. You can use services from a bundle in a controller just like you can any other service provided by the framework (e.g. via the FrameworkBundle) or written by yourself in the `App\`-namespace. Which services a bundle provides (if any) depends on the specific bundle, but using them is the same as with any other service, which is already documented.

**Comment by ghost** [comment]
"Do you have any suggestions what you are missing from the description?"

It says basically nothing relevant about what a Bundle is. It says "A bundle is similar to a plugin in other software, but even better.". Ok, in the abstract I can understand what is a plugin. But this doesn't help me at all. What actually happens when I add a Bundle to config/bundles.php?

For example, if I install a composer package, I get a class that I can import. So this is what a package actually is. "A package is a class that you can import to your PHP files". Yes, it can be more than that, but at least this simple descriptive case gives me something concrete. Now if all I knew was that "a composer package is like a program you install in your computer, but even better", this wouldn't help me.

"A bundle is not accessed from controllers. You can use services from a bundle in a controller"

Got it. So the bundle gives me a service and I access the service. So basically what happens when a bundle is registered in bundles.php is that it's services become available to Symfony?

**Comment by derrabus** [comment]
> So basically what happens when a bundle is registered in bundles.php is that it's services become available to Symfony?

Yes.

**Comment by javiereguiluz** [comment]
@davidmoseler in your original issue (#15771) you said that the bundles page doesn't explain how to use or what to do with bundles like JMSSerializerBundle.

As we mentioned in the original issue, this is intended. There are thousands of bundles and all are different between them. Some do a lot, some do little. Some require a lot of steps to complete their installation, others require nothing on your side. Some provide services to use in your controllers/services and others don't do that.

That's why you need to read the specific docs of the bundles that you are using. I hope our answer is more clear now. Thanks.

**Comment by ghost** [comment]
@javiereguiluz However, there is probably a well defined interface between a bundle and symfony and a precise definition of what a bundle is and how it becomes accessible. If there were no such definition, the code would not work, since code does not understand a statement like "A bundle is similar to a plugin in other software, but even better.".

It seemed from the discussion earlier that this interface is the registration of a service. But even after the discussion it was still not clear if this was the only part of the interface. And now you say that some bundles do not even provide services.

Let's say it that way: either there is something in common between all bundles that allow them to be called "bundles", or there is a set of possible ways a bundle can interact with Symfony. Either way, this should be clear.

Otherwise, I can ask: what is the difference between a Symfony bundle and a composer package? It seems that most bundles are actually installed via composer, with possible additional steps. So, what IS the difference between a bundle and a generic composer package? Notice that everything in your answer applies to any composer package, not only bundles.

So, in the end, I still don't know what a bundle is! Even with the clarifying discussion here. Imagine for someone that only read the docs.

Finally, JMSSerializerBundle has also a documentation issue, because their docs assume that you know how to access the $container variable and that this funcionality on the Symfony side was not deprecated. But it was. So it becomes a two-sided issue: Symfony assumes that the bundle developers have proper updated documentations. But, if they don't, the Symfony docs don't give me enough information as a "consumer-side" developer fix the issue (I would have to either become a bundle-side developer or a symfony-side developer for a while). To make matters worse, Symfony doesn't update IT'S documentation when some interfaces change. For this specific example, JMSSerializerBundle was accessible via the $container variable, this form of accessing services was deprecated by Symfony, Symfony did not update the docs to tell developers (both consumer or bundle side developers) of this deprecation, bundle developers did not update their documentations, service injection for JMSSerializerBundle is broken, and, summing everything up, the whole thing becomes a huge mess.

**Comment by mbabker** [comment]
> However, there is probably a well defined interface between a bundle and symfony and a precise definition of what a bundle is and how it becomes accessible. If there were no such definition, the code would not work, since code does not understand a statement like "A bundle is similar to a plugin in other software, but even better.".

There really isn't much more of a "well-defined interface" for a bundle though.  Ultimately, a bundle is a PHP package typically downloaded and installed through Composer which at a minimum contains some classes to nicely integrate the package into a Symfony application.  A bundle could be nothing more than "glue code" which creates service definitions for yet another third-party package inside a Symfony application (for example, [Flysystem](https://github.com/thephpleague/flysystem) is a standalone PHP filesystem package and [flysystem-bundle](https://github.com/thephpleague/flysystem-bundle) is a separate PHP package which provides a way to create services for Flysystem filesystems).  Or, a bundle could provide an integration for a third-party package that also adds some extra features specific to the Symfony environment context (not trying to self-promote here in any way, but I do this with [PagerfantaBundle](https://github.com/BabDev/PagerfantaBundle)).  Or, a bundle could be a fully-featured PHP package built specifically for Symfony to provide some feature (such as [LexikJWTAuthenticationBundle](https://github.com/lexik/LexikJWTAuthenticationBundle) which provides a JWT authentication solution).  Or, a bundle could be anywhere in the middle of those definitions.

So, what truly makes a `symfony-bundle` package type in Composer different from a generic `library` type, or more generically what makes a Symfony Bundle different from a PHP package?  Ultimately, a bundle isn't much more than a single PHP class implementing `Symfony\Component\HttpKernel\Bundle\BundleInterface` that is registered in your application's kernel, and said bundle class typically has a reference to a PHP class that implements `Symfony\Component\DependencyInjection\Extension\ExtensionInterface` that handles loading the services that bundle provides into the service container.  A bundle can be a generic PHP package, but a generic PHP package on its own can't be a bundle without at least having the bundle class.  And, using the `symfony-bundle` type in Composer allows Composer plugins (like Symfony Flex) to do things when installing or upgrading a package (which is how when you have Flex installed, a bundle is automatically added to your `config/bundles.php` file or recipes are automatically applied to your application).

> Finally, JMSSerializerBundle has also a documentation issue, because their docs assume that you know how to access the $container variable and that this funcionality on the Symfony side was not deprecated.

Just for reference, a lot of documentation both in the core Symfony docs and in the ecosystem uses a lot of example pseudo-code snippets that aren't going to be functional on their own.  Otherwise, "short" examples like `$container->get('foo');` would become over-complicated by having to explain how the container is built, how you inject the container, the difference between the root container and a service locator, etc.  There never has been a global `$container` variable inside of a Symfony application; generally, it ends up referring to a container that was injected through dependency injection or fetched from some other class/method.

Yes, accessing services directly from the service container was deprecated back in Symfony 3.4, see https://symfony.com/blog/new-in-symfony-3-4-services-are-private-by-default for more details on that.  There are still ways you can configure the container so you can fetch any service out of it, but generally, the practice is to use dependency injection and not try to fetch services from the container at runtime.  With current Symfony versions supporting autowiring and not requiring much manual container configuration, you can typehint `JMS\Serializer\SerializerInterface` and get the JMS Serializer instance.

Unfortunately, some packages are behind on some parts of their documentation, while other packages keep up their documentation quite well; this isn't a Symfony unique problem, it's just the way of the open-source world sometimes.
