### ISSUE TITLE
Wrong version when downloading zip

### ISSUE THREAD

**Issue by Krazitchek** [symfony/symfony-docs#15830]
Whichever version is selected (branch), it is version 5.4 of the documentation that Github offers to download.
Before, the downloaded zip corresponded well to the selected version (branch 4.4 -> 4.4.zip, branch 5.3 -> 5.3.zip).

**Comment by xabbuh** [comment]
Can you explain which download button you are talking about?

**Comment by Krazitchek** [comment]
Yes, i clic on the green button named "code" on top right part of the files list on symfony/symfony-doc github page, then on the link Download ZIP. I always do that to download and compile locally the documentation  as explained on project page. I choose the desire version on the dropdown branches button, then "code" button and download zip.

**Comment by javiereguiluz** [comment]
@Krazitchek I can reproduce this. I don't know how it was before, but now it always downloads 5.4 version instead of the version that matches the selected branch.

In any case, this is a GitHub bug, so please contact them at https://support.github.com/contact

Meanwhile, clone the repository with Git and then select the branch with `git checkout 5.3`, `git checkout 4.4`, etc.
