### ISSUE TITLE
Translate documents into other languages

### ISSUE THREAD

**Issue by karaka200** [symfony/symfony-docs#15960]
Is it possible to translate documents into other languages?
If not, is it not better to do these translations to improve this issue?

**Comment by xabbuh** [comment]
There have been translations of the documentation in the past. Unfortunately, these translations were constantly out-of-sync with the English version. That's why we decided to no longer promote any of these translations some years ago.

However, if you are looking for resources in other languages, [the fast track book](https://symfony.com/book) is available in many different languages.

I hope this helps you, but I am going to close here anyway as we won't change the situation for the whole documentation regarding translations. Thank you for understanding.
