### ISSUE TITLE
Too Many Redirects

### ISSUE THREAD

**Issue by marcoiosif** [symfony/symfony-docs#16031]
Hello, I get this error following this link:

https://symfony.com/doc/5.3/components/security/authentication.html

ERR_TOO_MANY_REDIRECTS

Thanks

**Comment by javiereguiluz** [comment]
Thanks for reporting this problem. Sadly, we are aware that this error happen sometimes recently.

In my local machine I can't reproduce this error and when browsing that URL, I get redirected to `/current/components/security/authentication.html` with just one HTTP redirect.

On symfony.com I clicked on that URL and I saw the same ERR_TOO_MANY_REDIRECTS error ... I left the page untouched, and my browser retried the URL some seconds later ... and it worked.

Does anybody know if it's something that could happen because of some condition that affects Cloudflare somehow? Thanks!

**Comment by marcoiosif** [comment]
Now is working. Very strange. Regards

**Comment by javiereguiluz** [comment]
I've asked around on Symfony's Slack and the general consensus is that this looks like a browser cache issue. I can't reproduce locally, I can't reproduce it either when using `curl` ... and the problem "solves by itself" just by letting the browser make a lot of attempts. We're closing this for now as "fixed" ... but we'll be on alert for any new feedback about this. Thanks!

**Comment by chapterjason** [comment]
@javiereguiluz https://symfony.com/doc/current/frontend/encore/installation.html was also affected several minutes ago. Clear cache fully worked.

**Comment by javiereguiluz** [comment]
I can't reproduce this locally yet. I can only see it when someone reports it ... but then the error "solves by itself". We don't deploy any change or fix between the error report and the time when the page works again. This is really strange 🤔

**Comment by GromNaN** [comment]
That sounds like a cache pollution issue. There a request that results in a 301 that have the same cache key than the expected 200.
