### ISSUE TITLE
Remove <?php

### ISSUE THREAD

**Issue by TheGarious** [symfony/symfony-docs#16064]
I see lot of example of code including <?php and the rest not. 

Do we need include <?php for each example php code or not ?

**Comment by javiereguiluz** [comment]
Generally speaking we prefer to not add `<?php` in all examples ...

... but we received complaints from people (especially newcomers) which copy+pasted our code and it didn't work ...

... so we added `<?php` in articles aimed at newcomers but not in others.

Now that we have a new doc builder we may change this more easily than before. Let me ask internally to the Docs Team. Thanks!

**Comment by weaverryan** [comment]
The best solution might be inconsistency 😇 

For example, in a code block like this: https://symfony.com/doc/current/page_creation.html#creating-a-page-route-and-controller - we are showing the entire code, so having `<?php` makes sense because you can copy and paste. Most of our code blocks are probably like this.

But then consider this code block - which is a one-liner: https://symfony.com/doc/current/controller.html#rendering-templates

Adding `<?php` + a line break there would be ugly.

Overall, I'd vote to YES include `<?php`. But there ARE a few cases where it would be better to have the option to not include it.

**Comment by wouterj** [comment]
I still favor code blocks without the start tag (90% of the examples in the docs are incomplete and can't work when copy-pasting anyways. E.g. most of them are missing namespace declarations or use statements). The only exception we have is for the full code examples in the "getting started" guides.

**Comment by TheGarious** [comment]
Finally, if the example works with copy and paste then we need to have tag <?php, else other example we need to clean up example code. 

Do i have right ?

**Comment by javiereguiluz** [comment]
OK, so let's settle on Wouter's proposal. Let's add the `<?php` only to code samples that are complete PHP scripts ... not to partial code samples. Let's close this issue and if someone finds any code block missing `<?php` , please submit a pull request fixing it. Thanks!
