### ISSUE TITLE
Twig code highlighting not working always

### ISSUE THREAD

**Issue by alexander-schranz** [symfony/symfony-docs#16129]
Sometimes it seems the coce highlighting does not work always for twig.

https://symfony.com/doc/5.3/form/form_themes.html#applying-themes-to-single-forms

The rst file did look correctly.

**Comment by javiereguiluz** [comment]
This is tricky to solve ... because we rely on https://github.com/scrivo/highlight.php and if I'm right, they are not very open to contributions to improve highlighting because they want to be 100% similar to the original highlight.js library they are based on.

But somebody will need to look into this and see if we can do something to improve the situation (maybe contributing some improvements or at least update the list of reserved Twig keywords in highlight.js library).

**Comment by javiereguiluz** [comment]
Closing because sadly we can't fix this ourselves. If anybody is willing to help us, they should submit a PR to the project mentioned in the previous comment. Thanks!

**Comment by alexander-schranz** [comment]
Make sense, still thx for having a look at it.
