### ISSUE TITLE
Link to EasyAdmin documentation

### ISSUE THREAD

**Issue by truckee** [symfony/symfony-docs#16368]
If there is a link from [Symfony documentation](https://symfony.com/doc/current/index.html) to the docs available at [https://symfony.com/bundles](https://symfony.com/bundles) I've not yet found it. Perhaps it could be made more prominent.

If there is not, I suggest one be added.

**Comment by javiereguiluz** [comment]
In the Symfony Docs index page, there's a generic link to "Symfony Bundles Docs" at the bottom of the page.

We intend to keep it like that for now ... because most traffic comes from the bundles repositories directly (they point to their own docs hosted on symfony.com) and we also have the main "Symfony Bundles Docs" index page at https://symfony.com/bundles. Finally, we also have links to certain bundles in the contents of some Symfony Docs pages (e.g. security article recommends 2FA bundle; certain pages recommend MakerBundle, etc.).

In any case, thanks for your suggestion!
