### ISSUE TITLE
`InteractiveLoginEvent` is missing in the Security documentation

### ISSUE THREAD

**Issue by Seb33300** [symfony/symfony-docs#16387]
[This page](https://symfony.com/doc/current/security.html#security-events) list all the events available in the security component ([see here](https://github.com/symfony/symfony/tree/6.0/src/Symfony/Component/Security/Http/Event)), except the `InteractiveLoginEvent` which is missing.

Any reason for that?

This event was documented until version 5.2:
https://symfony.com/doc/5.2/components/security/authentication.html#authentication-events

**Comment by javiereguiluz** [comment]
@wouterj do you know if this was done on purpose because we don't want to show `InteractiveLoginEvent`? Thanks!

**Comment by wouterj** [comment]
Yes, I deliberately did not include the event when rewriting the security docs.

I would not recommend using this event (or the `InteractiveAuthenticatorInterface`), as its implemention in Symfony is very inconsistent:

| Authenticator | Interactive? |
| --- | --- |
| Form Login | yes |
| JSON Login | yes |
| HTTP Basic | **no** |
| Login Link | yes |
| X.509 Client Certificates | yes |
| Remote users | yes |
| Remember me cookies | **yes** |

As you can see, HTTP basic is considered non-interactive, while using the rememberme cookie is considered interactive. As this has been the case since v2.0, we unfortunately cannot change this. If there was a way to deprecate an interface or event, I would love to deprecate the interactive interface and event.

Instead of using the `InteractiveLoginEvent`, I recommend using the `LoginSuccessEvent`. If you need to explicitly include/exclude  some authenticators in your listeners, you can use an `instanceof` check with `$loginSuccessEvent->getAuthenticator()`.

**Comment by Seb33300** [comment]
Hello @wouterj 

`InteractiveLoginEvent` and `LoginSuccessEvent` are not really the same events.

I always thought that `InteractiveLoginEvent` may be a confusing name.
For me it was more an event triggered when a user "started a new interaction" with the app. Not necessary because the user manually click on something or submitted a something.

By new interaction I mean a new session of use = when a new session/token is created.
In this case, yes, the rememberme is interactive, because the cookie is used to re authenticate a user who is starting to interact with the app (after a long period of inactivity / closed brower...).
HTTP basic is non interactive because there is no way to know if the user just started to interact with the app or not.

For example, when working with JWT, the `LoginSuccessEvent` is triggered on all requests.
While the `InteractiveLoginEvent` should be triggered only on the request that will create the token.
