### ISSUE TITLE
Duplicated option in form type date

### ISSUE THREAD

**Issue by matthieuleorat** [symfony/symfony-docs#16466]
Hello,

I think a found an issue in the https://symfony.com/doc/current/reference/forms/types/date.html#choice-translation-domain page

 choice_translation_domain is display twice with some unwanted text i guess like "DEFAULT_VALUE" and :end-before: DEFAULT_VALUE"

I can contribute, but i don't know how to fix it.

Regards,
Matthieu

**Comment by Seb33300** [comment]
Just noticed the same issue.

This is because the `DEFAULT_VALUE` from https://github.com/symfony/symfony-docs/blob/5.4/reference/forms/types/options/choice_translation_domain.rst.inc is not properly replaced in https://github.com/symfony/symfony-docs/blob/5.4/reference/forms/types/options/choice_translation_domain_disabled.rst.inc and https://github.com/symfony/symfony-docs/blob/5.4/reference/forms/types/options/choice_translation_domain_enabled.rst.inc

Maybe the syntax to override templates changed with the new documentation system?
