### ISSUE TITLE
Anchor links do not respect back button in section table of contents

### ISSUE THREAD

**Issue by aar0nr** [symfony/symfony-docs#16497]
### How to reproduce

1. Visit a section, e.g. https://symfony.com/doc/current/service_container.html
2. Click on one of the anchor tags in the table of contents.
3. Click the back button on your browser.

### Expected outcome

The browser should return to the previous scroll position.

### Actual outcome

The browser's scroll position does not change.

### Meta

Chrome Version 98.0.4758.80

**Comment by javiereguiluz** [comment]
@aar0nr thanks for reporting. Sadly this is a known limitation of the current design, which is based on a complex set of flex `<div>`. The pros of the current design are much more than the cons (like the one you reported) so we think it's a reasonable trade-off. Thanks for understanding it.

As an alternative solution, you can use Ctrl./Command + Up Arrow to Instead of Backspace to go to the top of the page.
