### ISSUE TITLE
Internal link issue on Core team page

### ISSUE THREAD

**Issue by Seb33300** [symfony/symfony-docs#16517]
On the [core team page](https://symfony.com/doc/current/contributing/code/core_team.html), it seems that there is a small rendering issue with `[1]_` syntax that is an internal link to the bottom of the page:
```
.. [1] Minor changes comprise typos, DocBlock fixes, code standards
    violations, and minor CSS, JavaScript and HTML modifications. 
```

See https://github.com/symfony/symfony-docs/blob/6.0/contributing/code/core_team.rst#pull-request-merging-policy

**Comment by javiereguiluz** [comment]
@Seb33300 thanks for reporting this. Sadly, this is a known limitation of our new PHP-based RST parser. We don't support footnotes yet. However, we consider the unparsed contents are still readable:

<img width="1125" alt="note" src="https://user-images.githubusercontent.com/73419/155753583-3491b773-a57c-41b7-80ca-47d813857f04.png">

That's why we decided to consider this as "won't fix". The day the RST parser supports footnotes, this will be fixed automatically, so it's fine for now. In any case, thanks a lot for reporting this issue!
