### ISSUE TITLE
Unexpected redirect on version switch to github instead docs

### ISSUE THREAD

**Issue by alexander-schranz** [symfony/symfony-docs#16534]
When I'm one of the following links and click on the link:

 - https://symfony.com/doc/5.0/components/stopwatch.html
 - https://symfony.com/doc/3.3/components/translation.html
 
> Read [the updated version of this page](https://github.com/symfony/stopwatch) for Symfony 6.0 (the current stable version).
> Warning: You are browsing the documentation for [Symfony 3.3](https://symfony.com/releases/3.3), which is no longer maintained.
 
The link actually is targeting github I would expect to stay on the docs and not get from documentation redirected to github. Same for the version switch on the left.

**Comment by javiereguiluz** [comment]
@alexander-schranz actually, this is not a bug but a feature. We're removing the stand-alone components docs ... and integrating those into the regular Symfony Docs. We're leaving some minor contents in the README files of the components repositories explaining how to set up components when using them outside Symfony apps. That's why we redirect to those README files. Cheers!
