### ISSUE TITLE
[Form] The html5 option doesn't work as expected for DateTime types

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony-docs#16600]
In this page: https://symfony.com/doc/4.4/reference/forms/types/date.html#html5

We say that adding `['html5' => true]` is enough to display a native browser widget to pick dates.

I can't make it work. I need to use `['html5' => true, 'widget' => 'single_text']` to render those native widgets.

Am I doing something wrong or should we update the docs? Thanks!

**Comment by htmlshaman1** [comment]
Can confirm, setting html5 to true is not enough to show the html5 widget for me either.

I had to have 'single_text' to display the the html5 widget, which worked without html5 set to true. 

https://github.com/symfony/symfony/blob/4.4/src/Symfony/Component/Form/Extension/Core/Type/DateType.php#L192 

And when I look at the options passed to DateType, it defaults to html5 = true without me setting it, therefore 'single_text' is enough.

**Comment by mdoutreluingne** [comment]
I also confirm that I need to use `['html5' => true, 'widget' => 'single_text']`  or just  `['widget' => 'single_text']` 
(because html5 is true by default) for the types DateType, DateTimeType, TimeType to be considered as an html5 field, to then render the native widget.

I think we need to update the documentation because the wording is incomplete. For the 3 types that I have stated, it should be indicated that it is necessary to use `['html5' => true, 'widget' => 'single_text']` to render those native widgets.

What do you think ? If you affirm I can create a PR.

**Comment by xabbuh** [comment]
@mdoutreluingne Yes, that looks correct to me.

**Comment by javiereguiluz** [comment]
@xabbuh do you think we could improve the code of these Form types to simplify all this? Maybe using `widget => 'html5'` would be enough to say that you want to render the HTML5 native date widget of browsers?

**Comment by xabbuh** [comment]
@javiereguiluz That sounds like a good idea to me.

**Comment by nicolas-grekas** [comment]
Fixed in https://github.com/symfony/symfony/pull/49588
