### ISSUE TITLE
"toctree" text appears on HTML version of the page

### ISSUE THREAD

**Issue by mark2016** [symfony/symfony-docs#16613]
Hi, the guide to contributing documentation appears to have a build error, I expect from a syntax error in the underlying page.

URL to the problem page is https://symfony.com/doc/current/contributing/documentation/index.html

The page appears to have rendered incorrectly, as "toctree" is an instruction to build a table of contents, should not be visible in the rendered version:

![image](https://user-images.githubusercontent.com/16224288/158723607-20ff843e-abeb-46b7-975e-8644592ce343.png)

**Comment by javiereguiluz** [comment]
This hidden `toctree` was needed when using Sphinx as the RST parser because Sphinx requires all files to be included in some toctree. Now that we use a different, and more tolerant, RST parser I think this is no longer needed. So, I'm trying to fix this in #16632 just by removing this unneeded toctree.
