### ISSUE TITLE
[Messenger] Allow AsMessageHandler attribute on methods

### ISSUE THREAD

**Issue by fabpot** [symfony/symfony-docs#16657]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#45273
| PR author(s) | @mjpvandenberg, @fabpot
| Merged in    | 6.1

**Comment by wouterj** [comment]
@mjpvandenberg thanks for this cool feature. To make sure everyone knows about this when 6.1 will be released next month, do you have time to add a small "tip" box in https://symfony.com/doc/current/messenger.html#creating-a-message-handler about this new functionality? (having multiple handle methods in a single class instead of `__invoke()`)

**Comment by mjpvandenberg** [comment]
No problem, see https://github.com/symfony/symfony-docs/pull/16774
