### ISSUE TITLE
RetriedTillSaveStore is deprecated.

### ISSUE THREAD

**Issue by abeal-hottomali** [symfony/symfony-docs#16785]
The class `RetriedTillSaveStore`, mentioned in the docs [here](https://symfony.com/doc/current/components/lock.html#blocking-locks), is marked as `deprecated`.  Should be changed/removed?

**Comment by mdoutreluingne** [comment]
Thanks for your issue, I think here you mean the class `RetryTillSaveStore`.

I've created #16790 to fix the incorrance for version 6.0 documentation because the class was removed from Symfony 6.0.

If you want more detail regarding on this class that has been depreciated, see [here](https://github.com/symfony/symfony/pull/38296).
