### ISSUE TITLE
How to set encoder(8bit,base64 or quoted-printable) in symfony mailer

### ISSUE THREAD

**Issue by adnan-rasheed** [symfony/symfony-docs#16812]

**Comment by xabbuh** [comment]
Can you please elaborate a bit more what piece of information you are missing?

**Comment by adnan-rasheed** [comment]
@xabbuh there is an option in php mailer for setting content transfer encoding to one of these methods **8bit,base64, 7bit & quoted-printable**. Also there is way to set encoding method in swiftmailer but in symfony I did not see any documentation to set one of the value from above methods

**Comment by xabbuh** [comment]
I think we need an easy way to configure that in the code itself first (see symfony/symfony#44557).

**Comment by DavidPetrasek** [comment]
I would also need to change the encoding. See [#50409](https://github.com/symfony/symfony/discussions/50409).

**Comment by fritzmg** [comment]
In `SwiftMailer` `5.x` we had [`setEncoder`](https://github.com/swiftmailer/swiftmailer/blob/181b89f18a90f8925ef805f950d47a7190e9b950/lib/classes/Swift/Mime/Headers/AbstractHeader.php#L125-L134) + [`get8BitEncoding`](https://github.com/swiftmailer/swiftmailer/blob/181b89f18a90f8925ef805f950d47a7190e9b950/lib/classes/Swift/Encoding.php#L28-L36) etc. so you could do

```php
$message->setEncoder(\Swift_Encoding::get8BitEncoding());
```

However, this was removed in `6.x`: https://github.com/swiftmailer/swiftmailer/commit/d210d674809310dac02da09b372bf74a8047c2ab

**Comment by mpichot** [comment]
I'm wondering why this was removed? :thinking:
I can't find a good solution to encode emails other than quoted-printable.
Anyone?

**Comment by javiereguiluz** [comment]
I'm closing this one because the related code issue was closed after "expiring" (https://github.com/symfony/symfony/issues/44557).

Please, try to ask about this in the GitHub Discussions or Slack chat shown in https://symfony.com/support If there's enough interest, the next step would be to create an issue in the code repository and try to gather some support for it. Finally, there could be a PR in the code repository and then we would document it here.

Thanks for understanding.

**Comment by fritzmg** [comment]
No need to create a new issue. The last comment in the original issue states:

> Feel free to comment if this is still relevant, I can always reopen!
