### ISSUE TITLE
Replace annotations with attributes in code examples

### ISSUE THREAD

**Issue by ker0x** [symfony/symfony-docs#16877]
Currently, the documentation is composed of a mix between annotations and attributes in the different code examples.

For example, the[ Mercure documentation](https://symfony.com/doc/current/mercure.html#web-apis) uses Doctrine attributes while the [Serializer documentation](https://symfony.com/doc/current/serializer.html#using-serialization-groups-annotations) use Annotations.
Same goes for the [Controller documentation](https://symfony.com/doc/current/controller.html#a-basic-controller) and the [Mailer documentation](https://symfony.com/doc/current/mailer.html) with the `Route` annotation/attribute!

The support for annotation [has been recently dropped](https://github.com/symfony/maker-bundle/pull/1126) in the maker bundle for Entities and the `Route` attribute is already use when generating Controller, 

So, in order to be consistent everywhere, wouldn't it be interesting to replace annotations with attributes when possible?

**Comment by javiereguiluz** [comment]
After thinking about this, I propose the following:

* Let's keep showing both annotations and attributes in the main article about some topic which uses both
* Let's use only attributes in the other articles not related to that topic

Practical example:

Routing: use annotations + attributes in `routing.rst` article ... but only use attributes in all the other docs whenever we want to display the route of a controller

Possible exceptions:

Doctrine annotations are quickly disappearing because even the Maker bundle now only generates attributes, so maybe we should only show attributes in all pages.

What do you think? Ping @symfony/team-symfony-docs

**Comment by fabpot** [comment]
I would use PHP attributes everywhere.

**Comment by xabbuh** [comment]
I agree with Fabien.

**Comment by wouterj** [comment]
I would say:

- Show both on the 5.4 docs
- Only use attributes in 6.0+

This way, people can have a look at the LTS docs if they are still using annotations, and we don't have the maintenance burden going forward

**Comment by OskarStark** [comment]
I agree with @wouterj

**Comment by javiereguiluz** [comment]
OK, so it seems that there's a consensus around Fabien's idea and Wouter's implementation. Let's do that 🙌

**Comment by weaverryan** [comment]
Yup - Wouter wins again!

**Comment by alexislefebvre** [comment]
Maybe pinning this issue would give it visibility and encourage people to update the different pages?
