### ISSUE TITLE
Broken references on the BC page

### ISSUE THREAD

**Issue by alexislefebvre** [symfony/symfony-docs#17118]
Here: https://symfony.com/doc/4.4/contributing/code/bc.html#changing-interfaces

It it shown “Yes [2]_” instead of a link to the reference.

It affects all the maintained versions.

**Comment by javiereguiluz** [comment]
The root problem is that our RST parser doesn't support footnotes. We considered that this is OK because the parser result is not broken (you can still see the footnote numbers).

However, there are other issues ... such as some footnotes mysteriously disappearing from the generated HTML content. E.g. where are footnotes 6 and 9?

<img width="311" alt="" src="https://user-images.githubusercontent.com/73419/183935745-696150fb-6a84-4bd6-9f40-776b6a6143e0.png">

So, in #17144 I propose to remove footnotes and use normal internal references instead.
