### ISSUE TITLE
Add the idea that the serializer component is best used typically with DTO

### ISSUE THREAD

**Issue by torian257x** [symfony/symfony-docs#17161]
watch the introduction here

https://www.youtube.com/watch?v=XxIhzgGv214

**Comment by wouterj** [comment]
As also mentioned in that video, what is "best" is dependent on context (e.g. the scale of the product and team). This is also why we don't normally tend to have any opinion on application architecture in the Symfony docs. Anything written on symfony.com is seen as "official". This can lead to overly complicated projects that could have been written much simpler, if Symfony is recommending an approach that is only useful at a big scale.

I think the Serializer docs are written generic enough to not explicitly recommend serializing entities, nor recommend always creating DTOs.

For these reasons, I'm going to close this issue for now.
However, blog posts are a great way to share more opinionated practices (they are written by you as a person, rather than Symfony as the authorizing organization). So I would like to invite you to write a blog post about DTOs and serializers and sharing it with the community (e.g. in the `#posts` channel on Slack) if you feel like this practice needs more attention in the community.

**Comment by torian257x** [comment]
well... I disagree. Using entities for serialization is an opinion and depends on the context, just as do DTOs. At least mention it is a viable solution as well, and solves many issues like hiding attributes in certain contexts, and dont hide them in others. And solve circular reference. 

But TBH I dont have the energy for this discussion.
