### ISSUE TITLE
[Mime] Simplify adding Parts to an Email

### ISSUE THREAD

**Issue by fabpot** [symfony/symfony-docs#17303]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#47462
| PR author(s) | @fabpot
| Merged in    | 6.2

**Comment by wouterj** [comment]
This should be documented together with https://github.com/symfony/symfony-docs/issues/17353

The sections that require update (using `addPath()` instead of `attach*()`/`embed*()`) are https://symfony.com/doc/current/mailer.html#file-attachments and https://symfony.com/doc/current/mailer.html#embedding-images I think.

**Comment by hiddewie** [comment]
I made https://github.com/symfony/symfony-docs/pull/17372 to document both symfony PRs.
