### ISSUE TITLE
Split "Framework configuration reference" into multiple per-component pages

### ISSUE THREAD

**Issue by rimas-kudelis** [symfony/symfony-docs#17420]
The [Framework configuration reference](https://symfony.com/doc/current/reference/configuration/framework.html) page currently documents all configuration options for all Symfony components in one page. Combined with visually not very distinctive font size differences between H3 (component name) and H4 (option name), this makes it a little difficult to quickly find which options are available for each specific component (e.g. HTTP client or Forms). It would probably be easier to read that information if this page was split into multiple per-component pages, each detailing only options relevant to one specific Symfony component.

**Comment by javiereguiluz** [comment]
Rimas, thanks for this proposal.

In the symfony-docs team we've been discussion about this for years. This page is indeed too long, but a while ago we started removing component docs from Symfony Docs _(we no longer explain components separately but within the rest of the documentation)_ so there's no place to put those options in "the component page" because components no longer have their own page.

For now we're going to keep this long page. hopefully the index at the top of the page and the browser search can help folks navigate its contents. Thanks for understanding.

**Comment by rimas-kudelis** [comment]
@javiereguiluz well thanks for closing this as "completed" when it certainly isn't. :P

What I proposed by "per-component pages" wasn't to scatter this info everywhere, but to split this specific page into a simple flat structure of multiple pages. Right now you have it all under `doc/current/reference/configuration/framework.html`, but you could have `doc/current/reference/configuration/form.html` for Form config reference, `doc/current/reference/configuration/validation.html` for Validator, `doc/current/reference/configuration/translator.html` for Translator and so on. Or you could even put these pages one level deeper – e.g. `doc/current/reference/configuration/framework/translator.html`, and turn the current `framework.html` into a table of contents (by keeping in it only the index you mentioned).

I don't see how this suggestion conflicts with your move away from per-component documentation (although I must say I quite like current per-component docs as well – they just make it easier to find what I'm looking for, since I usually know what component I'm dealing with).

Please reconsider. Thanks!

**Comment by javiereguiluz** [comment]
I'm reopening so other Docs Team members can share their opinion if they want. Thanks

**Comment by rimas-kudelis** [comment]
Thank you.

**Comment by javiereguiluz** [comment]
I'm closing because this proposal didn't get any feedback in the past months.

As I originally said, this is complicated _(the current page is long ... but having all things related to the framework config in a single page is very convenient fro most readers)_. We've talked internally about this many times ... and I'm sure we'll keep talking about this.

Meanwhile, let's close becase we won't work on this in the near term. Thanks for understanding 🙏
