### ISSUE TITLE
[Doctrine] Recommend `$repository->save()` instead of `$em->persist()`

### ISSUE THREAD

**Issue by ThomasLandauer** [symfony/symfony-docs#17429]
Since `make:entity` now generates `->save()` and `->remove()` in the entity's repository, I'm suggesting to introduce this as best practice on https://symfony.com/doc/current/doctrine.html instead of the current approach.

I'm not coming up with a PR right away, cause this would require a larger reorganization of the page:
* The repository needs to be introduced earlier (i.e. higher) in the page. And it needs to be "rebranded" from the place to *query* for entities to the place to *manage* (get/query, save, update, ...) the entities.
* Subsequently, all cases of injecting the entity manager could be replaced by injecting the repository.

Good idea?

**Comment by javiereguiluz** [comment]
We've discussed about this internally and we've decided to not do this. Otherwise, docs could only be properly followed by people using the `make:entity` command to generate their entities.

I know that in other parts of the docs we mention `make:entity` and even show its output. But in those cases, he code generated by `make:entity` is the same that you should write yourself (the command just helps you being more productive).

Thanks for understanding.
