### ISSUE TITLE
Add performance advanced solutions

### ISSUE THREAD

**Issue by raziel057** [symfony/symfony-docs#17428]
As we can see more and more solution trying to run Symfony with async event driven or other modern servers (swoole, openswoole, amp, workerman, frankenphp), it would be interesting to provide tips or links to the different solutions. It could be added in a specific section of the https://symfony.com/doc/current/performance.html page.

Frankenphp and Workerman support with AdapterMan seems particularly interesting ([see last benchmark here](https://www.techempower.com/benchmarks/#section=test&runid=49216ea1-34d5-4715-a5a2-3dff8a1855f5&f=zik0zj-zik0zj-zik0zj-zik0zj-zik0zj-zik0zj-zik0zj-zik0zj-zik0zj-zik0zj-v2qiv3-zik0zj-zik0zj-e7)). It use the exact same code.

Maybe it would make sense to increase the popularity of these solutions, by providing advises (pro/cons).

References
https://frankenphp.dev/
https://github.com/joanhey/AdapterMan
https://github.com/walkor/workerman
https://openswoole.com/
https://github.com/swoole/swoole-src

**Comment by joanhey** [comment]
Added Frankenphp to the bench.
https://github.com/TechEmpower/FrameworkBenchmarks/pull/7748

Now only in normal mode with plain php.
Later I'll try with Worker mode and Symfony.

**Comment by joanhey** [comment]
Added Symfony Swoole using phpruntime
https://github.com/TechEmpower/FrameworkBenchmarks/pull/7753

**Comment by raziel057** [comment]
@joanhey thank you. Good to see viable solutions that improves performances of high quality PHP Frameworks.

**Comment by joanhey** [comment]
Added Symfony with Frankenphp in Worker mode using phpruntime
https://github.com/TechEmpower/FrameworkBenchmarks/pull/7756

**Comment by javiereguiluz** [comment]
@joanhey thanks for working on this 🙏 

Just out of curiosity, how are the numbers that you see when running these benchmarks on your local machine? How much faster is the app when running via FrankenPHP? Thanks.

**Comment by joanhey** [comment]
Hola Javier

Normally I don't bench locally because it's unrealistic, but we get some numbers in the test verification.
But this latency time is with only 1 user, it's more important the scalability.
With more req/s, the latency scale very fast.
Plain php have a very low latency, but don't scale with fastcgi.

### Symfony Fortunes test
**Fastcgi:**
![image](https://user-images.githubusercontent.com/249085/204827271-1111987b-a0fd-4bae-ae58-3a24754ec2e0.png)

**Swoole using phpruntime:**
![image](https://user-images.githubusercontent.com/249085/204844889-54d8ccdd-0d25-4420-ab6e-820478b65e3f.png)

**Frankenphp using phpruntime:**
![image](https://user-images.githubusercontent.com/249085/204820372-0d21a87e-896f-4a56-b1f0-c41d3d678b69.png)

**Workerman using Adapterman:**
![image](https://user-images.githubusercontent.com/249085/204820233-7802365a-b623-4feb-a657-8d081e0e220e.png)

**Comment by joanhey** [comment]
<blockquote class="twitter-tweet"><p lang="en" dir="ltr"><a href="https://twitter.com/hashtag/php?src=hash&amp;ref_src=twsrc%5Etfw">#php</a> <a href="https://twitter.com/symfony?ref_src=twsrc%5Etfw">@symfony</a> added <a href="https://twitter.com/php_swoole?ref_src=twsrc%5Etfw">@php_swoole</a> and <a href="https://twitter.com/hashtag/frankenphp?src=hash&amp;ref_src=twsrc%5Etfw">#frankenphp</a> using the phpruntime to the TechEmpower benchmark.<br>In some days we&#39;ll have the numbers to compare vs <a href="https://twitter.com/workermanphp?ref_src=twsrc%5Etfw">@workermanphp</a> using <a href="https://twitter.com/adaptermanphp?ref_src=twsrc%5Etfw">@adaptermanphp</a> <a href="https://t.co/J5TgoiRPn5">https://t.co/J5TgoiRPn5</a></p>&mdash; Adapterman (@adaptermanphp) <a href="https://twitter.com/adaptermanphp/status/1598001970484506625?ref_src=twsrc%5Etfw">November 30, 2022</a></blockquote>

**Comment by joanhey** [comment]
The initial tests are not too good for FrankenPHP.
But remember that is new, and need more work and optimizations.
These numbers will be better with time. And I'm in contact with dunglas, to help with any information.

Still not finished the run, also no results from Swoole and Workerman without a framework yet (in 2 days will finish the run).

Only platform runtimes without a framework, FrankenPHP without Worker mode:
![image](https://user-images.githubusercontent.com/249085/205910977-abd2a9e4-65a6-4f67-a66a-c77141f9ba46.png)
Latency
![image](https://user-images.githubusercontent.com/249085/205911143-da773f81-efc0-498c-9cff-13cf459fed7c.png)


In some hours we will have all Symfony runtimes using the same code, and will be a more fair comparison.

The link: https://www.techempower.com/benchmarks/#section=test&runid=124fd2af-3030-4315-8876-e1db1fa91193&test=fortune&l=xan9xb-35r&o=3&c=3

**Comment by joanhey** [comment]
The symfony results are ready:
![image](https://user-images.githubusercontent.com/249085/206164964-55696293-d3e7-4792-bbb1-89f52f82946e.png)

So we'll show the json and single query:

**Json**
![image](https://user-images.githubusercontent.com/249085/206165570-3d694b37-fca3-4daf-8eb5-57ea1b1cd539.png)

Latency
![image](https://user-images.githubusercontent.com/249085/206165613-2e94887f-7eca-432c-a36a-cc70a1f8db55.png)


**Single query**
![image](https://user-images.githubusercontent.com/249085/206165381-714cb398-1d4c-4b12-8058-ddcafc45d02b.png)
Latency
![image](https://user-images.githubusercontent.com/249085/206165496-f04635fc-0338-4b88-9af5-435699f69af2.png)


The link to visualize the results:
https://www.techempower.com/benchmarks/#section=test&runid=124fd2af-3030-4315-8876-e1db1fa91193&test=json&f=zik0zj-zik0zj-zik0zj-zik0zj-zik0zj-zik0zj-zik0zj-zik0zj-zik0zj-zik0zj-v2qiv3-zik0zj-zik0zj-cn3

**Comment by joanhey** [comment]
This benchmark is the most fair, as all the runtimes use the same framework and code.

**Comment by javiereguiluz** [comment]
Folks, we're closing this as "won't fix".

The reason is the same as explained here: https://github.com/symfony/symfony-docs/pull/18432#issuecomment-1597417283

We prefer to keep this article focused on the changes/tweaks you can do in your Symfony app and in some very specific PHP ini settings to improve performance.

Using servers that provide async features is important for some apps, but those projects will need to document how to integrate them with Symfony apps. Thanks for understanding!
