### ISSUE TITLE
[Performance] Remove preloading?

### ISSUE THREAD

**Issue by 94noni** [symfony/symfony-docs#17643]
What about removing this part:
https://symfony.com/doc/6.1/performance.html#use-the-opcache-class-preloading

With Symfony v6.1 which requires PHP v8.1, I have understood it is no more relevant

**Comment by alexislefebvre** [comment]
> With Symfony v6.1 which requires PHP v8.1, I have understood it is no more relevant

I didn't found a clear explanation but Symfony members wrote this:

>  But then, preloading itself is going to be almost useless as of PHP 8.1.

Source: https://symfony.com/blog/symfony-6-1-will-require-php-8-1

> preloading is also mostly dead since 8.1

https://github.com/symfony/symfony/pull/44380#pullrequestreview-819949886

**Comment by OskarStark** [comment]
can you please help here @nicolas-grekas ? Thank you

**Comment by greg0ire** [comment]
Preloading gives 2 benefits:
1. it reduces the number of autoload calls (if everything you need is preloaded, there are no autoload calls)
2. it links types together, performing signature compatibility checks before hand.

With PHP 8.1, the second benefit is almost gone because of a newly introduced inheritance cache that also has to do with signature compatibility checks, see this benchmark: https://github.com/php/php-src/pull/6627#issuecomment-775869140

Benefit number 1 still stands though, but depending on the application, it may or may not be dwarfed by other things. On my applications, which are very few, I haven't been able to witness a significant impact from preloading. Would be nice to have benchmark from other people on other apps.

**Comment by 94noni** [comment]
closing as related code PR was closed
