### ISSUE TITLE
No MapEntity documentation

### ISSUE THREAD

**Issue by speller** [symfony/symfony-docs#17847]
3 months left since the MapEntity and other action argument resolvers were introduced https://symfony.com/blog/new-in-symfony-6-2-built-in-cache-security-template-and-doctrine-attributes, but still, there's no documentation about it.

**Comment by javiereguiluz** [comment]
Here you have the MapEntity documentation: https://symfony.com/doc/current/doctrine.html#mapentity-options

The real problem is that the doc search is bad (see #17775) but we're working non-stop at the moment to fix it. In fact, in my local machine, I can look for MapEntity and I get the expected results.

Cheers!
