### ISSUE TITLE
Config Component / Loading from database

### ISSUE THREAD

**Issue by micter59** [symfony/symfony-docs#17874]
Hello,

I want to use the Config Component to load from and store in database.
I'm from far not an expert with Symfony, but I usually find a lot of informations in the doc and in symfony casts videos.
But this time I've hard time to find anything usefull about this.
Strangely I can't find examples about this specific usage.

The principal page is there : https://symfony.com/doc/current/components/config.html
I've been looking at the linked page at the bottom, but it's not evident for me.
In fact, the only mention I can find is the first paragraphe, which mention :
"source may be (YAML, XML, INI files, or for instance a database)."

I've found this issue with seems to be related to mine :
https://github.com/symfony/symfony-docs/issues/9293

In this one, someone talk about an (example ?) application.
But I don't know how / where to get it.

Do you know where I can find documentation about this usage please ?

**Comment by wouterj** [comment]
Hi!

Loading configuration from a database is not something that is often done, which is why you probably have a hard time finding it. I think you'll have to write your own config loader and work from there: https://symfony.com/doc/current/components/config/resources.html
But I'm honestly not totally sure if the config component is the right component for use-cases that involve a database.

If you have more questions, please use one of the support channels instead of this issue tracker: https://symfony.com/support

**Comment by micter59** [comment]
Thanks for your answer. I'll also keep in mind the support section for the next time.
