### ISSUE TITLE
[Messenger] Add Clock support in Worker

### ISSUE THREAD

**Issue by fabpot** [symfony/symfony-docs#18093]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#49730
| PR author(s) | @fabpot
| Merged in    | 6.3

We created this issue to not forget to document this new feature. We would really appreciate if you can help us with this task. If you are not sure how to do it, please ask us and we will help you.

To fix this issue, please create a PR against the 6.3 branch in the [symfony-docs repository](https://github.com/symfony/symfony-docs).

Thank you! :smile:

**Comment by alexandre-daubois** [comment]
Searched for some time but I wasn't able to find a proper place to document this. The reason is we never mention the `Worker` class anywhere in the documentation. Should this be closed? Or should we have more info about the use cases [it seems to be](https://github.com/symfony/symfony/pull/49730#pullrequestreview-1347467723)?

**Comment by alamirault** [comment]
I'm not sure we should document this change. Looks to be an "internal" change for using new Component without real new functionality for devs (out of the box)
