### ISSUE TITLE
Request for version selector to remember last-selected version

### ISSUE THREAD

**Issue by givihuda** [symfony/symfony-docs#18264]
I frequently hit the docs by Google search or other websites, and then because I'm working with different versions of Symfony that aren't the latest, I keep having to select the particular version. What would make more sense is for the site to remember the version I had selected last, and just go to that version for the page.

Is that possible? Or feasible? It would certainly prevent a lot of user actions or unwanted page hits.

**Comment by herberterich** [comment]
![Uploading 6BD1132A-B8BC-46ED-942A-CB0865B4F74F.jpeg…]()

**Comment by javiereguiluz** [comment]
This was asked in the past too and sadly we cannot implement it. The reason is that it would introduce some weird experiences.

For example, you visit the docs of X.Y version and that it's stored locally in your browser. Now, you Google something about Symfony Docs which was introduced in a most recent version than X.Y. Your browser does an automatic redirection to that page in X.Y version ... which doesn't exist, so you see a 404 error.

Browsers don't have the data/logic needed to decide if the automatic redirection to the saved version is going to work or result in a 404 error.

So, let's close this as won't fix. Thanks for your understanding!
