### ISSUE TITLE
[HttpClient] Allow custom working directory in TestHttpServer

### ISSUE THREAD

**Issue by fabpot** [symfony/symfony-docs#18469]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#50814
| PR author(s) | @ro0NL
| Merged in    | 6.4

We created this issue to not forget to document this new feature. We would really appreciate if you can help us with this task. If you are not sure how to do it, please ask us and we will help you.

To fix this issue, please create a PR against the 6.4 branch in the [symfony-docs repository](https://github.com/symfony/symfony-docs).

Thank you! :smiley:

**Comment by javiereguiluz** [comment]
Let's close this as "won't merge" because this is just a new method argument which is easy to discover for those who need it.

The important feature related to this that we'll have to document is the one proposed in this issue (if it's implemented) --> https://github.com/symfony/symfony/issues/50830
