### ISSUE TITLE
[Changelog] Put forward a link to the changelog of each component

### ISSUE THREAD

**Issue by epitre** [symfony/symfony-docs#18460]
When moving to a newer version of a component, it is important to know what changed.  
I believe the documentation should be the entrypoint.  
As it would be too much work to write documentation specific to the migration to a newer version, maybe having, in each component doc, a link to the changelog of this component in github would be a start.

WDYT ?

**Comment by javiereguiluz** [comment]
Thanks for your proposal. My vote would be 👎 for this because of some reasons:

1) It adds a bit more maintenance for us and we already have a lot of things to do

2) The CHANGELOG and UPGRADE files from code repository are not that useful for docs ... those files just mention very briefly what changed/deprecated, but they usually don't explain anything or include any example. So, their contents are not very actionable

3) The docs already include `versionadded` and `deprecated` sections, so I think we are not missing any important information from the changelog

Let's wait and see what others think. Ping @symfony/team-symfony-docs  Thanks!

**Comment by OskarStark** [comment]
I agree with Javier here 👍

**Comment by weaverryan** [comment]
I agree also. We have limited real estate to work with to not lose people's attention. Thank you for the suggestion!
