### ISSUE TITLE
[Validator] Remove deprecated code paths

### ISSUE THREAD

**Issue by nicolas-grekas** [symfony/symfony-docs#18489]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#50857
| PR author(s) | @nicolas-grekas
| Merged in    | 7.0

We created this issue to not forget to document this new feature. We would really appreciate if you can help us with this task. If you are not sure how to do it, please ask us and we will help you.

To fix this issue, please create a PR against the 7.0 branch in the [symfony-docs repository](https://github.com/symfony/symfony-docs).

Thank you! :smiley:

**Comment by javiereguiluz** [comment]
* [x] Remove static property `$errorNames` from all constraints, use const `ERROR_NAMES` instead
   (I can't find occurrences of this in the docs)
* [x] Remove `VALIDATION_MODE_LOOSE` from `Email` constraint, use `VALIDATION_MODE_HTML5` instead
   (fixed in #18493)
* [x] Remove constraint `ExpressionLanguageSyntax`, use `ExpressionSyntax` instead
   (fixed in #18502)

**Comment by javiereguiluz** [comment]
Closing as fixed
