### ISSUE TITLE
[7.0] Remove remaining deprecated code paths

### ISSUE THREAD

**Issue by nicolas-grekas** [symfony/symfony-docs#18507]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#50873
| PR author(s) | @nicolas-grekas
| Merged in    | 7.0

We created this issue to not forget to document this new feature. We would really appreciate if you can help us with this task. If you are not sure how to do it, please ask us and we will help you.

To fix this issue, please create a PR against the 7.0 branch in the [symfony-docs repository](https://github.com/symfony/symfony-docs).

Thank you! :smiley:

**Comment by javiereguiluz** [comment]
Form
----

 * [x] Throw when using `DateTime` or `DateTimeImmutable` model data with a different timezone than configured with the `model_timezone` option in `DateType`, `DateTimeType`, and `TimeType`
   (deprecated in #18475 and removed in #18479)
 * [x] Make the "widget" option of date/time form types default to "single_text"
   (deprecated in #18511 and removed in #18512)

FrameworkBundle
---------------

 * [x] Make the `http_method_override` config option default to `false`
   (deprecated in #18513 and removed in #18514)
 * [x] Remove `AbstractController::renderForm()`, use `render()` instead
   (remove the only occurrence in #18509)
 * [x] Remove the `Symfony\Component\Serializer\Normalizer\ObjectNormalizer` and
   `Symfony\Component\Serializer\Normalizer\PropertyNormalizer` autowiring aliases, type-hint against
   `Symfony\Component\Serializer\Normalizer\NormalizerInterface` or implement `NormalizerAwareInterface` instead
   Fixed in #18602 and #18603.
 * [x] Remove the `Http\Client\HttpClient` service, use `Psr\Http\Client\ClientInterface` instead
   (the only mention to `Http\Client\HttpClient` is being removed in #18500)

Messenger
---------

Fixed in #18520

 * [x] Remove `MessageHandlerInterface` and `MessageSubscriberInterface`, use `#[AsMessageHandler]` instead
 * [x] Remove `StopWorkerOnSigtermSignalListener` in favor of
   `StopWorkerOnSignalsListener` and make it configurable with SIGINT and
 * [x] Remove `Symfony\Component\Messenger\Transport\InMemoryTransport` and
   `Symfony\Component\Messenger\Transport\InMemoryTransportFactory` in favor of
   `Symfony\Component\Messenger\Transport\InMemory\InMemoryTransport` and
   `Symfony\Component\Messenger\Transport\InMemory\InMemoryTransportFactory`

Translation
-----------

 * [x] Remove `PhpStringTokenParser`
   (there are no mentions about this class in the docs)
 * [x] Remove `PhpExtractor` in favor of `PhpAstExtractor`
   (deprecated in #18515 and removed in #18516)

TwigBundle
----------

 * [x] Remove option `twig.autoescape`, use `twig.autoescape_service[_method]` instead
   (removed in #18517)
 * [x] Remove the `Twig_Environment` autowiring alias, use `Twig\Environment` instead
   (there are no occurrences of this in the docs)

Yaml
----

 * [x] Remove the `!php/const:` tag, use `!php/const` instead (without the colon)
   (the 45 occurrences of `!php/const` are free of the trailing `:`)

**Comment by javiereguiluz** [comment]
I've finished working on this issue.

There are still a few things to do related to Serializer and Messenger. Please, someone take care of those. Thanks a lot!

**Comment by alexandre-daubois** [comment]
Concerning

> Remove the Symfony\Component\Serializer\Normalizer\ObjectNormalizer and
Symfony\Component\Serializer\Normalizer\PropertyNormalizer autowiring aliases, type-hint against
Symfony\Component\Serializer\Normalizer\NormalizerInterface or implement NormalizerAwareInterface instead

I'm not sure how we should update this snippet:

https://github.com/symfony/symfony-docs/blob/96884d747a5b005d4b13321c2f2b6993344941b9/serializer/custom_normalizer.rst?plain=1#L27-L31

Using `NormalizerInterface` doesn't seem to work because of a circular reference. 🤔 I wasn't able to make it work with the `NormalizerAwareInterface/Trait` as well.

**Comment by alexandre-daubois** [comment]
Found how to update this one:

https://github.com/symfony/symfony-docs/blob/96884d747a5b005d4b13321c2f2b6993344941b9/serializer/custom_normalizer.rst?plain=1#L27-L31

Preparing the PR :slightly_smiling_face:

**Comment by javiereguiluz** [comment]
Closing as fixed completely! Thanks!
