### ISSUE TITLE
[Symfony Docs] Next and Prev button not working

### ISSUE THREAD

**Issue by alexander-schranz** [symfony/symfony-docs#19075]
For example in https://symfony.com/doc/current/create_framework/index.html the Next and Prev buttons seems to render empty box but never really be shown and so it hard to navigate through the whole Documentation as not always the end text has a next chapter link.

Even there is a next chapter they are empty and disabled:

<img width="533" alt="Bildschirmfoto 2023-10-23 um 10 45 23" src="https://github.com/symfony/symfony-docs/assets/1698337/7017a074-4645-4016-b168-e1e6d1418fa9">

<img width="792" alt="Bildschirmfoto 2023-10-23 um 10 45 06" src="https://github.com/symfony/symfony-docs/assets/1698337/fb7b656f-255a-4a2f-9005-56a8180d3ab9">

<img width="718" alt="Bildschirmfoto 2023-10-23 um 10 44 54" src="https://github.com/symfony/symfony-docs/assets/1698337/c1228491-1180-4cc0-a04a-a4428c389553">

**Comment by javiereguiluz** [comment]
Alexander, thanks for reporting this.

The issue here is that both `next` and `prev` are `null` in the generated contents when building docs. I've tried debugging why, but I can't find the exact cause. So, I've done two things:

* Hide the pagination in those pages (the pagination still works in other parts of the Symfony Docs, such as `/book`)
* Create an issue in the tool we use to build docs to see if someone can debug what's going on here: https://github.com/symfony-tools/docs-builder/issues/164

So, I'm closing this one ... and this will really solved if we can fix the issue in `symfony-tools/docs-builder`.

Thanks!
