### ISSUE TITLE
[Asset-Mapper] Bad examples between manual DL of CSS

### ISSUE THREAD

**Issue by ph-il** [symfony/symfony-docs#19164]
When you explain to download CSS manually, the documentation tel to add it to assets/vendor, but later, it recommended to Ignore the directory in git.

**Comment by smnandre** [comment]
Do you speak about CSS files directly linked to a JS package for example, or "any" CSS ? 

For the later, it's a CSS like any other, so you can keep it with your other CSS files.

If it's linked to a JS package, well .... it depends. As stated in the documentation, it may be "magical" or more manual, depending on the library (and would be the same if you installed it with npm), how you store your assets, how you compile them (or not) ... 

Some JS package may for instance use relative links between their assets (then the vendor path can be sensible), some do not, so really it depends.

But in any case, if you want to version it you must exlude it from your .gitignore.

How/what do you think could be explained differently in the docs ?

**Comment by javiereguiluz** [comment]
Let's close this one as fixed since AssetMapper docs have changed a lot in the past months. The section about handling CSS files explains the different options available: https://symfony.com/doc/current/frontend/asset_mapper.html#handling-css

As you said, in `assets/vendor/` you should only put the CSS files that can be downloaded automatically by AssetMapper. Any other CSS files should be in `assets/styles/` or any other custom dir configured by you. Thanks.
