### ISSUE TITLE
Emojis?

### ISSUE THREAD

**Issue by OskarStark** [symfony/symfony-docs#19270]
Do you think it makes sense to use an emoji here @symfony/team-symfony-docs 

![CleanShot 2023-12-12 at 13 27 36@2x](https://github.com/symfony/symfony-docs/assets/995707/8f667a83-3afe-49b3-b2e1-9af8109bb2f9)

**Comment by alexandre-daubois** [comment]
Makes it less verbose and more clear to me. Also, screen readers support emojis so I'm :+1: on this.

I like the fact it's a bit like a CTA, like "support for this one is done, down to implement an unsupported one?"

Just my two cent :smile:

**Comment by wouterj** [comment]
I see no real advantage. We're effectively only replacing 3 characters with 1. Imho, a symbol always has more ambiguity than a word, so if the symbol doesn't have a large advantage (e.g. reducing text density) I don't think it's worth it.

Besides, we've rejected using the em-dash (as opposed to the normal dash we use now in some places) in the past because it's hard to type on a normal international keyboard, making it more difficult to maintain the docs. I think the same holds true for these unicode characters.

**Comment by OskarStark** [comment]
Fair enough 👍 

If the majority of the docs team does not agree with @wouterj, please reopen this issue.
