### ISSUE TITLE
[FrameworkBundle] Move Router cache directory to `kernel.build_dir`

### ISSUE THREAD

**Issue by fabpot** [symfony/symfony-docs#19281]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#52962
| PR author(s) | @Okhoshi
| Merged in    | 7.1

We created this issue to not forget to document this new feature. We would really appreciate if you can help us with this task. If you are not sure how to do it, please ask us and we will help you.

To fix this issue, please create a PR against the 7.1 branch in the [symfony-docs repository](https://github.com/symfony/symfony-docs).

Thank you! :smiley:

**Comment by alexandre-daubois** [comment]
Had a look but it seems there's nothing to update here

**Comment by okhoshi** [comment]
Thanks @alexandre-daubois for jumping on this so quickly 🙏 

The only part I could see that would need an update is https://symfony.com/doc/current/reference/configuration/framework.html#cache-dir because the config is deprecated. I can take care of that update anyway :).

I now realize that one could set the `cache_dir` to `null` to disable the caching completely. I should reinstate that possibility.

**Comment by alexandre-daubois** [comment]
Ah yes, I missed this occurrence. PR always welcome if you're motivated to create it :slightly_smiling_face:

**Comment by okhoshi** [comment]
I'll create the PR once https://github.com/symfony/symfony/pull/53059 is merged :)

**Comment by alexandre-daubois** [comment]
I think you can create the PR even without your last PR merged. Ping me if you need help/review :+1:
