### ISSUE TITLE
Unable to setup Symfony 7.0 docs locally in my laptop

### ISSUE THREAD

**Issue by ousmanesinalydaou** [symfony/symfony-docs#19382]
I'm facing the following error when running the command "php build.php":

In FileIncluder.php line 47:

  Include ".. include:: /components/require_autoload.rst.inc" does not exist or is not readable.
  
  
 I would appreciate it if anyone could assist me in figuring out this issue!

**Comment by alamirault** [comment]
Can you run command with more verbosity in order to have a stacktrace ?  `php build.php -v`

**Comment by ousmanesinalydaou** [comment]
> Can you run command with more verbosity in order to have a stacktrace ? `php build.php -v`

I did that but I'm having the same error till now!

**Comment by xabbuh** [comment]
Which PHP version did you use? Can you please show the full output when running the command with `-v`?

**Comment by ousmanesinalydaou** [comment]
> Which PHP version did you use? Can you please show the full output when running the command with `-v`?

I'm currently using PHP 8.3.1 but I've tried it with different versions of PHP as well!

**Comment by javiereguiluz** [comment]
I just run this command in `7.0` branch of the docs and it worked as expected (my setup: macOS 14, PHP 8.3.1). Which operating system are you using?

**Comment by ousmanesinalydaou** [comment]
> I just run this command in `7.0` branch of the docs and it worked as expected (my setup: macOS 14, PHP 8.3.1). Which operating system are you using?

I'm using Windows 11

**Comment by javiereguiluz** [comment]
@ousmanesinalydaou sadly, the project we use to build docs (which is https://github.com/symfony-tools/docs-builder) doesn't support Windows yet.

We've just added Windows (and macOS) to the platforms tested in the project (see https://github.com/symfony-tools/docs-builder/pull/170) so we are aware of this error. Sadly, we can't estimate when (or even if) this error will be fixed.

In any case, let's close this issue here because we cannot fix it in this repository. Thanks!
