### ISSUE TITLE
Example Access Denied

### ISSUE THREAD

**Issue by MasterGHD** [symfony/symfony-docs#19679]
Hello Symfony Team!

I was check the documentation related to [security and denied responses](https://symfony.com/doc/current/security/access_denied_handler.html), and noticed that the first example does not work at version 7.x. 
I'm not sure if this applies to version 6.x.

The method "getFlashBag" no longer exists:
`$request->getSession()->getFlashBag()->add('note', 'You have to login in order to access this page.');`

Could you give a new example, similar to the current one?

**Comment by xabbuh** [comment]
It does exist. What error did you get?

**Comment by MasterGHD** [comment]
> It does exist. What error did you get?

1. I was using the autocomplete from PHPStorm, which it doesn't show, and the flash message doesn't show after a redirect (HTTP 302). For this feature, I use a twig component which captures all flash messages;
2. The code doesn't return any fatal error.

**Comment by javiereguiluz** [comment]
Let's close this one because the mentioned `getFlashBag()` still exists. This might be related to some other issue, so better try any of. the support channels shown at https://smyfony.com/support If you find any doc issue after getting support help, please add a comment here with more information and we'll reopen the issue. Thanks!
