### ISSUE TITLE
[Symfony v5.4] composer require webapp in setup.html

### ISSUE THREAD

**Issue by masaharu-suizu** [symfony/symfony-docs#19703]
Hi Symfony team.

Error messages returned from Composer when I try to install "webapp" in Symfony v5.4.

```
$ composer create-project symfony/skeleton:"^5.4" my_project_directory
$ cd my_project_directory
$ composer require webapp <- here
```
Error messages
![image](https://github.com/symfony/symfony-docs/assets/30203831/df61dcce-2e0e-4567-9c66-1b2059330107)

So, I changed the command as below.

```
$ composer require webapp:1.2.0
```

I could avoid the error messages from composer.
Is it possible to update https://symfony.com/doc/5.x/setup.html ?

**Comment by javiereguiluz** [comment]
Thanks for reporting this issue. Let's ask @nicolas-grekas because AssetMapper is only available since 6.3 and maybe we should add `"symfony/framework-bundle": "<6.3"` in the `conflict` section of https://github.com/symfony/webapp-pack/blob/main/composer.json

But I see that Nicolas added a conflict (for other reasons) and reverted it (see https://github.com/symfony/webapp-pack/commit/124fb85d004a1ab32de7af86f0d73b9e8fd1136f) so maybe this is not simple as that. Thanks.

**Comment by nicolas-grekas** [comment]
I force-pushed v1.3.0 of the pack with a conflict.

**Comment by javiereguiluz** [comment]
Thank you!
