### ISSUE TITLE
[Website] Links to method on Github maybe broken on Firefox

### ISSUE THREAD

**Issue by MrYamous** [symfony/symfony-docs#19709]
For example on this part of Http Client documentation : https://symfony.com/doc/current/http_client.html#native-php-streams

When I click on createResource link a new tab is opened on the StreamWrapper file but it doest not point to the function when i'm using Firefox (124.0.1).
If I switch to Chrome the link is fine.
Just a QOL issue but as I did not notice this kind of behavior before maybe something has changed recently. 

I do not know if it's an issue with my browser, does anyone else experience the same behavior?

**Comment by javiereguiluz** [comment]
Matthieu, the problem is that we can't link to specific methods in GitHub. So, we use "text fragments" (https://developer.mozilla.org/en-US/docs/Web/Text_fragments) as a trick to achieve the same result.

Sadly, Firefox is the only browser that doesn't support text fragments yet. Given that this is a nice-to-have feature instead of a critical feature, we think it's a reasonable compromise to keep using this even one browser won't support it. Hopefully firefox will add support for it soon.

Cheers!
