### ISSUE TITLE
Unnecessary Function Call

### ISSUE THREAD

**Issue by justin-oh** [symfony/symfony-docs#19838]
In the documentation for [Compiler Passes in Bundles](https://symfony.com/doc/current/service_container/compiler_passes.html#working-with-compiler-passes-in-bundles), the example shows:

```php
// src/MyBundle/MyBundle.php
namespace App\MyBundle;

use App\DependencyInjection\Compiler\CustomPass;
use Symfony\Component\DependencyInjection\ContainerBuilder;
use Symfony\Component\HttpKernel\Bundle\Bundle;

class MyBundle extends Bundle
{
    public function build(ContainerBuilder $container): void
    {
        parent::build($container);

        $container->addCompilerPass(new CustomPass());
    }
}
```

However, the call to the parent function is unnecessary because the [Bundle class](https://github.com/symfony/symfony/blob/7.1/src/Symfony/Component/HttpKernel/Bundle/Bundle.php)'s implementation of the function is empty:

```php
/**
 * This method can be overridden to register compilation passes,
 * other extensions, ...
 *
 * @return void
 */
public function build(ContainerBuilder $container)
{
}
```

Also, shouldn't anything related to bundles in documentation of 6.1 and beyond be extending [AbstractBundle](https://github.com/symfony/symfony/blob/7.1/src/Symfony/Component/HttpKernel/Bundle/AbstractBundle.php)?

**Comment by javiereguiluz** [comment]
About your first question, we always call the parent method because even if today might be empty, those parent methods could change in the future, so the code must be ready for that.

About the second question: yes, we should use `AbstractBundle` everywhere. We did some recent changes related to this (see #19793) but we need to update more examples. Thanks!
