### ISSUE TITLE
[Validator] Add `errorPath` to Unique constraint

### ISSUE THREAD

**Issue by fabpot** [symfony/symfony-docs#19976]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#57436
| PR author(s) | @norkunas
| Merged in    | 7.2

We created this issue to not forget to document this new feature. We would really appreciate if you can help us with this task. If you are not sure how to do it, please ask us and we will help you.

To fix this issue, please create a PR against the 7.2 branch in the [symfony-docs repository](https://github.com/symfony/symfony-docs).

Thank you! :smiley:

**Comment by norkunas** [comment]
I thought I'll submit PR but before I want to discuss about the little difference between `UniqueEntity` and `Unique` constraints that `UniqueEntity` uses first defined field if error path is not provided. Should `Unique` also fallback to first field, if at least one field is defined?

**Comment by javiereguiluz** [comment]
Closing it as fixed in #20163.

@norkunas I understand this as _"the error message is bound to the first collection item"_ (in `Unique`) and this option allows to bind it to some specific field within that first collection item. If I understood this wrongly, please tell me and we can fix it in another PR.
