### ISSUE TITLE
Unify how --format is handled by commands

### ISSUE THREAD

**Issue by fabpot** [symfony/symfony-docs#19991]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#57518
| PR author(s) | @fabpot
| Merged in    | 7.2

We created this issue to not forget to document this new feature. We would really appreciate if you can help us with this task. If you are not sure how to do it, please ask us and we will help you.

To fix this issue, please create a PR against the 7.2 branch in the [symfony-docs repository](https://github.com/symfony/symfony-docs).

Thank you! :smiley:

**Comment by javiereguiluz** [comment]
From the related code PR, this is the only change relevant for docs:

* Deprecate the `text` format (used only twice) in favor of the more common `txt` one

In the docs we only mention the text format once and we use `txt` instead of `text` (see https://symfony.com/doc/current/frontend/asset_mapper.html#run-security-audits-on-your-dependencies) so there's nothing to update in the docs. Thanks!
