### ISSUE TITLE
Yaml number-formatting issue

### ISSUE THREAD

**Issue by homersimpsons** [symfony/symfony-docs#20078]
Reading the yaml documentation in https://symfony.com/doc/current/components/yaml.html#numeric-literals we can see the following code block:
![image](https://github.com/user-attachments/assets/da73b361-3281-4caf-b1af-c916ac01bd9b)

Here, the numbers are all formatted as strings, except for the `3.` for the `parameters.pi` property.

The correct rendering should be:
![image](https://github.com/user-attachments/assets/3ed5af59-0078-4d25-b745-a41df59ae811)

This may be a highlightjs issue (it looks like this project is using this library).

Libraries:
- I read an [article](https://stitcher.io/blog/a-syntax-highlighter-that-doesnt-suck) about https://github.com/tempestphp/highlight, but I doubt the idea would be to change the library.
- I came across https://shiki.style/ while doing some research, it correctly highlight `parameters.pi`, but highlight the other properties as "string"

**Comment by javiereguiluz** [comment]
@homersimpsons good catch!

We use a custom-made parser which makes use of some PHP highlighter to produce the final results. So, this kind of bugs need to be fixed in that other project.

I've created an issue using your information: https://github.com/symfony-tools/docs-builder/issues/177

So, let's close this one in favor of the other repository issue. Thanks!
