### ISSUE TITLE
[Translation] [Loco] Ability to configure value of `status` query-varia…

### ISSUE THREAD

**Issue by fabpot** [symfony/symfony-docs#20184]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#58072
| PR author(s) | @mathielen
| Merged in    | 7.2

We created this issue to not forget to document this new feature. We would really appreciate if you can help us with this task. If you are not sure how to do it, please ask us and we will help you.

To fix this issue, please create a PR against the 7.2 branch in the [symfony-docs repository](https://github.com/symfony/symfony-docs).

Thank you! :smiley:

**Comment by javiereguiluz** [comment]
Note: the docs of these providers are not added directly to the Symfony Docs repository.

The doc about this new feature must be added to the `README` file of this translation provider: https://github.com/symfony/loco-translation-provider/blob/7.2/README.md (the Pull Request must be submitted against https://github.com/symfony/symfony repository instead of https://github.com/symfony/loco-translation-provider).

See https://github.com/symfony/phrase-translation-provider for an example of a similar provider with its docs in the README.

**Comment by javiereguiluz** [comment]
Closing as fixed in https://github.com/symfony/symfony/pull/58193
