### ISSUE TITLE
Tilde is not rendered in doc

### ISSUE THREAD

**Issue by MrYamous** [symfony/symfony-docs#20215]
I noticed in the [String documentation](https://symfony.com/doc/current/string.html#working-with-emojis) a tilde that doesn't appear (the space before 5,000)
<img width="766" alt="Capture d’écran 2024-09-11 à 08 02 18" src="https://github.com/user-attachments/assets/58d6945d-a831-4fed-a806-6143e8844f04">

Do you think it can be a browser issue ? Tried with Chrome and Safari

I remembered this old PR #17624 for a similar issue. If it's about documentation rendering, for this case I think render it as code ``~`` is not fully appropriate

**Comment by javiereguiluz** [comment]
Thanks for reporting this. It looks like a bug, so I created a failing test in the Docs Builder tool that we use in Symfony Docs (see https://github.com/symfony-tools/docs-builder/pull/181).

Hopefully someone can investigate how to fix it. Thanks!

**Comment by OskarStark** [comment]
We could change it this way:
```diff
- of all emojis (~ 5000) ....
+ of all emojis (approx. 5000) ....
```

and see, if we can fix the parser somehow

**Comment by OskarStark** [comment]
Code-PR merged:

* https://github.com/symfony-tools/docs-builder/pull/181

**Comment by javiereguiluz** [comment]
I'm closing this without merging because the error was solved thanks to the bug fix provided by @wouter in https://github.com/symfony-tools/docs-builder/pull/181

See the tilde character correctly rendered in production: https://symfony.com/doc/current/string.html#working-with-emojis

note: other Symfony Docs versions will be updated when the docs are fully rebuilt tonight.
