### ISSUE TITLE
[Notifier] [GatewayAPI] Add support for label parameter

### ISSUE THREAD

**Issue by nicolas-grekas** [symfony/symfony-docs#20290]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#58427
| PR author(s) | @Nico Hiort af Ornäs
| Merged in    | 7.2

We created this issue to not forget to document this new feature. We would really appreciate if you can help us with this task. If you are not sure how to do it, please ask us and we will help you.

To fix this issue, please create a PR against the 7.2 branch in the [symfony-docs repository](https://github.com/symfony/symfony-docs).

Thank you! :smiley:

**Comment by javiereguiluz** [comment]
Note: the docs of these providers are not added directly to the Symfony Docs repository.

The doc about this new feature must be added to the `README` file of this notifier provider: https://github.com/symfony/gateway-api-notifier/blob/7.2/README.md (the Pull Request must be submitted against https://github.com/symfony/symfony repository instead of https://github.com/symfony/gateway-api-notifier).

**Comment by MrYamous** [comment]
The readme for this notifier has been updated with code PR, i think we can close this issue
