### ISSUE TITLE
[Translation] Allow sort when extracting translation files

### ISSUE THREAD

**Issue by nicolas-grekas** [symfony/symfony-docs#20291]
| Q            | A
| ------------ | ---
| Feature PR   | symfony/symfony#58408
| PR author(s) | @danut007ro
| Merged in    | 7.2

We created this issue to not forget to document this new feature. We would really appreciate if you can help us with this task. If you are not sure how to do it, please ask us and we will help you.

To fix this issue, please create a PR against the 7.2 branch in the [symfony-docs repository](https://github.com/symfony/symfony-docs).

Thank you! :smiley:

**Comment by javiereguiluz** [comment]
Closing without making any change because the `--sort` option is not explained explicitly. It's mentioned along with other extra options of the `translation:extract` command in https://github.com/symfony/symfony-docs/blob/7.1/translation.rst#extracting-translation-contents-and-updating-catalogs-automatically

Thanks!
