### ISSUE TITLE
Add cookbook article about overriding predefined data for child form

### ISSUE THREAD

**Issue by Koc** [symfony/symfony-docs#3374]
https://github.com/symfony/symfony/issues/9746

**Comment by vudaltsov** [comment]
I don't think this could have been achieved much easier:

```php
$company = $this->getDoctrine()
    ->getManager()
    ->getRepository(Company::class)
    ->createQueryBuilder('company')
    ->addSelect('companyCategories')
    ->join('company.companyCategories', 'companyCategories')
    ->getQuery()
    ->getSingleResult();

$form = $this->createForm(CompanyType::class, $company);
```

Such code will produce only one DB query with a join instead of two queries. I think we could add a line on this in the `EntityType` article maybe... But on the other hand it's pretty obvious how to preload children in doctrine. And it's a general question, not about forms.
