### ISSUE TITLE
[RFC] Added a cookbook: assets on S3

### ISSUE THREAD

**Issue by lyrixx** [symfony/symfony-docs#3723]
see https://github.com/symfony/symfony/pull/10301#issuecomment-35680857
and the next comment.

(This is a reminder for me;))

**Comment by WouterJ** [comment]
Ping @lyrixx. It would be great if you could add some steps to this PR so someone can document them.

**Comment by bassrock** [comment]
:+1:

**Comment by javiereguiluz** [comment]
I'm closing this because it hasn't received a single comment in 2 years and we've been looking for a volunteer to write this for 3 years.

By the way, we should always think twice before adding articles about third-party services ... because they are hard to maintain (we need experts on those external services ... and we don't have them). Thanks!
