### ISSUE TITLE
All sidebars should have a way to link them directly

### ISSUE THREAD

**Issue by stof** [symfony/symfony-docs#3814]
Currently, a title inside a sidebar gets rendered as a ``<p class="sidebar-title">``. Given it is not rendered as a heading, it does not have a direct link to it. This makes it really hard to link to the doc properly.

If you look at https://github.com/symfony/symfony/issues/10760 for instance, I had to link to the previous heading rather than to the sidebar itself, which makes the link less useful.

**Comment by WouterJ** [comment]
should we abandon this idea then?

**Comment by javiereguiluz** [comment]
@WouterJ I think we should abandon the original idea. The good news is that we can already link directly to any sidebar, as demonstrated with this link: http://symfony.com/doc/current/book/installation.html#book-installation-permissions

If you agree, please close this issue. Thanks!

**Comment by stof** [comment]
@javiereguiluz it would be good to have a visible link to the sidebars, to make it easy to copy-paste it when linking to the doc. Isn't there a way to achieve it ?

**Comment by WouterJ** [comment]
@javiereguiluz I have bad news for you: That sidebar has an anchor, as we gave it to him by defining an anchor in the reSt files. Sidebars by default don't get an anchor. Moreover, nobody will see it has an anchor since it doesn't have a nice anchor sign in the headline.

Why should we abandon this idea? Is the build code so secret that you can't provide some very small details?

**Comment by javiereguiluz** [comment]
@stof having a visual "anchor link" for sidebar titles is a very reasonable request ... so I've just added it to the documentation (it will be online after the next deploy):

![sidebar-anchor-link](https://cloud.githubusercontent.com/assets/73419/5778265/4aea4076-9d9a-11e4-8c58-ec85fbdb238c.gif)

@WouterJ I was referring that the bad news are that we don't have automatic links for sidebar titles ... but the good news is that is doesn't matter because we can add them manually when needed.

The build process is not secret ... it's just complex, because it's based on the "peculiar" Sphinx project. In any case, we now have visual anchors for sidebar titles, so this issue can be considered fixed :)

**Comment by javiereguiluz** [comment]
@stof @WouterJ thinking a bit more about this, and given than the solution involves executing more JavaScript code in the doc section, I'd like to ask two questions:

  * Do we have more examples of sidebars that are usually linked to for reference purposes?
  * If not, don't you think that we should instead move this specific sidebar about permissions to a real book section or cookbook?

**Comment by fabpot** [comment]
I propose to close this one as there are no feedback. A comment I made back then on the symfony.com repo PR:

"Do we have enough examples? It sounds weird to me to have to titles inside sidebars. The example you reference is probably a good sign that the value is so important that it deserves more than a sidebar, like a cookbook entry or a dedicated chapter."

**Comment by WouterJ** [comment]
Please note that there is a biv difference between a sidebar and a admonition. Sidebars always have titles (it's a required option of the sidebar directive), while admonitions have no built in support for titles.

**Comment by javiereguiluz** [comment]
Let's close this issue. We won't add this feature and besides, a sidebar which is important enough to be linked to, it should probably be a regular chapter section or a cookbook and not a sidebar. Thanks.

**Comment by stof** [comment]
Well, I have such an example: the documentation of the different ways to setup file permissions on the cache folder is currently in a sidebar. Fortunately, there is a title not far above, but I'm still meaning to link to the sidebar itself.

**Comment by javiereguiluz** [comment]
@stof you are right ... but at the same time, that sidebar is the perfect example of a very important information "wrongly" displayed as a sidebar. It's so important that it should be a cookbook article or a highlighted chapter section.

**Comment by javiereguiluz** [comment]
Let's close this as "won't fix".

Setting up Sphinx to build a complex doc like Symfony is hard enough to not complicate even more with custom extensions to support features like that.

Luckily the solution is simple: let's put important contents on their own articles instead of in sidebars (we've already made some changes like that after the recent [documentation reorganization](http://symfony.com/blog/introducing-the-new-symfony-documentation) and for example, the famous "Permission Problems" sidebar no longer exists).
