### ISSUE TITLE
Using the new template naming in the documentation

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony-docs#3849]
The other day, @lyrixx and I were talking about Twig template naming and locations and he asked if we could update the official Symfony documentation to use the new template syntax.

Imagine that your project has the following four templates:

```
your-project/
 ├─ app/
 │  └─ Resources
 │     └─ views/
 │        └─ template1.twig
 ├─ src/
 │  └─ Acme/
 │     └─ Bundle/
 │        └─ DemoBundle/
 │           └─ Resources
 │              └─ views/
 │                 ├─ template2.twig
 │                 └─ Default/
 │                    ├─ template3.twig
 │                    └─ common/
 │                       └─ template4.twig
 ├─ vendor/
 └─ web/
```

Using the **traditional syntax**, you have four different formats to explain:

```
::template1.twig
AcmeDemoBundle::template2.twig
AcmeDemoBundle:Default:template3.twig
AcmeDemoBundle:Default:common/template4.twig
```

Using the **new namespaced syntax** everything is straightforward:

```
template1.twig
@AcmeDemoBundle/template2.twig
@AcmeDemoBundle/Default/template3.twig
@AcmeDemoBundle/Default/common/template4.twig
```

With the new syntax you only have to write the path from `Resources/views/`, without thinking if the template is associated with a controller or if it's stored in a subdirectory. Everything is much easier to explain, specially for Symfony newcomers.

Forgetting for a moment about the colossal effort that would be needed to update all the documentation, what do you think about this proposal?

**Comment by weaverryan** [comment]
@javiereguiluz I know this issue and (symfony/symfony#11051) got a little crazy, but I think we're close now - and I agree with what you said above.

But, the core code is still stripping off the `Bundle` suffix in the Twig namespaces (remember this code? https://github.com/symfony/symfony/blob/master/src/Symfony/Bundle/TwigBundle/DependencyInjection/TwigExtension.php#L130-132). If I'm correct, then we need to:

A) Deprecate the `@AcmeDemo/Default/index.html.twig` namespace
B) Add the `@AcmeDemoBundle/Default/index.html.twig` namespace
C) Start using the syntax in (B) instead of the 3-part syntax (?does it have any downsides - can you use bundle-overriding with it? I can't remember).

Also - I want to keep things focused - but this plan could possibly be changed if we imagine using puli in Symfony 3.0. In that case, we'd need to brain-storm how that would look and move in that direction instead of moving towards (B) and (C) above (cc @webmozart).

Make sense?

**Comment by webmozart** [comment]
@weaverryan I would like to work on Puli integration directly into Symfony once 2.7 is released, as the feature freeze is too soon now. Also this means that a stable version of Puli will be available.

For reference, with Puli the paths will be normalized to:

```
/acme/blog-bundle/views/Default/common/template4.html.twig
```

If a resource is loaded through Puli (e.g. a Twig template or a config file), references to other resources can use relative paths: 

```
../views/Default/common/template4.html.twig
```

**Comment by javiereguiluz** [comment]
@webmozart what would be the Puli path for a template stored in the global `app/Resources/views/` directory? (e.g. `app/Resources/views/common/template4.html.twig`)

And I have another question: since you already have tested some proof-of-concept integrations of Puli + Symfony: what's the impact of Puli on performance? (I'm not implying that Puli degrades performance ... I'm just curious to know if Puli improves or degrades or maintains Symfony performance). Thanks.

**Comment by webmozart** [comment]
@javiereguiluz The application path for your example would be:

```
/app/views/common/template4.html.twig
```

For DX reasons, I even think we should get rid of the `Resources` directory in applications. Then the Puli path is the same as the relative path to the project root.

At the moment, Puli degrades performance directly after clearing the cache. This needs to be optimized. Once the cache is loaded, performance is the same as now, since Puli is not accessed anymore then.

**Comment by javiereguiluz** [comment]
Closing this issue because there is no consensus to make this change.

In any case, docs already use the syntax recommended by the Symfony Best Practices for global templates and the traditional syntax (`Bundle:controller:template`) for the few bundle templates.
