### ISSUE TITLE
Document new Validation API options?

### ISSUE THREAD

**Issue by weaverryan** [symfony/symfony-docs#4094]
Hi guys!

Related to https://github.com/symfony/symfony/blob/master/UPGRADE-2.5.md#validator and https://github.com/symfony/symfony/blob/master/UPGRADE-3.0.md#validator - specifically, I'm talking about the new Validator API and options. 

Needed changes:
- [x] A) Update the `ExecutionContextInterface` namespaces (see #4161 and #4233)
- [x] B) Update the `addViolationAt` to `buildViolation`
- [ ] C) Add a cookbook entry to explain all of this stuff, and show how a bundle can support both versions
- [x] D) Update the framework reference section with the `framework.validation.api` option.
- [x] E) Replace usages of deprecated method `validateValue()` where needed.
- [x] F) Change signature of using `->validate` with a group argument:

**Comment by WouterJ** [comment]
@xabbuh we do use `validateValue` in the validation book chapter ("Validating Values and Arrays").

**Comment by xabbuh** [comment]
@WouterJ But only in the example showing the deprecated API (which is only explained in a comment), right?

**Comment by craigh** [comment]
I see this issue is a bit old, but I am confused by the current Interface usage in v2.8 (which I assume is the same as 3.0 - but I have 2.8 installed). I am constructing a custom validation constraint as explained [here](http://symfony.com/doc/current/cookbook/validation/custom_constraint.html). PhpStorm warns that the `$context` property of the `\Symfony\Component\Validator\ConstraintValidator` class doesn't contain the `buildViolation` method:
![screen shot 2016-03-30 at 5 54 40 pm](https://cloud.githubusercontent.com/assets/350048/14158883/ad15f488-f6a0-11e5-9a1d-039c6e122cfc.png)

some brief looking around didn't help. I'm wondering if this is (1) my mistake (2) a bug (3) wrong docs (4) all of the above...?

The [docs](https://github.com/symfony/symfony/blob/master/UPGRADE-3.0.md#validator) say that the `$context` property should be `Symfony\Component\Validator\Context\ExecutionContextInterface` but you can see it not.

**Comment by xabbuh** [comment]
This basically is a thing with the old API in Symfony 2.8 due to which the `$context` property is marked as `Symfony\Component\Validator\ExecutionContextInterface` (it is `Symfony\Component\Validator\Context\ExecutionContextInterface` in 3.0 which provides the method). However, when using the 2.5 API, you can be sure that `$context` always is an implementation of the new interface (which by the way extends the legacy interface). Once you switch to Symfony 3.0 auto-completion in PhpStorm should work again.

**Comment by javiereguiluz** [comment]
I'm closing this as fixed because all important stuff was completed. The only missing thing (explain how a bundle could support both validation API version) is irrelevant now in 2018 year. Thanks!
