### ISSUE TITLE
Add parameters details for Heroku

### ISSUE THREAD

**Issue by weaverryan** [symfony/symfony-docs#4217]
Hey guys!

A friend of mine was using Heroku with Symfony and got it all working nicely, *except* for handling parameters.yml. I realized that how parameters should be handled is not covered in our document. I *believe* that [environment variables](http://symfony.com/doc/current/cookbook/configuration/external_parameters.html) should be used.

**Comment by javiereguiluz** [comment]
Let's recap the things to do in this PR:

  1. [x] Use SYMFONY_ENV parameters (done in #4545 and #4591)
  2. [x] Explain the `env-map` feature (won't fix because it's documented in the ParameterHandler)
  3. [ ] How to do things like compiling Assetic assets during deploy (`compile` option of the `heroku` option in the `extra` section of `composer.json`)
  4. [ ] Solve the problems caused by required dev dependencies (such as `SensioGeneratorBundle`)
  5. [x] Explain parameters.yml parameters.yml.dist` (done in #4174)

In my opinion, we just have to tackle 3 and 4 in `/cookbook/deployment/heroku`. @bicpi are you still interested (and motivated) to work on this? Thanks.

**Comment by dzuelke** [comment]
> How to do things like compiling Assetic assets during deploy (`compile` option of the `heroku` option in the `extra` section of `composer.json`)

That's specific to @CHH's now unmaintained buildpack. For the official Heroku buildpack, just use a `compile` script in `composer.json`, see https://devcenter.heroku.com/articles/php-support#custom-compile-step

**Comment by dzuelke** [comment]
> Solve the problems caused by required dev dependencies (such as `SensioGeneratorBundle`)

That should never be a problem because your code shouldn't use it with the right environment set. You just need to make sure you `heroku config:set SYMFONY_ENV=prod`. That's also @fabpot's officially sanctioned way of doing it.

**Comment by bicpi** [comment]
@javiereguiluz Yes, still interested and motivated. Heroku's PHP support has improved a lot in the last few months so I'm going to check the open items.

**Comment by bicpi** [comment]
> Solve the problems caused by required dev dependencies (such as SensioGeneratorBundle)

@javiereguiluz Mh, this is not an issue any more if you follow the best practice to use Heroku with a non-dev environment, e.g. if you set the prod environment as default. As Heroku uses `composer install --no-dev` it is not possible to run a dev environment without changes to the `composer.json` if the dev environment makes use of dev dependencies. Is there a use case to run a dev environment on Heroku, does it makes sense?

**Comment by dzuelke** [comment]
The only open item for asset compiles is described here: https://devcenter.heroku.com/articles/php-support#build-behavior

**Comment by bicpi** [comment]
@dzuelke Thanks, already discovered it. I'll add a note about this and a short one about `--no-dev` implications and then this ticket can be closed. Hope that sounds good.

**Comment by weaverryan** [comment]
Closing this - all the todos are "completed" - either have PR's or have open issues.

Thanks!
