### ISSUE TITLE
[DX] User TimeZone management

### ISSUE THREAD

**Issue by isleshocky77** [symfony/symfony-docs#4333]
It would be great to have a best practices of how to handle having users which reside in multiple timezones along with an application which has logic and content which is time-sensitive.

Included should be best practices of storing a DateTime in a database, Querying a DateTime from database per user's TimeZone and displaying DateTime to the user.

Obvious links would be to use the Date form field properly with a user's timezone as well as properly using twig to display DateTime in the user's timezone.

**Comment by adamelso** [comment]
:+1: I've always been nervous about implementing timestampable behaviour in Symfony as there many factors involved: server configuration, PHP configuration, user locale, Doctrine hydration, Symfony Forms, using Doctrine Extensions library, to UTC or not to UTC? etc.

I feel this maybe one of those things that come back to bite if implemented incorrectly, and the Symfony docs would be the ideal place to educate.

**Comment by Zuhayer** [comment]
Has 'how to handle having users which reside in multiple timezones' been updated in the cookbook? 

I am unable to find it.

**Comment by javiereguiluz** [comment]
I'm afraid I must close this as "won't fix" because we don't have enough resources to create a special article dedicated to his. However, "timezones" are mentioned and explained in every article related to timezones in some way or another. See https://www.google.com/search?q=symfony+docs+timezone Thanks for understanding!
