### ISSUE TITLE
[BC promise] Exception types

### ISSUE THREAD

**Issue by wouterj** [symfony/symfony-docs#4413]
The BC promise is currently missing exceptions. We should set up rules for the exceptions.

I would say:
- Never change exceptions thrown by `@api` methods
- Methods without `@api` may change the type of the exception, but the base exception class should be te same. E.g. `FooException` and `BarException` both implements `MainException`, then `FooException` may be changed to `BarException`

/cc @symfony/deciders @symfony/mergers

**Comment by WouterJ** [comment]
ping @webmozart, @stof, @fabpot I would like to hear your thoughts on this one, so it can be documented.

**Comment by umulmrum** [comment]
An older issue, but I think it's still worth considering.

I'd suggest something like this:

- A method may only throw exceptions that are declared via `@throws` in the method's docblock.
- Adding and removing exception declarations is a BC break; replacing a declaration is not a BC break if the new exception is a subclass of the old exception.
- If a method has a parent method or implements an interface method, it inherits the exception declarations; additional exception types may only be thrown if they are subclasses of exceptions that are already declared for the parent method.

In @wouterj's example this would implicitly mean that `FooException` may be changed to `BarException` if the method declares `MainException`, but not if the method declares `FooException`.

There are cases where exceptions indicate severe programming errors, e.g. if a method couldn't be found because of a missing PHP extension. This could be solved e.g. by one of the following:
- Declare those exceptions anyway.
- Demand wrapping these exceptions in another exception that is already declared.
- Throw an `Error` instead of an `Exception` to make clear that this error condition is special.
- Ignore some exceptions and rely on more global exception handling.

WDYT?

**Comment by javiereguiluz** [comment]
@nicolas-grekas do you want to add Exceptions to the BC promise? This proposal has received just 2 comments in almost 5 years, so maybe there's no interest in it. Thanks.

**Comment by nicolas-grekas** [comment]
I agree, no need to keep that open for so long. I anyone wants to submit a PR, we'll consider.

**Comment by stof** [comment]
I think we need to distinguish 2 different things here:

- exception which indicate a broken usage of the API, for which the fix is to change the calling code to use it in a different way. Such exceptions have no reason to ever be catched locally when calling the API. They are best left for the global exception handler. These exceptions don't need to be declared in the phpdoc IMO, and could be changed class if needed (changing to a child class may still be a good idea whenever possible though)
- exception which indicate a failure of the API, for which handling it locally makes sense (for instance, trying to copy a non-existent folder could throw about the invalid path). For such cases, it makes sense to document them in phpdoc *with an explanation of when they are thrown* and to preserve BC on them (i.e. only ever change them to a child class)
