### ISSUE TITLE
Add whitespace between image and text

### ISSUE THREAD

**Issue by ifdattic** [symfony/symfony-docs#4717]
I think it might be useful to add some whitespace between the image and the text on the page http://symfony.com/doc/current/book/installation.html

![screen shot 2014-12-30 at 7 24 22 pm](https://cloud.githubusercontent.com/assets/966877/5580875/d505a41a-9059-11e4-88d5-7c332786bad3.png)

**Comment by javiereguiluz** [comment]
@xabbuh @WouterJ I know that you like to close issues only when the issue has been fixed in the actual production website. But before reopening this issue, please consider that Fabien has closed it because a fix for the issue has been merged on symfony.com source code and the deploy of the new website is coming very soon.

**Comment by xabbuh** [comment]
Looks good. :+1: Thanks @javiereguiluz and @fabpot.
