### ISSUE TITLE
Documentation linking to 3rd-party articles

### ISSUE THREAD

**Issue by ifdattic** [symfony/symfony-docs#4871]
At SymfonyCon Madrid @weaverryan during one of discussions proposed the idea of having a section for linking to 3rd-party resources. While reading the http://symfony.com/doc/current/cookbook/configuration/pdo_session_storage.html I remembered that idea and (shameless plug) as having written a similar article http://ifdattic.com/how-to-mongodb-sessions-symfony-application I asked Ryan about his thoughts on this one.

We think it would be best to get a lot of feedback from the community to decide on this "external linking" test case.

A. If we want to allow external links
B. What the requirements would be
C. Where these should live

**Comment by javiereguiluz** [comment]
@ifdattic I appreciate that you suggested this idea to improve documentation, but I propose to close it as *won't fix*.

I agree that the official Symfony doc cannot cover everything. I also agree that there are some fantastic third-party resources and articles. However, linking to external websites is always a risk for the official documentation of a big project. What if the linked article goes down or changes its URL? Someone should check the third-party URLs regularly. What if the third-party site includes inappropriate ads? Someone should again check that regularly. What if the external article is no longer relevant because its contents are deprecated? Again, someone should check that continuously.

In any case, I agree that the Symfony ecosystem is very important and we should give more credit to them. That's why I proposed to mention and link to more popular third-party bundles in the Symfony documentation. See https://github.com/symfony/symfony-docs/pull/5373

Let's see if @WouterJ and @xabbuh agrees with my comments.

**Comment by ifdattic** [comment]
@javiereguiluz It's fine. I agree that this might add a lot of maintenance and in time become more of a bother than good.

**Comment by harikt** [comment]
I am +1 for @javiereguiluz comment. His words are absolutely true. 

Also as symfony blog itself covers `they talked about us` may be a place for it.
