### ISSUE TITLE
[RFC] Revisit the Translation/i18n best practices

### ISSUE THREAD

**Issue by wouterj** [symfony/symfony-docs#5026]
Url: http://symfony.com/doc/current/best_practices/i18n.html
## The Original Best Pratices
- Use the XLIFF format for your translation files.
- Always use keys for translations instead of content strings.

_Best practice 2 ("Store the translation files in the app/Resources/translations/ directory.") is not included in this RFC._
## The Proposed Best Practices
1. Use the Yaml format for your translation files.
2. Always use keys for translations instead of content strings
## Reasoning
- The Translation component hardly supports the Xliff specification. Actually, it reads just `<source>`, <target>`and`<note>` elements and everything else is ignored. The Xliff specification contains a lot more elements which are usefull for translations. As such, the Xliff format is not the way it's intended by the Xliff specifications. Some examples (I've left out all boilerplate code):
  
  _Please note that I don't consider myself a Xliff expert, far from that. The examples might be invalid, but they create a picture to illustrate the difference between Xliff's intended approach and Symfony's Xliff implementation_
  
  **The Symfony Way**
  
  ``` xliff
  <source>Hello %name%!</source>
  <target>Hello %name%!</target>
  ```
  
  **The Xliff Way**
  
  ``` xliff
  <source>Hello <g id="1">name</g>!</source>
  ```
  
  **The Symfony Way**
  
  ``` xliff
  <trans-unit id="apples">
     <source>I have %number% apples</source>
     <target>{0}I have 0 apples|{1}I have 1 apple|[2,Inf]I have %number% apples</target>
  </trans-unit>
  ```
  
  **The Xliff Way**
  
  ``` xliff
  <group restype="x-gettext-plurals" id="apples">
     <trans-unit id="apples[0]">
         <source>I have no apples</source>
     </trans-unit>
  
     <trans-unit id="apples[1]">
         <source>I have one apple</source>
     </trans-unit>
  
     <trans-unit id="apples[n]">
         <source>I have <g id="1">count</g> apples</source>
     </trans-unit>
  </group>
  ```
  
  Besides these, there are many other examples. For instance, doing something with the attributes of the `<file>` and `<body>` elements.
- The Translator does not support anything more than a key-value pair. It seems completely against all DX conventions to have so much boilerplate code for just a simple key-value representation
- Using keys as the source is against the Xliff specification goals. If the best practice still want to recommend Xliff, it the other best practice should be changed to "Use the messages itself as the source/key"
- XML is a difficult format. This makes it hard for beginners to understand. Besides that, DTD errors are hard to read if you aren't used to them. As demostrated in https://github.com/symfony/symfony/issues/11256, using simple HTML entities like`&hellip;` will cause errors. And those errors cause headaches to understand what's wrong and how to fix it.

**Comment by javiereguiluz** [comment]
@WouterJ you have a very nice list of points to favor Yaml over Xliff. I agree with all of them :)

But I also like to hear the opinions of the people who frequently use the services of professional translation companies. Do they ask you to work in any particular format? Is Xliff really the only widespread format? Would those companies be willing to accept/deliver YAML files for their translations or is that totally out of question?

**Comment by stof** [comment]
@WouterJ there is a markup issue in your list of supported elements.

And I fully agree about your points (I always use Yaml in my projects)

**Comment by maschmann** [comment]
Referring to past larger multilanguage/multi-client projects with lots of translations:

* using YAML or PHP translation files works for internal purposes and a limited amount of actual translations
* when handing files out to (professional) translation services best worked with xliff files
* internally we've moved all translations to the database, for which I wrote a bundle, capable of exporting and importing the database contents in different formats
* XLIFF is unwieldy and the format is nearly impossible to handle in a clean way, using normal editors (no industry standard tools)
* Having inline HTML in XLIFF can be compensated with CDATA tags, since it's XML ;-) But... having HTML in translation files is really _not_ a good idea, generally speaking.

Working with external translation service providers gave us headaches. Providing them YAML or PHP files regularly broke our translations. Also there needs to be a process to diff the translation files and merge them to a version you can use in your app. And there's always people working on the translation files while the rest is being translated. So there's a great threat of inconsistencies, double keys and so forth.

My best practices would be:

* pack all translations into a data store like a database
* add import/export capabilities to translation component, so XLIFF can be automatically generated and importet - to support external translation providers
* add CDATA wrapping for html content

**Comment by WouterJ** [comment]
Thank you for your detailed comment, @maschmann. (and sorry for the absence of a response...)

Keep in mind that the best practices are designed for beginners, to remove some design decisions one has to make (they have worries enough grasping Symfony usage). So I think a database is a bit overdone to put into the best practices.

So from your comments, you actually recommend us to keep recommending Xliff? And do you like the combination of dot seperated keys instead of the translated sentence in Xliff?

I would also like to know the opinion of more people /cc @fabpot @weavaerryan @webmozart @xabbuh

**Comment by xabbuh** [comment]
If Xliff is the format you have to use when working with translation services, I think we should keep recommending to use this format.

**Comment by maschmann** [comment]
Maybe use a recommendation like: If you exepect to work with external translation services, use xliff, otherwise yaml.
The current implementation of app/console translation:update, there's an option for output format. So it's always possible to create xliff files afterwards.
Concerning the dot notation vs. translated string as translation key:
Personally I'd prefer dot notation (or a abstract key handling) instead of translation as keys because it's less prone to have errors with included html, backslashes or other ugly stuff and somehow (in my expirience) easier to understand for new Symfony users.
Although this implies a user always has to make sure all translations are in translation files or the output in the fronted will be somewhat cryptic for possible users (had this happen several times).

**Comment by WouterJ** [comment]
To wrap this issue up:

* [ ] Rewrite the [format section](http://symfony.com/doc/current/best_practices/i18n.html#translation-source-file-format) and change the best practice about the format to: *"Use the Yaml format for your translation files, except when you're working with external translation services that require XLIFF."*
* [ ] Update the [example in the best practices guide](http://symfony.com/doc/current/best_practices/i18n.html#example-translation-file)
* [ ] Update all translation examples in the documentation to have the following order: Yaml, XLIFF, PHP
* [ ] Update [the doc standards](http://symfony.com/doc/current/contributing/documentation/standards.html#formats) with the new format order for translations

/cc @fabpot I know you had some reasons to recommend Xliff in the best practices instead of Yaml. I would love if you could share your opinion about the proposed changes.

**Comment by JulienItard** [comment]
:+1:

**Comment by weaverryan** [comment]
Hi guys!

The XLIFF practice was recommended originally for a few reasons:

A) the "industry standard" thing. Though, I think this is less important, because as a few people have mentioned, you can dump translations (`translation:update`) into XLIFF, and we could also say "use XLIFF if you know you'll use an external service that prefers this"

B) XLIFF has the ability to store some extra metadata with the keys, though this is a feature that I've only seen in JMSTranslationBundle. That bundle, stores:
* whether the translation is new or has been translated
* where the key comes from (e.g. the template, line)
* a human-readable description that you can add

But again, unless you're using JMSTranslationBundle, you're not taking advantage of this. And in theory, the keys/translations could be kept in a YML file and extra metadata stored elsewhere, since that's kind of a implementation-specific detail.

So, I would be fine with YAML, but I also want to hear from @aitboudad in case he has some extra expertise. I also want to establish a recommended "flow", for example:

A) Add translations into templates, etc
B) use `translation:update` to populate the files? Or do it by hand? I've used JMSTranlsationBundle's dump before, and it's great - but I don't know if our core dumper is as good yet.
C) Translate by hand? Using a GUI/tool that keeps track of which need to be updated?

Are there some practices from other frameworks/libraries that we can build from?

**Comment by JulienItard** [comment]
What's about LexikTranslationBundle ? I like its workflow

**Comment by javiereguiluz** [comment]
I agree that XLIFF is far from ideal ... but we recently asked the community about this (see https://github.com/symfony/symfony/issues/22566) and it was clear that we cannot stop using or recommending XLIFF. So, I'm closing this proposal as "won't fix". I'm sorry.
