### ISSUE TITLE
Future of the translated documentations

### ISSUE THREAD

**Issue by gregquat** [symfony/symfony-docs#5068]
Hi everybody,

It's me again. I would like to reopen the discussion about the translated documentations. I have sent an email to @fabpot to know if the French documentation (in my case) has a future or not.
Endeed, as most of you know it, I can't update/translate the documentation as often as the English documentation is updated (thanks to your amazing work).

We have already discussed that in this thread : https://github.com/symfony/symfony-docs/issues/4078.
I would like to make the same proposal, we can only translate parts of the documentation (the Quicktour and maybe the Book) that are quite stable.
The Reference and the Cookbook are maving too often, and they are for advanced developers, so we can think they are comfortable with English documentation.

As Fabien says, if we only translate small and stable parts of documentation, we can open it to others languages. Actually, only French and Italian are available but I know there many projects in many languages.

I just have to know if I must invest some time on this project or if it's a lost cause.
What's your opinion?

Thanks

**Comment by javiereguiluz** [comment]
In my opinion we should remove all translations for all documentation. These are my main reasons:

  * The translation will always be "not good" because the original English docs change very fast. Translations are "always" outdated and contain mistakes. This generates frustration on Symfony users and hurts project reputation.
  * Any developer suitable to use Symfony has the basic level required to read English docs. Let's be honest about this: Symfony is not for everybody. This is not a *Hello World* nonsense or a quick-and-dirty PHP script. This requires some programming level and experience which is incompatible with not being able to read basic English.
  * Our dear translators could put their efforts in more rewarding tasks. They could help form time to time in the original documentation, which would benefit us all. They could write some original articles in their own language and post them in their own blogs. This would promote their work, would help local communities to grow and would help inexperienced developers to get introduced into Symfony.
 
PS: beware that the Quick Tour contents could change a lot in the short term.

**Comment by gregquat** [comment]
Thanks Javier.
@weaverryan, @WouterJ, @fabpot, @xabbuh, @garak any opinion?

**Comment by garak** [comment]
I think that the main issue is the ability of keeping translated docs up to date. If a translator is able to update only some sections (e.g. book and quick tour), then he/she should remove the other sections, and the translation links in the correspondent language should disappear.
I can speak for myself: Italian translation is completely up to date for 2.3 and just a few minor pages behind for current stable version (2.6).
