### ISSUE TITLE
Improved YAML configuration syntax

### ISSUE THREAD

**Issue by xabbuh** [symfony/symfony-docs#5107]
see symfony/symfony#13892

**Comment by javiereguiluz** [comment]
@xabbuh I don't find this issue "actionable". The feature introduced by Symfony is automatic and non-configurable. What should we change in the documentation?

**Comment by xabbuh** [comment]
We can now show service container configuration examples using the new syntax which hopefully make them easier to understand.

**Comment by dupuchba** [comment]
:+1:

**Comment by WouterJ** [comment]
@javiereguiluz that's why it's also not tagged as actionable yet :)

**Comment by xabbuh** [comment]
@WouterJ Thanks :D

**Comment by javiereguiluz** [comment]
My vote is 👎 for these reasons:

* This change would introduce lots of verbosity to YAML syntax. Verbosity can be helpful when reading the config (e.g. when dumping your entire app config) but it's not that great when you need to write that verbose config.
* If we show the verbose YAML syntax, lots of readers may think that it is the only YAML syntax and they will use it in their apps instead of the "normal" YAML syntax.
* YAML syntax's conciseness is its second best feature (after readability). This change will seriously affect that.
* It would take us a lot of time to change everything without introducing errors and propagating the changes to all the supported branches.

**Comment by javiereguiluz** [comment]
I still maintain my 👎 vote on this. Any other opinions/votes on this? Thanks

**Comment by ogizanagi** [comment]
@javiereguiluz : I agree with your comment, however I think it's a good alternative to present somewhere in the doc (not by promoting it nor updating all examples, but simply by adding a tip in the container service definition documentation).

What about adding this tip right after the [Optional dependencies setter injection](http://symfony.com/doc/current/service_container.html#optional-dependencies-setter-injection) example ?

**Comment by javiereguiluz** [comment]
@ogizanagi I agree. A note/tip about this would be cool.
