### ISSUE TITLE
Preparing the Symfony 3 transition

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony-docs#5111]
Symfony 3 will be released at the end of this year. Fortunately, most of the Symfony 2 documentation will be still valid and we'll only have to remove some outdated sections.

However, we should probably create new documents to prepare the transition from Symfony 2 to Symfony 3. For example, today someone asked me via Twitter if we had an article explaining the new Symfony 3 directory structure.

Would it be enough to create one article explaining how to upgrade applications from Symfony 2 to 3? Would we need to create several articles in a new "Symfony 3" cookbook section? Let's discuss about it and prepare an actionable roadmap.

**Comment by WouterJ** [comment]
#5155 covers how to upgrade and prepare for Symfony 3.

About the major changes that are coming in Symfony 3 (of which the directory structure is probably the biggest): I think documentation should tell the current state and not so much the transition, that's the task of blog posts. This means that instead of adding dedicated articles explaining the new directory structure, we should update the documentation to use the new structure. As we explain the directory structure in the Quick Tour and Book (IIRC), we already kind of "explain" the new directory structure. However, we don't emphasize the "new" structure, we should just talk about the current structure (whether it exists for years or since a couple of weeks doesn't matter).

**Comment by weaverryan** [comment]
@javiereguiluz I'm closing this - we still have a lot of work to do, but we can focus on the 2 milestones:

* https://github.com/symfony/symfony-docs/milestones/2.8
* https://github.com/symfony/symfony-docs/milestones/3.0

If anything is missing, let's add it there.
