### ISSUE TITLE
Improve generic deployment article

### ISSUE THREAD

**Issue by wouterj** [symfony/symfony-docs#5158]
From the article:

> **B) Configure your app/config/parameters.yml File**
> 
> This file should not be deployed, but managed through the automatic utilities provided by Symfony.

We should better explain what the "automatic utilities" are. Afaik, it's only the incenteev parameter handler that's included in the SE? Or is there something from Symfony itself that handles his.

The step is also a bit strange as it only tells what _not_ to do. Nothing explains what the user needs to do.

_This was issue was submitted by a user on a [dutch forum](http://www.phphulp.nl/php/forum/topic/symfony-vraag-mbt-deployen/97651/last/)_

**Comment by juliendufresne** [comment]
:+1: on this one.
It's probably not about incenteev parameter handler because if we follow the document, we have not installed any dependencies yet (done in the step after that).

I don't know if there is a tool for that. If we deploy with capistrano, Incenteev parameter handler seems not to be the solution.

The best place to store the parameters.yml file in a capistrano structure is in the `shared/app/config/` directory. If we configure incenteev parameter handler to do that, then we need the same structure for our devlopment environment.
```json
        "incenteev-parameters": {
            "dist-file": "app/config/parameters.yml.dist"
            "file": "../shared/app/config/parameters.yml"
        },
```

**Comment by ThibauldNuyten** [comment]
Shit like this is why people think development is hard. It's not, people just FUCKING SUCK BALLS at making documentation for *anything*. 

I lost count how many times I read a tutorial where lots of critical information was missing. Critical meaning information absolutely required to finish the exercise. i.e. lots of times I've seen tutorials that would say "add xyz code to your project", without specifying where in the project to place that code, or in which file, or *exactly where* in the file it should be placed. Also often missing is what exactly the code does, and why it's there/needed in the first place. 

Coding is the new magic. You say (type) a few words, and things happen, but no one is expected to know what those words do anymore. Frameworks were a blessing, but the more I get into them the worse this shit gets. There is absolutely no point in adding a function to your framework if the documentation for it sucks or is nonexistent.

**Comment by javiereguiluz** [comment]
@ThibauldNuyten I totally agree with you! That's why I love Symfony documentation. Everything works, you can copy+paste the code, they even include the necessary `use ...` statements in case you don't use an IDE, they most of the times explain to you some details about how you should do things in that way, etc. In fact, the worst part about the Symfony Docs is that it creates impossibly high expectations for other projects and whenever you look at other projects docs ... you get disappointed :(

In the particular case of this article, the problem is that it's a vague and generic article on purpose. We have dedicated articles to explain step-by-step how to deploy Symfony apps to Azure, Heroku, etc. But this article is about some general notes and comments about deploying ... so it will always miss information needed in your particular case :(  I can't think of a solution to this problem.

**Comment by juliendufresne** [comment]
@javiereguiluz I totally agree with you when you say that the Symfony Documentation is awesome and contains plenty of information.

But for this case, I still don't understand what the quote from @wouterj refers to
> the automatic utilities provided by Symfony

This quote is [still present in the current documentation][https://symfony.com/doc/current/deployment.html#b-configure-your-app-config-parameters-yml-file].

Which automatic utility is it referring to?
As I said in my previous comment, it can not be the `incenteev/composer-parameter-handler` package because it uses the parameters.yml.dist file which is under version control (so it should not contains critical information such as production environment credentials).
I don't know any "tool provided by symfony" able to manage the parameters.yml file in the production environment.

**Comment by garek007** [comment]
Yes I am wondering what "automatic utilities" are myself. I agree with ThibauldNuyten.
