### ISSUE TITLE
Entity Provider: improving-performance-with-a-join @ORM\ManyToMany

### ISSUE THREAD

**Issue by bokonet** [symfony/symfony-docs#5183]
Is it possible to join a ManyToMany relation?
I got still 2 queries with that join.

How to Load Security Users from the Database (the Entity Provider) 
http://symfony.com/doc/current/cookbook/security/entity_provider.html#improving-performance-with-a-join

**Comment by xabbuh** [comment]
Hey @bokonet, do you suggest to improve the documentation or is this more a support question? If it's the letter, you are better off asking this on [IRC](http://symfony.com/irc) or on the [mailing list](http://groups.google.com/group/symfony2). Otherwise, you should probably clarify what you want to be changed in which way.

**Comment by bokonet** [comment]
Hey @xabbuh, i think its not possible to join a ManyToMany relation to improve performance. so that part of the documentation make no sense for me and should be updated. Am i wrong?
