### ISSUE TITLE
[Testing]  add more details on how to play with fake files for file uploading

### ISSUE THREAD

**Issue by allan-simon** [symfony/symfony-docs#5346]
related with https://github.com/symfony/symfony/issues/14805 

http://symfony.com/doc/current/book/testing.html#functional-tests

The documentation only reference about file uploading is an example of code calling `UploadedFile` with some arguments, without explanation on these arguments.

Problem I've encountered 
- the Path has to exists , but if so , does the mime type/content/size has to fit,  does precising myself the size override the one my file actually has?
  - if I can override everything why do I have to provide a valid path to start with ?

**Comment by alexislefebvre** [comment]
We can guess how it works by looking at the constructor of the `UploadedFile`: https://github.com/symfony/symfony/blob/554303e339c3ba9044d037e5cd0250b2c5a0c3c1/src/Symfony/Component/HttpFoundation/File/UploadedFile.php#L76-L97

> the Path has to exists , but if so , does the mime type/content/size has to fit

Accoding to the code and its documentation: *`The type of the file as provided by PHP; null defaults to application/octet-stream`*

> does precising myself the size override the one my file actually has?

The file size is `null` by default. It looks like the size of the source file won't be readen, so it has to be provided when creating the `UploadedFile`  object.

**Comment by javiereguiluz** [comment]
Closing this in favor of the file uploading meta-issue: #8255.

**Comment by nmeri17** [comment]
> Closing this in favor of the file uploading meta-issue: #8255.

That issue links to this one recursively, and yet, the question is not resolved. I already piggybacked on several threads to get here. The question is how to fake an UploadedFile within tests. Is it possible? If yes, must the path exist? Because, based on the constructor, it throws an exception if it doesn't. Does that only happen when the test parameter is false? How then does moving uploaded file work, later?

The link to a working example posted in one of the threads has gone dead. Can you be so kind to spell this out somewhere conspicuous?
