### ISSUE TITLE
[Form] Document data mappers

### ISSUE THREAD

**Issue by wouterj** [symfony/symfony-docs#5459]
Data mappers are really great things and they are mentioned zero times in the documentation. We really have to fix it (especially in this era of value objects).

An example of a data mapper: https://gist.github.com/webmozart/36b1cd8a68a5f7844268
A presentation about it: https://youtu.be/Q80b9XeLUEA?t=20m18s

**Comment by weaverryan** [comment]
I had no idea this existed. In fact, I think this solves a problem that I recently told someone was impossible :)

**Comment by xabbuh** [comment]
FYI, @webmozart just published a blog post giving more details about this: https://webmozart.io/blog/2015/09/09/value-objects-in-symfony-forms/

**Comment by stof** [comment]
Be careful about this though. There is a point missing in the blog post of @webmozart: data mapping runs before the validator (as the validator runs on your model). This means that this approach does not work if your value object throws exceptions when trying to instantiate it in a wrong state (which is a best practice). your user would receive a 500 error (because of the exception) instead of seeing nice validation errors on the form.
