### ISSUE TITLE
Why does the cookbook chapter on building a traditional login form feature a hard coded instead of a generated form?

### ISSUE THREAD

**Issue by yhoiseth** [symfony/symfony-docs#5509]
I followed the [guide to create a traditional login form](http://symfony.com/doc/current/cookbook/security/form_login_setup.html), and it worked well.

I did, however, replace the hard coded login form with a login form generated in my controller. I did this to get the [automatic Bootstrap styling](http://symfony.com/blog/new-in-symfony-2-6-bootstrap-form-theme) and because I find it more elegant.

Why isn't this approach (the generated form) used in the documentation as well?

**Comment by javiereguiluz** [comment]
My guess is that using the Form component in this case would be counterproductive. For starters, the reader should be aware of the Form component details, instead of focusing just on the Security component. This "tight coupling" between the article and the forms documentation is something we always try to avoid.

Second, the form is simple enough to write it and understand it as a pure HTML form.

Regarding the Bootstrap styling, that's definitely something that would be better than the current article ... but the readers will easily adapt the style to the CSS framework they are using.

For all of the above, I propose to close this issue as "won't fix". But let's wait to read other people opinions.

**Comment by weaverryan** [comment]
As Javier said, you just need a form with 2 fields. And since you won't be using any of the form processing or validation from the form, it's just not worth it (but there certainly are people like you @yhoiseth who choose to, which is cool). In this case, we'd build a form *just* to have it help us render it (but not use any of its processing power). Even the CSRF token is possible with the form.

So, that's the reason. It won't be right for everyone, but I also figure that people who will care will know enough to choose to use a form :).

Thanks!

**Comment by WouterJ** [comment]
What about adding a tip saying you don't have to hardcode the form and using the Form component might be better in some cases (e.g. bootstrap form theming)?

I know the hardcoded login form has been a big problem of FOSUserBundle, so having something that indicates that this isn't the only way might be a good idea.

**Comment by weaverryan** [comment]
That sounds reasonable to me :). @WouterJ I thought you were on holiday a bit longer? Are you cheating??? ;)

**Comment by xabbuh** [comment]
His doc bot has taken over. :)
