### ISSUE TITLE
Do not use class parameter in "How to Change the default Target Path Behavior"

### ISSUE THREAD

**Issue by wouterj** [symfony/symfony-docs#5547]
We should decorate the `ExceptionListener` class instead of extending it in "How to Change the default Target Path Behavior", because (a) it's nicer and (b) class parameters are deprecated and removed from Symfony 3.

**Comment by stof** [comment]
this is not as simple, because it currently overwrites a protected method, which cannot be done through decoration.

and btw, a different use case should be chosen for the example: avoiding the redirection for AJAX request is now part of the default behavior

**Comment by Restless-ET** [comment]
Hi there, I'm just wondering if this page (or the example at least) is still relevant in the docs.

This comes from a time when XHRs were not ignored by SF itself so the user had to implement that himself if he wanted to achieve the described behaviour.
However since SF 2.6.8 (and 2.3.29) this is no longer the case as this behaviour has been added to the SF firewall (https://github.com/symfony/symfony/commit/9ee74eaef02458074a6366329e5c509f27feb4d4).

My point being if this is actually helping developers or confusing them by leading them to think that SF does not support that by default (thus making them write useless code on their bundles).

Just my 2 cents. :)

**Comment by javiereguiluz** [comment]
I agree with @Restless-ET here and this article seems to have lots of problems (it uses `.class` parameters, it uses the XHR example to explain things (but Symfony already does that), etc.

What if we revamp this article and recommend instead to use the `security.interactive_login` event to do this? Thanks!

**Comment by javiereguiluz** [comment]
Closing because the `/security/target_path.html` article no longer exists in Symfony 3.3 or newer.
