### ISSUE TITLE
Eyes friendly documentation color

### ISSUE THREAD

**Issue by JFOC** [symfony/symfony-docs#5562]
Hello,
Is possible to change documentation color more eyes friendly for long time reading ?

Preferred soft color like in Laravel documentation.

**Comment by javiereguiluz** [comment]
@JFOC we designed the documentation styles to make them easy on the eye. That's why we don't use small font sizes or dimmed colors, which make you "force" your eyes and in the long run cause troubles.

We can't chage these styles because they match the styles of the rest of the website. I don't know if it can help you, but one possible solution would be to use the [Stylebot extension](https://chrome.google.com/webstore/detail/stylebot/oiaejidbmkiecgbjeifoejpgmdaleoha) to apply a custom CSS style on the symfony.com documentation.

**Comment by JFOC** [comment]
Aha..I see

**Comment by JHGitty** [comment]
I think we should close this issue?
