### ISSUE TITLE
delivery-whitelist config option does not behave as documented.

### ISSUE THREAD

**Issue by msteltenpool** [symfony/symfony-docs#5790]
http://symfony.com/doc/current/reference/configuration/swiftmailer.html#delivery-whitelist

"If set, emails matching any of these patterns will be delivered like normal, instead of being sent to delivery_address."

This is not true, the class Swift_Plugins_RedirectingPlugin sends it to both the white listed recipient address as well as the delivery_address.

You can see that behavior in the previous mentioned class, after it adds the white listed address as recipient, it also adds the default recipient (delivery_address)l.

```php
foreach ((array) $this->_recipient as $recipient) {
    if (!array_key_exists($recipient, $to)) {
        $message->addTo($recipient);
    }
}
```

**Comment by xabbuh** [comment]
@msteltenpool Thanks for reporting this misleading description. This should indeed be changed.

**Comment by weaverryan** [comment]
Great bug report - thanks for this, it's now fixed!

**Comment by ReSpawN** [comment]
Is this back for some reason @weaverryan? We've tried all variations we could find but it seems to be inoperative. It delivery_addresses work perfectly though.

**Comment by xabbuh** [comment]
@ReSpawN What exactly is the behaviour you observe and what did you expect instead?

**Comment by ReSpawN** [comment]
@xabbuh Dude, I feel so stupid. After much debugging and checking lines of code, it seems that we we're using a SwiftMailer which was supplied with Symfony 2.8. We've neglected to update it as we then needed to change hundreds of calls to SwiftMailer's Message (used to be newInstance, now anonymous constructed). 

Thus, it turns out to be a deprecated buggy version. :)
