### ISSUE TITLE
missing option parameter/parameters in form type choice

### ISSUE THREAD

**Issue by poolerMF** [symfony/symfony-docs#5806]
http://symfony.com/doc/current/reference/forms/types/choice.html

missing parameter **choices_as_values**

and in ChoiceType.php I see another options, not described:
**choice_loader**
**choice_label**
**choice_name**
**choice_value**
**choice_attr**
**group_by**

**Comment by xabbuh** [comment]
Thank you for reporting this @poolerMF. You are absolutely right that we are currently missing docs for these things. However, we already have an issue covering this (see #5179) and two pull requests which try to cover the gap (see #5755 and #5788). That's why I am going to close here nonetheless. But anyway, once again thank you very much for your contribution!
