### ISSUE TITLE
Wrong link in book/page_creation.rst

### ISSUE THREAD

**Issue by pliski** [symfony/symfony-docs#5853]
In [symfony-docs/book/page_creation.rst](https://github.com/symfony/symfony-docs/blob/2.8/book/page_creation.rst) > "Creating a Page: Route and Controller"

the link:
http://localhost:8000/app_dev.php/lucky/number

should be: 
http://localhost:8000/app_dev.php/en/lucky/number

with the parameter for i18n.

Otherwise I'm getting a 404:
No route found for "GET /lucky/number"

**Comment by pliski** [comment]
In fact the symfony_demo app comes with this configuration options in [app/config/routing.yml](https://github.com/symfony/symfony-demo/blob/master/app/config/routing.yml):

```
...
app:
...
    prefix:   /{_locale}
...
```

So all the link in the book will generate the no route Exception.

Not a big deal but newbies could think that their new out of the box demo app doesn't work and get discouraged.

**Comment by javiereguiluz** [comment]
@pliski thanks for reporting this problem. Let me explain what's happening:

1) When you install Symfony, the Welcome Page points to `symfony-docs/book/page_creation.rst` article. The routes of this article don't use the language code (it's too early in the book to explain internationalization).
2) The Symfony Demo application adds the language code in all its routes.

However, this is not a problem. The reason is that the Symfony Demo and the Symfony Book are completely independent.

@pliski I'd like to ask you: how did you mix the demo app and the book? Where does this confusion come from? Is there anything we can do to avoid these issues in the future? Thanks.

**Comment by WouterJ** [comment]
Closing, as this does not seem to be a direct problem with the docs. However, I would like to discover how we can make it more clear that the demo app and the book are not related to eachother, so feel free to comment @pliski.
