### ISSUE TITLE
Document autoload changes in the Standard Edition

### ISSUE THREAD

**Issue by xabbuh** [symfony/symfony-docs#5941]
With version 5 of the SensioDistributionBundle some changes must be done to the front controllers of your application (see sensiolabs/SensioDistributionBundle#242 and https://github.com/symfony/symfony-standard/blob/2.8/UPGRADE-2.8.md). It would be good to document this somewhere.

**Comment by Tobion** [comment]
I don't think this is really necessary. in http://symfony.com/doc/current/cookbook/upgrade/major_version.html#update-your-code-to-work-with-the-new-version is says read the UPGRADE file. And in the upgrade-2.8 this is documented.

What is not documented is the new directory structure, i.e. there is no upgrade-3.0 document at all.

**Comment by Tobion** [comment]
Actually the major version upgrade help http://symfony.com/doc/current/cookbook/upgrade/major_version.html should recommend to upgrade to the latest minor version first before upgrading the major version. Otherwise they would miss alot of deprecations.

In light of this the title ´Upgrading a Major Version (e.g. 2.7.0 to 3.0.0)` is bad because one should only upgrade from 2.8 to 3.0, not from 2.7.

**Comment by javiereguiluz** [comment]
Closing as "won't fix" because the changes are already documented in the UPGRADE guides. Besides, the SensioDistributionBundle is now deprecated and it won't be available in Symfony 4 (to be released in November 2017). Thanks!
