### ISSUE TITLE
Difference between dev and prod logs

### ISSUE THREAD

**Issue by yapro** [symfony/symfony-docs#6179]
Please, help me. I want to write documentation about difference between dev and prod. Which a section can I do it?

Based on https://github.com/symfony/symfony/issues/17475#issuecomment-173622868

**Comment by xabbuh** [comment]
Is this still in issue even with the changes done in symfony/symfony#17202?

**Comment by yapro** [comment]
@xabbuh off course

**Comment by javiereguiluz** [comment]
@nicolas-grekas can you please tell us if this is fixed by the new `framework.php_errors.log` config option in https://symfony.com/doc/current/reference/configuration/framework.html?

If yes, could you please confirm to us that this is `false` by default in `prod` meaning that you still need to configure PHP error log properly to get them in the Symfony app? Thanks!

**Comment by javiereguiluz** [comment]
I'm closing this because of the lack of activity.
