### ISSUE TITLE
[DX] Fix documentation for login firewall

### ISSUE THREAD

**Issue by morille** [symfony/symfony-docs#6307]
[As explained in this issue](https://github.com/symfony/symfony/issues/17921), the documentation for login form is not correct concerning common pitfalls number 2, login firewall.

**Comment by xabbuh** [comment]
The issue is that we recently replaced the different routes for `login_path` and `check_path`. Thus the login credentials will now be validated by the firewall that also has the form. Possible solutions would be to change the `check_path` route again or to add a shared context to both firewalls.

However, I am not sure if we should actually describe the usage of different firewalls here at all. My perception is that most of the times when people use different firewalls it's completely unnecessary and proper access control rules will be more appropriate. So in my opinion we should rather drop this part here.
