### ISSUE TITLE
Add cookbook entry about debugging and monitoring errors in production mode

### ISSUE THREAD

**Issue by Koc** [symfony/symfony-docs#6372]
There lack of documentation about dealing with errors on production. Some best practices about logging errors, include fatal error with traces. For example in 2.7 added `symfony_debug_backtrace` function, but there is no recipe how to use it in production.

**Comment by Koc** [comment]
/ cc @nicolas-grekas

**Comment by Koc** [comment]
#6342 similar but about different case: dev env. In this ticket we are talking about catching error in production

**Comment by javiereguiluz** [comment]
I'm sorry but I must close this issue as "won't fix". We already explain the production details for logging, etc. But we can't add docs about monitoring in prod general prod debugging instructions because they are out of the scope of Symfony Docs. Sorry but our resources are limited so we must focus. Thanks for understanding.

**Comment by Koc** [comment]
Nevermind. This issue is not relevant since PHP 7.0 (when fatal errors was converted to exceptions).
