### ISSUE TITLE
[Form] Form type as a service

### ISSUE THREAD

**Issue by theofidry** [symfony/symfony-docs#6499]
In light of [this new deprecation](http://symfony.com/blog/new-in-symfony-3-1-frameworkbundle-improvements?utm_source=feedburner&utm_medium=feed&utm_campaign=Feed%3A+symfony%2Fblog+%28Symfony+Blog%29#deprecated-built-in-form-types-as-services) of built-in types as services, I think it would be a good idea to add a note about it [here](http://symfony.com/doc/current/book/forms.html#defining-your-forms-as-services) about _when_ you should register types as a service. I know more than one person (myself included) that thought types had to be registered this way to be used.

It is also not clear why we must tag form types, IIRC it's to be able to use the form type name instead of it's FQCN? If so maybe this should be mentioned as well as using the name instead of the FQCN is more brittle and it may not be something you want to enable.

**Comment by stof** [comment]
Before 2.8, they indeed had to be registered (to make the name known).

As of 2.8, the Form component will auto-register form types on their first usage by creating a new instance (thanks to the fact that they are used by their class name). So defining a service for the form type is necessary only if you need to inject some dependencies in the form type (for instance, the ``entity`` type needs to inject the doctrine manager registry).
Another reason to keep registering the service in 2.8 is backward compatibility with the name based system (which does not exist anymore in 3.0, which is why we can deprecate these services)

**Comment by javiereguiluz** [comment]
It's been two years since this issue was opened. I wonder if it's still relevant, considering that in modern Symfony apps everything is a service by default and their IDs are FQCN. What do you think @theofidry? Thanks!

**Comment by theofidry** [comment]
I'm not sure to be honest. The issue was _when_ do you need to register it as a service and the confusion with the tag. Maybe @HeahDude has more insight

**Comment by stof** [comment]
The tag is here to identify the services being form types to put them in the registry (we don't put the whole container in it)

**Comment by xabbuh** [comment]
IMO http://symfony.com/doc/current/form/form_dependencies.html provides all the needed information.

**Comment by javiereguiluz** [comment]
I agree with Christian. This seems to be well covered now in the docs. Let's close. Thank you all!

**Comment by HeahDude** [comment]
👍
