### ISSUE TITLE
Should the image in the Schedule section be clickable?

### ISSUE THREAD

**Issue by alexislefebvre** [symfony/symfony-docs#6567]
The image in the [*Schedule* section](http://symfony.com/doc/2.3/contributing/community/releases.html#schedule) is not clickable despite the fact that its dimensions allow easier reading when opened in full size: http://symfony.com/doc/2.3/_images/release-process.jpg

![release-process](https://cloud.githubusercontent.com/assets/2071331/15263368/b95b5a76-1969-11e6-9982-415b4559e3b9.jpg)

**Comment by alexislefebvre** [comment]
It looks like none of the existing images included with `.. image:: …` are clickable, is this syntax exist in [Sphinx](http://www.sphinx-doc.org/en/stable/rest.html#images)?

**Comment by javiereguiluz** [comment]
@alexislefebvre to answer your question: yes!

Sphinx doesn't provide this, but we can use `:class:` attribute to add a CSS class to the image:

```rst
.. image:: ...
   :class: zoomable
```

Then we add some JavaScript magic to symfony.com and look for `zoomable` images (we'll need a better CSS name).

We'll try to do this soon as part of a bigger doc section revamp. I'd say let's close this issue for being too specific (it talks about 1 image) and because we're already working on something related but more generic. Thanks.

**Comment by alexislefebvre** [comment]
@javiereguiluz Thanks for your answer. Are they many images that are larger than the documentation (in other words, which are worth viewing in full size)? As a workaround, links to *big* images may also been added under these images.

I'm closing this issue.

**Comment by alexislefebvre** [comment]
@javiereguiluz 

> We'll try to do this soon as part of a bigger doc section revamp. I'd say let's close this issue for being too specific (it talks about 1 image) and because we're already working on something related but more generic. Thanks.

Are there some news about this?
