### ISSUE TITLE
Every component should have main page with list of all available topics (without scrolling down)(or in sidebar)

### ISSUE THREAD

**Issue by sruj** [symfony/symfony-docs#6818]
I suggest, as it was before, to create main page for every component where is chronologically list of all available topics about component. 

It's uncomfortable, when you want to read all topics from start to end, to open the component main  page and scroll down to find next topic.

I know there is next and previous link, but its better when you see all the list on the sidebar or the the main page chronologically.

**Comment by javiereguiluz** [comment]
@sruj thanks for this proposal ... but I'm afraid I must close it as "won't fix" because, as you can see, we haven't changed this in more than a year ... and we are not planning to change it soon either. In any case, we're still thinking about how to improve this because the current navigation is far from ideal. Thanks!
