### ISSUE TITLE
Authentication is not clearly explained

### ISSUE THREAD

**Issue by Herod** [symfony/symfony-docs#6823]
I think that Authentication part is not very well explained.
For example I am not clear what is login_check doing or what to do with the login listener since there is already an abstract authentication listener.
In general the security part is very hard to understand or the explanations are incomplete in the documentation and sometimes FOSUserBundle is not enough.

http://symfony.com/doc/current/components/security/authentication.html

**Comment by javiereguiluz** [comment]
We agree that the Symfony Security docs need a lot of improvements. This is in our priority list ... but it's taking us a lot of time because of the massive complexity of the Security internals.

In any case, to focus all our discussions about this in one place, we've created a meta issue in #7496 and we've linked this issue from there. That's why we're closing your issue ... but only to avoid duplicated discussions. We won't forget about what you said here. Thanks!
