### ISSUE TITLE
Build docs locally and navigate fully offline

### ISSUE THREAD

**Issue by yceruto** [symfony/symfony-docs#6844]
I found some troubles to navigate fully offline through amazing Symfony documentation:

(1) Inside `symfony-docs/_build/_theme/_templates/layout.html` was declared the main assets to external urls:
* css `http://symfony.com/css/compiled/v5/all.css?v=4`
* js `http://symfony.com/js/v5/all.js?v=4`

Without these files the documentation is almost impossible to navigate.

(2) Other small but not least important is that all *.svg paths (maybe some png) inside `http://symfony.com/css/compiled/v5/all.css`, they aren't offline.

Is possible fix that ?

**Comment by xabbuh** [comment]
I am not sure if we can make that configurable. The thing is that we need to refer to these external resources to make the build be nicely accessible on our platform.sh builds.

**Comment by yceruto** [comment]
Is no possible to create another static folder apart from `_static` generated by sphinx and move theses assets inside ? as well as they did with `symfony-docs/_images` folder ?

**Comment by wouterj** [comment]
There is a big difference between images and the CSS styles:

 * Images are managed in this repository and deployed to symfony.com
 * CSS styles are managed in a symfony.com repository and deployed. This repository doesn't have any control over the CSS styles.

The problem here is that every time there is a CSS style change on symfony.com, we would have to update the files stored in this repository as well. This means we have duplicated files, which will be just a waiting game until they get out of sync (giving that the CSS styles are improved and tweaked pretty often).

To be honest, I think you're one of the only people building the docs locally for this purpose, I don't think the extra overhead is worth this.

However, there is some good news for you. Comment [this line](https://github.com/symfony/symfony-docs/blob/master/_build/conf.py#L42) (and maybe line 38) and you can build the docs correctly (with the default Sphinx theme instead of the symfony.com one).

You can also download the PDF (these might do not work correctly at the moment, because of the recent major doc restructure, but we're working hard to fix this) from symfony.com.

At last, you can of course simply download the files from symfony.com and save them on your local PC.

**Comment by yceruto** [comment]
> To be honest, I think you're one of the only people building the docs locally for this purpose, I don't think the extra overhead is worth this.

I understand and agree with you, I've a very bad extra super slow speed connection :smile: 

> However, there is some good news for you. Comment this line (and maybe line 38) and you can build the docs correctly (with the default Sphinx theme instead of the symfony.com one).

Yes, actually it's what I do, but the symfony.com style is pretty good and had hoped to use it. :cry: 

> You can also download the PDF (these might do not work correctly at the moment, because of the recent major doc restructure, but we're working hard to fix this) from symfony.com.

>At last, you can of course simply download the files from symfony.com and save them on your local PC.

Sadly it's not an option for me (remember slow very slow speed connection) ;)

Thanks and sorry for the noise,
closing... wontfix  :+1:
