### ISSUE TITLE
Add reference to the AWS SES Monitor Bundle

### ISSUE THREAD

**Issue by Aerendir** [symfony/symfony-docs#6860]
[This page](symfony-docs/email/cloud.rst) explains how to use AWS SES to send e-mails.

The problem is that at the start the account is put in a sandbox mode. To go out of it it is required to file an issue asking to "fully activate" the account.

To activate the account, Amazon requires the handling of bounces and complaints.

I wrote a bundle for this: http://github.com/Aerendir/aws-ses-monitor-bundle

Maybe useful to add it to the documentation to make others able to fully use AWS SES with Symfony 2.

**Comment by javiereguiluz** [comment]
I'm really sorry but I must close this as "won't fix". The reason is that we're simplifying docs as much as we can and we recently removed the article that you mentioned. We now briefly mention email cloud services in the main email article, so a recommendation like this for just one of those services wouldn't fit. I hope you understand it. Thanks!
