### ISSUE TITLE
Search engine is not efficient on basic search (unable to find how to test commands)

### ISSUE THREAD

**Issue by mickaelandrieu** [symfony/symfony-docs#6902]
Hi,

sounds like theses topics have been removed from actual docs (don't think this was intended though).

Compare with PDF of components in 3.1 (page 65): 
[Symfony_components_3.1.pdf](https://github.com/symfony/symfony-docs/files/429698/Symfony_components_3.1.pdf)

I tried to look at Console Component docs (in Components section), to search for both "ApplicationTester" and "CommandTester" in the search engine, with no results.

Mickaël

**Comment by ogizanagi** [comment]
It's actually documented in the guide: http://symfony.com/doc/current/console.html#testing-commands

**Comment by mickaelandrieu** [comment]
Thank you @ogizanagi.

Do you have any idea why we can't find it using search engine? Tried also [http://symfony.com/search?q=Testing+Commands](http://symfony.com/search?q=Testing+Commands)...

The main issue to me is probably here: the search engine is not efficient at all. Fix it will probably fix all the missing informations that are not missing but are somewhere in the website.

What do you think ?

**Comment by ogizanagi** [comment]
The search engine indexation has probably not been updated to reflect the new documentation structure :/
It seems I can't find anything else than third-party bundles documentation.

@javiereguiluz probably has more clues.

**Comment by mickaelandrieu** [comment]
Sounds critical issue ... let me know if I can help :) /c @javiereguiluz

**Comment by javiereguiluz** [comment]
Closing it as fixed because the great guys at @algolia fixed all the issues that we introduced after the doc revamp. There are still a few missing fixes on our side ... but we'll complete them in a separate repo. Thanks.

**Comment by rubenrua** [comment]
http://symfony.com/search?q=Testing+Commands

Currently Google is used for searching? Why this change?

**Comment by javiereguiluz** [comment]
@rubenrua because even if Algolia UI/UX is amazing and we love it ... the search results were really bad for us. Google results are much better for all the queries we tested. See this example (Google left, Algolia right):

![search-comparison](https://user-images.githubusercontent.com/73419/45094362-5ac6a000-b11b-11e8-9f0b-fe252503641a.png)

Also, Google now searches in Symfony docs, Symfony Blog and all the rest of Symfony websites, so results are much more interesting. That's why we changed it.

In any case, we're super grateful to Algolia team. They are AMAZING and they always helped us a lot.
