### ISSUE TITLE
Documentation for 2.3 on Symfony.com does not exist

### ISSUE THREAD

**Issue by cjunge-work** [symfony/symfony-docs#6952]
I'm wondering why the documentation on symfony.com doesn't include Symfony 2.3, considering 2.3 is supported until May 2017.

I was looking for documentation on how to set up a service factory, but the dropdown on the documentation page for what I needed only shows back to 2.7.
http://symfony.com/doc/current/service_container/factories.html

There were major changes in the syntax of factory service config between 2.3 & 2.7, which confused me until I dug thru the repository to find the info I needed. I think 2.3 should be documented until it's officially EOL end of May 2017.

**Comment by wouterj** [comment]
This is because the 2.3 docs use the old structure: http://symfony.com/doc/2.3/components/dependency_injection/factories.html

**Comment by javiereguiluz** [comment]
@cjunge-work the 2.3 docs are still published: http://symfony.com/doc/2.3/index.html  The problem is that we no longer show deprecated versions in the doc version selector. To be honest I'm not sure that's a good idea because I've already been asked several times why did we remove the 2.3 docs.

**Comment by cjunge-work** [comment]
@wouterj There's no link from the Symfony site to that section, and googling is pretty hard to find it as well! I also think it might not be a good idea to remove the link to 2.3, as some sites (like ours) won't upgrade until nearer EOL (if at all).

LTS implies support/help/documentation until EOL, otherwise it doesn't seem like it's really LTS IMHO.

**Comment by javiereguiluz** [comment]
@cjunge-work there are a few things to comment here:

* Symfony 2.3 is unsupported since May 2016. We won't fix any bug for it. Only if we find a critical security issue, we'll fix that (and only until May 2017). So we shouldn't consider "security support" === "bug fix support".
* Because of the doc revamp, it's now very hard / impossible to show the same page in every possible version (we've changed almost every page URL, so it's very hard to match pre-2.7 pages with post-2.7 pages).
* In any case, soon we're going to introduce some changes to the doc version selector to show recent unmaintained versions (for example today we don't show 3.0 in the selector because that version is unsupported ... but it's so recent that some people are complaining about that).

Considering all this, I must close this issue as "won't fix". I'm sorry @cjunge-work.
