### ISSUE TITLE
Bundle documentation dont explains routing and service config

### ISSUE THREAD

**Issue by Deltachaos** [symfony/symfony-docs#6957]
A beginner has asked me how to add a bundle and i told him that he should use the "generate:bundle" command. Before he tried to do it by hand using this documentation:
http://symfony.com/doc/current/bundles.html

The problem here is that it not mentions that you should also import a routing configuration and a service configuration for the bundle.
This is a bit confusing for beginners.

I am opening this issue because i currently dont have time to change the documentation currently.

**Comment by xabbuh** [comment]
Not sure about this. How often does a newcomer really have to create a new bundle (most of the times using the AppBundle shipped with the Symfony Standard Edition should be sufficient)?

**Comment by Deltachaos** [comment]
Well it is possible that it it is the first time he needs to add something to the app/config/routing.yml. Before he probably has not changed this configuration.

**Comment by wouterj** [comment]
The changes in the Symfony eco-system since this issue has been created (Symfony Flex + promoting not to use application-bundles) has made this issue a bit redundant I think. So I'm going to close this issue now, I don't there is anything to do.

If you disagree, feel free to place a comment, we can always reopen :)
