### ISSUE TITLE
Rethink "How to Call a Command from a Controller" article

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony-docs#7146]
This was [just published](https://twitter.com/SenseException/status/799633039919841280):

![tweet](https://cloud.githubusercontent.com/assets/73419/20443387/e8daee4a-adcc-11e6-8f96-a747698f76ff.png)

It refers to this article: [How to Call a Command from a Controller](http://symfony.com/doc/current/console/command_in_controller.html)

Is this really such a bad practice? Should we remove that article? Should we display at the beginning of the article a warning message?

**Comment by HeahDude** [comment]
I fail to see why using a controller as an entry point in the application to launch a command would be a bad thing. It can be pretty handy IMHO.

**Comment by theofidry** [comment]
My thoughts: no this article should not be removed although may be rethought a bit.

IMO there is two experimented approach:

- Have controllers and commands clean: they are just a entry point to your application with no logic, rather an adapter to a protocol for an application (i.e. protocol agnostic) action.
- Have fat controllers and commands: while it's not super nice, people just don't care because they are not important part of their application and prefer to put their focus on something else

Also there is a philosophical POV: some people like fabpot like to think of controllers or commands as a glue between your app and an entry point, so they can be big service locators; while some people like dunglas prefer to have them smaller using DI, more re-usable and (unit) testable.

So to me there is nothing wrong with not wanting to refactor a command and simply call it in a controller action. It adds to the technical debt for sure, but there is nothing wrong per se and it's up to the developer to think if this should be refactored or that for his use case it's not worth it.

**Comment by javiereguiluz** [comment]
Closing it as "won't fix" because of the comments published above. It's not really a bad practice in some circumstances. Thanks!
