### ISSUE TITLE
[Forms][Enhancement] orphanRemoval for Form Collections

### ISSUE THREAD

**Issue by vudaltsov** [symfony/symfony-docs#7148]
In [How to Embed a Collection of Form >>> Allowing Tags to be Removed >>> Doctrine: Ensuring the database persistence](http://symfony.com/doc/current/form/form_collections.html#allowing-tags-to-be-removed) section.

One of the options is to set `orphanRemoval=true` on OneToMany relations instead of doing anything in the controller for those tags to be deleted automatically.

[DoctrineDocs](http://docs.doctrine-project.org/projects/doctrine-orm/en/latest/reference/working-with-associations.html#orphan-removal)

**Comment by HeahDude** [comment]
👍 for this instead of the long work around in the controller.

**Comment by Koc** [comment]
https://labs.madisoft.it/orphan-removal-forms-collection-and-collections-elements-swapping-pick-your-poison/ interesting article about orphanRemoval restrictions

**Comment by vudaltsov** [comment]
Yeah, thank you. But still it might be usefull to show that in docs with
warnings.

19 нояб. 2016 г. 7:07 ПП пользователь "Konstantin Myakshin" <
notifications@github.com> написал:

**Comment by javiereguiluz** [comment]
I'm closing this old issue because I think it's better to keep showing the current doc: https://symfony.com/doc/2.7/form/form_collections.html#allowing-tags-to-be-removed  "Our" solution is really simple and only requires adding a few lines of code in the entity class, so you don't have to change any controller. The `orphanRemoval` option looks cool, but the given article shows that you need to make other changes and the solution is not that simple. Thanks.
