### ISSUE TITLE
Add docs for the Firewall Config class

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony-docs#7164]
https://github.com/symfony/symfony/pull/19398 introduced a FirewallConfig class accessible from FirewallContext. Should we document it or at leas mention it?

**Comment by ogizanagi** [comment]
Use cases for accessing the firewall configs are probably too limited right now, so I don't think it worth documenting it. [Your blog post](http://symfony.com/blog/new-in-symfony-3-2-firewall-config-class-and-profiler) is probably perfect and enough for mentioning this feature.

Plus, if more use cases are discovered, we may rework some parts (see https://github.com/symfony/symfony/pull/20591) which will expose a different entrypoint.

cc @chalasr

**Comment by chalasr** [comment]
@ogizanagi is right about that use cases are limited but I would say it's still good to have in the documentation because of the considerable number of existing support questions and issues for which a small mention about this feature would have been useful:

- http://stackoverflow.com/questions/19610316/how-to-access-firewall-configuration-in-controller
- http://stackoverflow.com/questions/17886818/symfony2-detect-if-user-is-inside-a-secure-firewall
- http://stackoverflow.com/questions/19610316/how-to-access-firewall-configuration-in-controller
- http://stackoverflow.com/questions/23128399/symfony2-get-firewall-name-on-login-page
- https://github.com/symfony/symfony/issues/14435
- https://github.com/symfony/symfony/issues/15294
- https://github.com/symfony/symfony/issues/4753

Even if it's just about documenting what is actually possible to do on this subject so it would be clear what is not, and give the right way to do (especially since using the security token `providerKey` is neither always available nor always accurate).

Maybe we could start by adding a small mention in the bundle documentation and make it grows as we improve the feature (I feel it could be useful to add some more informations about the registered listeners for instance, but let's wait for concrete use cases).

If nobody pick it I can give it a try asap

**Comment by javiereguiluz** [comment]
@chalasr documenting this won't be easy for me. If you want to give a try, I can help you later polishing the docs if needed. Thanks!

**Comment by javiereguiluz** [comment]
Fixed by #9207.
