### ISSUE TITLE
"Deep into" articles

### ISSUE THREAD

**Issue by Vinorcola** [symfony/symfony-docs#7297]
I'd like to suggest a new type of articles I think the doc is missing: Some "**Deep into ...**" articles.

The actual doc is aimed to explain **How to use** the framework but I think it is missing some **How it works** articles. Those articles would target more experimented users, helping understanding how Symfony and it's components works. This would help customizing Symfony and components and potentially increasing the number of pull requests because there will be more developpers that understand the internals.

Let's take the Security for example. We have a main article explaining how to configure your security, how it basically work. But I would suggest an article "Deep into Security" that explain the workflow:

- Firewall
- Authenticator
- Guard
- User provider
- Authorization
- Voter
- etc.

Right now, we have an article explaining **How to** create custom Voter, but it is hard to get when the voter get in action. The aim is to explain when each component come on stage, what does it do, how does it do it, ...

Hope it's clear enough.

**Comment by javiereguiluz** [comment]
Yes, we're missing some advanced articles for the Security component. In #7293 we're proposing to add one of those advanced articles about Security.

**Comment by Vinorcola** [comment]
I give Security as an example, but this could apply to any topic:

- Form, Form theming, Form normalization, etc.
- Dependency Injection, Services, Compiler, etc.

**Comment by javiereguiluz** [comment]
We agree that the Symfony Security docs need a lot of improvements. This is in our priority list ... but it's taking us a lot of time because of the massive complexity of the Security internals.

In any case, to focus all our discussions about this in one place, we've created a meta issue in #7496 and we've linked this issue from there. That's why we're closing your issue ... but only to avoid duplicated discussions. We won't forget about what you said here. Thanks!
