### ISSUE TITLE
[3.3][DI] Service ids now default to the classname

### ISSUE THREAD

**Issue by wouterj** [symfony/symfony-docs#7329]
Symfony 3.3 has a really nice feature that allows to use the service class as its ID.

Reference: https://github.com/symfony/symfony/pull/21133

**Comment by javiereguiluz** [comment]
My vote would be for the second option.

**Comment by wouterj** [comment]
I think the service IDs as class names make sense for one case only: Services that are merely used for it's tag (e.g. custom listener, etc.).

I think we should update all examples that say "Then tag this service with XXX" to use this new behaviour and add a small section about this in the service container subguides, keeping all other service examples just using the new service IDs.

**Comment by javiereguiluz** [comment]
Closing as fixed because after the latest updates, we always use service injection via autowiring and type-hints and in some cases we show the `->get(Something::class)` alternative, so we're always using FQCN ids. The only place where we show old IDs is in the docs explaining how to update from old Symfony to new Symfony and how can you alias services.
