### ISSUE TITLE
Mistake in validation doc

### ISSUE THREAD

**Issue by Zzortell** [symfony/symfony-docs#7412]
Hello!

I think there is an error in the doc:
[https://symfony.com/doc/current/validation.html#configuration](https://symfony.com/doc/current/validation.html#configuration)

But the actual default config is:
```yaml
framework:
    validation:      { enable_annotations: true }
```

Cheers ;)

**Comment by ogizanagi** [comment]
Actually, this is indeed the "default" config provided [in the standard edition](https://github.com/symfony/symfony-standard/blob/master/app/config/config.yml#L20), but `enable_annotations` is `false` be default, as described in the [FrameworkBundle Configuration class](https://github.com/symfony/symfony/blob/3.2/src/Symfony/Bundle/FrameworkBundle/DependencyInjection/Configuration.php#L604) :)
(Note this value slightly changes since https://github.com/symfony/symfony/pull/21196 to be guessed wisely.

**Comment by Zzortell** [comment]
Thanks for the explanations :) This is unclear, maybe it could be noticed in the doc with a sentence like

> If you are not using the standard edition, you must explicitly enable annotations...
