### ISSUE TITLE
Weird breadcrumb in the doc

### ISSUE THREAD

**Issue by stof** [symfony/symfony-docs#7418]
the breadcrumb on http://symfony.com/doc/current/configuration/external_parameters.html is really weird:
![sf_doc_breadcrumb](https://cloud.githubusercontent.com/assets/439401/22339938/ff2d0200-e3eb-11e6-85c2-8dd4bc90445b.png)

This page has nothing to do with the templating component

**Comment by javiereguiluz** [comment]
This has to do with the global problems explained in #7268.

The only viable solution seems to be to remove the `toctree` directive used to display the `Learn more` links and go back to regular links.

Sadly this will be an immense work and we cannot do it at the moment because we have a lot of pending things to do first. 😢

**Comment by javiereguiluz** [comment]
Quick update: while we wait for the real solution, I've proposed a temporary fix and if accepted, it will be merged into production soon. This is how the same page looks in my local environment now:

![breadcrumbs_after](https://cloud.githubusercontent.com/assets/73419/22470539/eab150aa-e7cf-11e6-89d3-e4ff68a2937a.png)

**Comment by javiereguiluz** [comment]
This was finally deployed ... so let's close it as fixed. Thanks!
