### ISSUE TITLE
The Cache component added a data collector

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony-docs#7437]
https://github.com/symfony/symfony/pull/21065 added a new data collector to gather Cache information. We must check if we list collectors somewhere and if that's the case, add this new collector.

**Comment by iltar** [comment]
I couldn't find a list of data collectors anywhere. The only references I could find:
 - https://symfony.com/doc/current/reference/dic_tags.html#data-collector
 - https://symfony.com/doc/current/profiler.html

Optionally it could be mentioned in the [cache component documentation](http://symfony.com/doc/current/components/cache.html), but it feels out of place due to it being a comonent.

**Comment by javiereguiluz** [comment]
Closing it because of the reasons mentioned by @iltar. We don't list the built-in data collectors anywhere.
