### ISSUE TITLE
Coding standards is in conflict with parameters as environment vars

### ISSUE THREAD

**Issue by wolfwolker** [symfony/symfony-docs#7757]
This cool new sf3.2 feature is in conflict with Coding standards http://symfony.com/doc/current/configuration/external_parameters.html

Extracted from http://symfony.com/doc/current/contributing/code/standards.html#service-naming-conventions `Use lowercase letters for service and parameter names;`

**Comment by javiereguiluz** [comment]
In my opinion, it looks like it's in conflict, but it's not:

```
doctrine:
    dbal:
        host: '%env(DATABASE_HOST)%'
```

`DATABASE_HOST` is uppercase ... but that's the parameter value. The parameter name is `host`, which is lowercase. @wolfwolker is it more clear now?

**Comment by wolfwolker** [comment]
I agree with you @javiereguiluz in that way there is no conflict, but, as the article I mentioned explains, is a good practice to declare de env var as a parameter name, to allow to set a default value in case the env var is not defined.

Also symfony demo project works in that way https://github.com/symfony/symfony-demo/blob/master/app/config/parameters.yml.dist

**Comment by javiereguiluz** [comment]
Ah, I see now the confusion. The real problem is that Symfony uses `parameters` to define the default value of env vars. In this example:

```yaml
parameters:
    env(DATABASE_URL): 'sqlite:///%kernel.root_dir%/../var/data/blog.sqlite'
```

`env(DATABASE_URL)` is not the name of a parameter. It's just the way to initialize the value of the `DATABASE_URL` env var. Maybe we need to add some explanation about this.

Luckily all this will soon be a thing of the past because Symfony 4 replaces the `parameters.yml` file by a `.env` config file.

**Comment by wolfwolker** [comment]
+1 to the .env file :)

**Comment by javiereguiluz** [comment]
Let's close this as "won't fix" and if others disagree, we'll reopen it. Thanks!
