### ISSUE TITLE
[PHPUnit Bridge] SYMFONY_PHPUNIT_REMOVE and prophecy

### ISSUE THREAD

**Issue by BatsaxIV** [symfony/symfony-docs#7798]
Hi,

I've never used prophecy with PHPUnit but the last sentence of the [documentation](http://symfony.com/doc/current/components/phpunit_bridge.html#modified-phpunit-script) looks weird to me :

> Set the SYMFONY_PHPUNIT_REMOVE env var to **symfony/yaml** if you need prophecy but not **symfony/yaml**.

Or maybe I'm missing something.

**Comment by xabbuh** [comment]
The reason is that the bridge by default removes the `symfony/yaml` as well as the `phpspec/prophecy` package from the list of PHPUnit requirements. If you need Prophecy, you will have to list the packages to be removed explicitly (i.e. you then only want to remove the dependency on the Yaml component). Do you think we can clarify that somehow to make it better understandable?

**Comment by BatsaxIV** [comment]
Ok, I understand now and reading again this sentence seems less odd :-)
However, to clarify any doubt, I propose this :

>  If you still need to use prophecy (but not symfony/yaml), then set the SYMFONY_PHPUNIT_REMOVE env var to symfony/yaml.

What do you think?

**Comment by xabbuh** [comment]
Reads good to me. Would you like to submit a pull request? :)

**Comment by BatsaxIV** [comment]
Ok nice !
Yes, I'll make the PR :)

**Comment by Briones** [comment]
I still dont get the message, I think is confusing, the message doesn't clarify about how to get phpunit working with prophecy. I guess that the message means that I need to put `SYMFONY_PHPUNIT_REMOVE="symfony/yaml"` in my `.env`file, and then what? At this point I don't have phpunit with prophecy support, I'm suppose to execute:
`composer install "phpspec/prophecy" --dev` or what?
