### ISSUE TITLE
document style is hard to see

### ISSUE THREAD

**Issue by meotimdihia** [symfony/symfony-docs#7880]
https://symfony.com/doc/current/bundles/EasyAdminBundle/book/configuration-reference.html#list

Tag `<h3>` style look the same as `<h4>` style.  

![](https://i.gyazo.com/89634a7f2ad5722f19c4b40e11ee4f91.png)

i think we should fix this. i am learning symfony.

**Comment by javiereguiluz** [comment]
They are not the same ... but too similar. h3 is 21px and h4 is 18px. Problem is that headings smaller than 18px looks bad in symfony.com design. In any case, I agree with you and this doesn't look good.

However, I think the real problem is that I made a mistake in that configuration reference. I put `easy_admin` as the first level heading ... but that's not needed because this is obviously the first node. This is in my TODO list and I'm going to fix it soon. Thanks!

**Comment by robfrawley** [comment]
Many designs use *styles* to indicate different headers, such as making it italic or not bold, etc. There are many changes that can be made without lowering the size below `18px`, and this design issue has cropped up for me before on other documentation pages, not just the given example.

**Comment by javiereguiluz** [comment]
I'm closing this as fixed. First, the doc of that particular bundle was changed to make things more readable. Second, after [our recent redesign](https://symfony.com/blog/refactoring-symfony-com-front-end) things like these have improved a lot. Thanks!
