### ISSUE TITLE
Document optimistic locking in Symfony forms

### ISSUE THREAD

**Issue by jrysig** [symfony/symfony-docs#7948]
It would be nice to describe support for [Doctrine optimistic locking](http://docs.doctrine-project.org/projects/doctrine-orm/en/latest/reference/transactions-and-concurrency.html#optimistic-locking) mechanism in [Symfony Forms](http://symfony.com/doc/current/forms.html):

Insert ```version``` and ```@ORM\Version``` annotation to entity, add ```version``` as hidden field to the form, handle OptimisticLockException.

**Comment by javiereguiluz** [comment]
@jrysig I'm sorry we didn't reply to this proposal on time. It's true that this is a nice Doctrine feature. However, it doesn't require any Symfony feature or config option to make it work. As explained in http://docs.doctrine-project.org/projects/doctrine-orm/en/latest/reference/transactions-and-concurrency.html#locking-support this is just about adding the `@Version` annotation on the entity. On Symfony's side, you just need to add a regular form field with the version number.

Lately we're trying to reduce the amount of contents to maintain on Symfony Docs. That's why we've removed lots of contents that are published elsewhere (such as all articles related to deployment). And that's the reason why we are closing here: Doctrine docs explain all this nicely, so there's no need to duplicate it. Thanks for understanding it.
