### ISSUE TITLE
[website] List of component in the left menu is incomplete

### ISSUE THREAD

**Issue by stof** [symfony/symfony-docs#8299]
http://symfony.com/doc/current/components/index.html includes the PHPUnit bridge in the list of documented components. But the `components` section of the left menu does not include it.

/cc @javiereguiluz

**Comment by javiereguiluz** [comment]
@stof thanks for reporting this issue. In fact, PHPUnit Bridge is included in the sidebar menu:

![components-list](https://user-images.githubusercontent.com/73419/29763871-415792ee-8bd5-11e7-980c-e24707cdee3b.png)

As you can see, the problem is that we don't sort components alphabetically, so they appear in the same order as defined here: https://github.com/symfony/symfony-marketing/blob/master/components.yml

We've fixed this to always sort components alphabetically. It will be online after the next deploy. Thanks!
