### ISSUE TITLE
[Security] Clarification on use of multiple roles within access_control

### ISSUE THREAD

**Issue by graemechapman** [symfony/symfony-docs#8355]
The [access_control documentation](https://github.com/symfony/symfony-docs/blob/master/security/access_control.rst#2-access-enforcement) does not mention behaviour when restricting access by multiple roles. 

The comment `If the user does not have the given role(s), then access is denied` seems to suggest that multiple roles should be possible and that, when defined with multiple roles, access is denied unless the user has ALL of the specified roles. 

In practice though, the result of this is dependent upon the access decision manager strategy. It is unclear if this is intended but undocumented behaviour, or an issue that needs to be raised in Symfony. 

The response to a related issue from 2013 (https://github.com/symfony/symfony-docs/issues/3290) suggests that multiple roles will be handled with OR logic, but this does not seem to be the case, and I can't find anything in the documentation to confirm this.

**Comment by chalasr** [comment]
When setting multiple `roles` in an `access_control` rule with the default `access_decision_manager` strategy (`affirmative`), the authenticated user must fulfil at least one role of the list in order to be authorized, it's a `OR` condition.
If you change the `access_decision_manager` strategy to `unanimous`, then the user must fulfil all roles of the list defined in the rule, meaning that it's a `AND`.

I agree that this could be made more explicit in the `access_control` documentation.

**Comment by javiereguiluz** [comment]
@chalasr that's a perfect explanation!! Thanks for your help. We're trying to improve this here: #9844.

**Comment by javiereguiluz** [comment]
Fixed by #9844.

**Comment by graemechapman** [comment]
@chalasr @javiereguiluz Thanks for the clarification!
