### ISSUE TITLE
Add top-level Cache article

### ISSUE THREAD

**Issue by weaverryan** [symfony/symfony-docs#8711]
Sorry of this is a duplicate, but we need a top-level "caching" entry, since Symfony 3.3 to talk about how to configure the cache, cache.pools, etc.

See #8710 for an example when I didn't really have a good place to link to (look for `framework.cache.pools`).

3.4 milestone added so we can do it during the Symfony 4 push.

**Comment by B-Galati** [comment]
@weaverryan I would like to help on this subject. If I understand well, we would need a new "cache" entry in the "guides" section of the doc ? This new entry would be like the `Serializer` one ?

**Comment by eXtreme** [comment]
From a developer's perspective, who knows how the component work... Right now there is no up-to-date (or even real) doc how to use and configure the cache in the framework. Every time I start a new project and want to use the cache I have to rely on previous work or dig into various PRs, blogposts etc and try to make it work.

How do you configure pools? How do you configure providers? Dev/test/prod setup? What are these default provider options? What can you do with default system and/or app pool?

**Comment by jrobeson** [comment]
definitely struggling with this one myself.

**Comment by lyrixx** [comment]
I also think this issue is important.
In a proprietary project, it have seen:

```
services:
    Symfony\Component\Cache\Adapter\PdoAdapter:
        arguments:
            - "@doctrine.dbal.default_connection"

    Psr\Cache\CacheItemPoolInterface: '@Symfony\Component\Cache\Adapter\PdoAdapter'
```

So the integration with the framework bundle is totally bypassed. Too bad :( 

There is some doc about pool in the [reference](https://symfony.com/doc/current/reference/configuration/framework.html#pools) but it does not show up via google or algolia :/ More over, people usually forget about this doc section.

For other component we have a dedicated page (see this [doc for the workflow](https://symfony.com/doc/current/workflow/usage.html)) and this is a very good starting point.

So big :+1: for a top-level cache article.

/cc @nicolas-grekas
