### ISSUE TITLE
How to Generate URLs from the Console

### ISSUE THREAD

**Issue by Starojitski** [symfony/symfony-docs#8827]
[This page](https://symfony.com/doc/current/console/request_context.html) in documentation that promises to explain how to to that but does not. All it does is explains why and how to modify router context. But when it becomes interesting it says 
`// ... your code here`
So, the mystery remains - how do i generate urls for my images ? :)

**Comment by javiereguiluz** [comment]
We thought the article was clear enough, but reading your comment means we failed. The idea is that URLs are generated in the same way, no matter if it's a controller, a service or a command console. The difference in the console is that you must configure the context because you are out of the web environment. We're fixing this in #8839.
