### ISSUE TITLE
Remove a tiny article about CSRF

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony-docs#8868]
This article is tiny: http://symfony.com/doc/current/controller/csrf_token_validation.html  and we're removing those kind of articles and merging them into longer articles to make things easier to maintain.

Not to contributors: please don't send a pull request to fix this. First we must decide if we want to merge all CSRF related contents in a new article and where to put it. Thanks!

**Comment by weaverryan** [comment]
👍 for re-thinking this. From what I can see, we have the following CSRF info:

* http://symfony.com/doc/current/controller/csrf_token_validation.html (btw, this is missing the template code - that's needed)
* http://symfony.com/doc/current/form/csrf_protection.html
* http://symfony.com/doc/current/reference/configuration/framework.html#csrf-protection
* https://symfony.com/doc/current/security/csrf_in_login_form.html

I think we should create one new article "CSRF Protection" under the `security/` section. This would include *all* of this content so the user can learn how to use it in forms, without forms, and on the login page. We can then link to this article from the form, security & controller sections. I like it in its own article because it *is* an important topic.

Also, in MakerBundle, we when we add a "login form authenticator" maker, we can auto-generate code that includes CSRF protection. We should make CSRF protection as automatic as possible so that users don't need to think about it much (the form implementation is pretty perfect in that way).

**Comment by javiereguiluz** [comment]
I like this. I'm preparing a pull request to see how this works in practice. Thanks!
