### ISSUE TITLE
Broken view when document have a caution

### ISSUE THREAD

**Issue by ucay** [symfony/symfony-docs#8918]
In `@media` greater than or equal `768px`, if the doc have a single line caution it will break the style.
The `.doc__tools` looks weird.
e.g. https://symfony.com/doc/3.4/bundles/inheritance.html
![screenshot from 2017-12-22 08 38 00](https://user-images.githubusercontent.com/3348846/34281867-31e44f8a-e6f4-11e7-849c-7b413b398a2b.png)

But, if the caution is more than one line, it looks a little nice.
![screenshot from 2017-12-22 08 49 46](https://user-images.githubusercontent.com/3348846/34282010-2692804c-e6f5-11e7-80f8-79c6fd7e2e23.png)

It will be more nice when we change the margin of `.doc__tools` like this.
```stylesheet
@media (min-width: 768px){
    .doc__tools {
        ...
        /* margin: 5px 0 15px 15px; */
        margin: 5px 5px 15px 15px;
    }
}
```
![screenshot from 2017-12-22 08 51 40](https://user-images.githubusercontent.com/3348846/34282159-0a75f438-e6f6-11e7-900b-fc161efd0040.png)

However, I love with this last style, but have no idea how to provide it (stylesheet beginner :laughing:  ).
![screenshot from 2017-12-22 09 08 32](https://user-images.githubusercontent.com/3348846/34282418-b9ee6002-e6f7-11e7-9a19-bc03dc9a1013.png)

note: the last example is using _hacky_ way :smile:

**Comment by javiereguiluz** [comment]
@ucay I agree that this element of the Symfony Docs doesn't look 100% right when the first content of the doc is a caution or note. In the past I tried to make it look like your last example but I failed. There are a lot of different doc contents and there was always some error in some page or in some device, because each solution must be tested in smartphones, tablets and desktops.

I'll try to look into this again ... but I can't promise a fix.

**Comment by javiereguiluz** [comment]
I've looked into this and I'm afraid we can't fix it unless we redesign this page entirely. If we change the margins, the selector looks better when there's an admonition ... but it looks worse otherwise. The real problem is that when using floats you can't do the right design, which is the last one showed by @ucay. It's technically impossible because of CSS.

So, I'm closing this as "won't fix" for now. I'm sorry.
