### ISSUE TITLE
Translate to Persian language

### ISSUE THREAD

**Issue by ghanbari** [symfony/symfony-docs#8954]
Hi, I want translate symfony documents to persian language.
what is the best practice for contribute in other languages that don't have any repository?

**Comment by javiereguiluz** [comment]
Thanks for proposing this contribution to spread the knowledge of Symfony for Persian-speaking people.

You may know it, but in the past we had several translations but [we removed them in 2015](https://symfony.com/blog/discontinuing-the-symfony-community-translations) because it's impossible to keep a translation in sync with the original contents (which change thousands of lines each month).

If you still want to translate docs, I strongly recommend you to only translate the six chapters of the "Getting Started" section of this page: https://symfony.com/doc/current/index.html  Those contents are enough to learn everything you need to start with Symfony and they are short enough to allow a translation and maintaining it.

Since we don't provide official translations, we can't host your contents in any Symfony repo, so you'll need to create a new repo to store them (maybe under a new GitHub organization to you can get help from more people?). These are some useful resources:

* The reStructuredSyntax format we use in the docs: https://symfony.com/doc/current/contributing/documentation/format.html
* The license of the original contents: https://symfony.com/doc/current/contributing/documentation/license.html
* The files we use to build docs: https://github.com/symfony/symfony-docs/tree/master/_build or if you prefer, you can use a free service that hosts and parses RST files: https://readthedocs.org/

Thanks again for your proposal and good luck with the translation!
