### ISSUE TITLE
[DependencyInjection] Added support for variadics in named arguments

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony-docs#9022]
https://github.com/symfony/symfony/pull/24937

**Comment by javiereguiluz** [comment]
Reading the original issue (https://github.com/symfony/symfony/issues/24935) I don't think we should document this explicitly. It's a nice to have feature that works exactly as a user would expect. There's no need to read docs about it to know how to use it.

**Comment by Wirone** [comment]
@javiereguiluz IMO this should be documented explicitly because people who would like to use this feature and are googling for it (like me) not necessarily will read symfony/symfony#24935. Also that issue does not define how it should be used, author just wrote how he tried to use it (when it wasn't supported).
