### ISSUE TITLE
[Question] Line break after each sentence

### ISSUE THREAD

**Issue by Jibbarth** [symfony/symfony-docs#9026]
Hi everyone and thanks for this awesome documentation.

I was watching [this conference about **Documentation as Code**](https://youtu.be/T6YJlaY0Dpw?t=15m49s) and I wondering if we should apply that recommandation : One line by sentence.

I think that allows a better reviewing on PR, and improve readability for diff when we are on smartphone :upside_down_face: 

Just made a test on a online restructuredText editor, and taking [The Big Picture](https://symfony.com/doc/master/quick_tour/the_big_picture.html) as reference : 

```
Start using Symfony in 10 minutes! Really! That's all you need to understand the
most important concepts and start building a real project!

If you've used a web framework before, you should feel right at home with
Symfony. If not, welcome to a whole new way of developing web applications. Symfony
*embraces* best practices, keeps backwards compatibility (Yes! Upgrading is always
safe & easy!) and offers long-term support.
```

could became

```rst
Start using Symfony in 10 minutes! 
Really! 
That's all you need to understand the most important concepts and start building a real project!

If you've used a web framework before, you should feel right at home with Symfony. 
If not, welcome to a whole new way of developing web applications. 
Symfony *embraces* best practices, keeps backwards compatibility (Yes! Upgrading is always safe & easy!) and offers long-term support.
```

and the [display](http://rst.ninjs.org/?theme=basic#VGhlIEJpZyBQaWN0dXJlCj09PT09PT09PT09PT09PQoKU3RhcnQgdXNpbmcgU3ltZm9ueSBpbiAxMCBtaW51dGVzISBSZWFsbHkhIFRoYXQncyBhbGwgeW91IG5lZWQgdG8gdW5kZXJzdGFuZCB0aGUKbW9zdCBpbXBvcnRhbnQgY29uY2VwdHMgYW5kIHN0YXJ0IGJ1aWxkaW5nIGEgcmVhbCBwcm9qZWN0IQoKSWYgeW91J3ZlIHVzZWQgYSB3ZWIgZnJhbWV3b3JrIGJlZm9yZSwgeW91IHNob3VsZCBmZWVsIHJpZ2h0IGF0IGhvbWUgd2l0aApTeW1mb255LiBJZiBub3QsIHdlbGNvbWUgdG8gYSB3aG9sZSBuZXcgd2F5IG9mIGRldmVsb3Bpbmcgd2ViIGFwcGxpY2F0aW9ucy4gU3ltZm9ueQoqZW1icmFjZXMqIGJlc3QgcHJhY3RpY2VzLCBrZWVwcyBiYWNrd2FyZHMgY29tcGF0aWJpbGl0eSAoWWVzISBVcGdyYWRpbmcgaXMgYWx3YXlzCnNhZmUgJiBlYXN5ISkgYW5kIG9mZmVycyBsb25nLXRlcm0gc3VwcG9ydC4KCgpUaGUgQmlnIFBpY3R1cmUKPT09PT09PT09PT09PT09CgpTdGFydCB1c2luZyBTeW1mb255IGluIDEwIG1pbnV0ZXMhIApSZWFsbHkhIApUaGF0J3MgYWxsIHlvdSBuZWVkIHRvIHVuZGVyc3RhbmQgdGhlIG1vc3QgaW1wb3J0YW50IGNvbmNlcHRzIGFuZCBzdGFydCBidWlsZGluZyBhIHJlYWwgcHJvamVjdCEKCklmIHlvdSd2ZSB1c2VkIGEgd2ViIGZyYW1ld29yayBiZWZvcmUsIHlvdSBzaG91bGQgZmVlbCByaWdodCBhdCBob21lIHdpdGggU3ltZm9ueS4gCklmIG5vdCwgd2VsY29tZSB0byBhIHdob2xlIG5ldyB3YXkgb2YgZGV2ZWxvcGluZyB3ZWIgYXBwbGljYXRpb25zLiAKU3ltZm9ueSAqZW1icmFjZXMqIGJlc3QgcHJhY3RpY2VzLCBrZWVwcyBiYWNrd2FyZHMgY29tcGF0aWJpbGl0eSAoWWVzISBVcGdyYWRpbmcgaXMgYWx3YXlzIHNhZmUgJiBlYXN5ISkgYW5kIG9mZmVycyBsb25nLXRlcm0gc3VwcG9ydC4KCg==) should be the same.

I don't know if we have good practice for writing the docs, I don't know if there is tools to ensure that formatting, and even if we decide to use it, I imagine how many work this represent.

What do you think ?

**Comment by javiereguiluz** [comment]
@Jibbarth thanks for proposing ideas to improve Symfony Docs. However, I'm afraid we can't implement this idea. First, it would be a nightmare to change all contents now. It's true that we could automate that with a script ... but we merge branches up (2.7 into 2.8, then 2.8 into 3.3, ..., then 4.0 into master). The number of merge conflicts between branches would be huge. We don't have the time or resources to do that. I'm sorry.

Besides, as you can see in the original video that you linked:

![line-wrap](https://user-images.githubusercontent.com/73419/34711262-0c8a0804-f51f-11e7-8f06-0a96ca0dea8c.png)

The problem is that most online editors don't support line wrapping, so most contents are hidden because of the long lines. In [the editor that you linked](http://rst.ninjs.org/?theme=basic#VGhlIEJpZyBQaWN0dXJlCj09PT09PT09PT09PT09PQoKU3RhcnQgdXNpbmcgU3ltZm9ueSBpbiAxMCBtaW51dGVzISBSZWFsbHkhIFRoYXQncyBhbGwgeW91IG5lZWQgdG8gdW5kZXJzdGFuZCB0aGUKbW9zdCBpbXBvcnRhbnQgY29uY2VwdHMgYW5kIHN0YXJ0IGJ1aWxkaW5nIGEgcmVhbCBwcm9qZWN0IQoKSWYgeW91J3ZlIHVzZWQgYSB3ZWIgZnJhbWV3b3JrIGJlZm9yZSwgeW91IHNob3VsZCBmZWVsIHJpZ2h0IGF0IGhvbWUgd2l0aApTeW1mb255LiBJZiBub3QsIHdlbGNvbWUgdG8gYSB3aG9sZSBuZXcgd2F5IG9mIGRldmVsb3Bpbmcgd2ViIGFwcGxpY2F0aW9ucy4gU3ltZm9ueQoqZW1icmFjZXMqIGJlc3QgcHJhY3RpY2VzLCBrZWVwcyBiYWNrd2FyZHMgY29tcGF0aWJpbGl0eSAoWWVzISBVcGdyYWRpbmcgaXMgYWx3YXlzCnNhZmUgJiBlYXN5ISkgYW5kIG9mZmVycyBsb25nLXRlcm0gc3VwcG9ydC4KCgpUaGUgQmlnIFBpY3R1cmUKPT09PT09PT09PT09PT09CgpTdGFydCB1c2luZyBTeW1mb255IGluIDEwIG1pbnV0ZXMhIApSZWFsbHkhIApUaGF0J3MgYWxsIHlvdSBuZWVkIHRvIHVuZGVyc3RhbmQgdGhlIG1vc3QgaW1wb3J0YW50IGNvbmNlcHRzIGFuZCBzdGFydCBidWlsZGluZyBhIHJlYWwgcHJvamVjdCEKCklmIHlvdSd2ZSB1c2VkIGEgd2ViIGZyYW1ld29yayBiZWZvcmUsIHlvdSBzaG91bGQgZmVlbCByaWdodCBhdCBob21lIHdpdGggU3ltZm9ueS4gCklmIG5vdCwgd2VsY29tZSB0byBhIHdob2xlIG5ldyB3YXkgb2YgZGV2ZWxvcGluZyB3ZWIgYXBwbGljYXRpb25zLiAKU3ltZm9ueSAqZW1icmFjZXMqIGJlc3QgcHJhY3RpY2VzLCBrZWVwcyBiYWNrd2FyZHMgY29tcGF0aWJpbGl0eSAoWWVzISBVcGdyYWRpbmcgaXMgYWx3YXlzIHNhZmUgJiBlYXN5ISkgYW5kIG9mZmVycyBsb25nLXRlcm0gc3VwcG9ydC4KCg==) this is not a problem, but in the editor used by Symfony Docs contributors, it's also a problem:

![github-line-wrap](https://user-images.githubusercontent.com/73419/34711304-345b28fe-f51f-11e7-901c-9a87fc57875f.png)

Even if this time your idea didn't make it, we encourage you to keep proposing ideas to improve Symfony Docs. Thank you!

**Comment by Jibbarth** [comment]
Okay, no problem I undertstand, it was just an idea 😉Thanks for the answer, and keep rocking !
