### ISSUE TITLE
Missing symfony/profiler from download page

### ISSUE THREAD

**Issue by kriskoch** [symfony/symfony-docs#9030]
I know the symfony-docs isnt the right repo to report this issue, but not sure where to report it. Contact us?
Anyways, on http://symfony.com/download   symfony/profiler is not listed in the symfony components.

**Comment by javiereguiluz** [comment]
@kriskoch thanks for reporting this ... but I think it's not a bug. The reason is that there's not a Symfony Profiler component (yet). Part of the profiler is inside the HttpKernel component (https://github.com/symfony/symfony/tree/master/src/Symfony/Component/HttpKernel/Profiler) and then we use a bundle to provide the UI of the profiler (https://github.com/symfony/web-profiler-bundle).

We have a `profiler-pack` repository (https://github.com/symfony/profiler-pack) but that's for Symfony Flex, so you can run `composer require profiler` and install all that's needed for the profiler.
