### ISSUE TITLE
Update the _theme to mimic the official site

### ISSUE THREAD

**Issue by arcristo** [symfony/symfony-docs#9246]
Hi,

I'm translating the documentation to [Portuguese](https://github.com/arcristo/symfony-doc-pt-br) and plan to build the doc using the layout from [Symfony Doc](http://symfony.com/doc/current/index.html) but the layout shipped with the repo is very different.

There is any plan to update the _theme to mimic the official site?

**Comment by xabbuh** [comment]
As far as I know there is no plan as it would involve too much work.

@javiereguiluz may know more about it.

**Comment by javiereguiluz** [comment]
We can't make the theme look the same as symfony.com because that will confuse visitors. But we should update the theme a bit because it's even using the old navigation menu (cookbook, etc.). Sadly I can't work on this because I'm *"allergic"* to Sphinx and I don't know how to do those changes.

PS: I've removed the `Website` label in this issue because it's not something that we need to change or fix on symfony.com website. Changes should be made on https://github.com/symfony/symfony-docs/tree/master/_build/_theme

**Comment by arcristo** [comment]
Yes, this is my first contact with Sphinx, and I was hoping to get some functionality from the official website, so I would not need the code myself: sweat_smile:

Things like the links to show a page in other versions (and filter only the versions that actually have that page) and the generation of pdfs.

The layout itself may be different, although I was also hoping to be able to use the official layout.

I'll keep going with the translations and keep track of the _theme folder on master as pointed out by @javiereguiluz

**Comment by javiereguiluz** [comment]
@arcristo we tried to do this but we failed. That's why in #9972 we've switched the default theme used to build docs locally. Now it doesn't look like symfony.com at all ... but at least everything works and the generated docs are fully usable. That's why I'm closing this issue. Thanks!
