### ISSUE TITLE
Config about routing and routes may need more explanation

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony-docs#9285]
Asked in Symfony Slack:

-----

Where in Symfony docs is a description of which route(s) go into which config files & dirs?
E.g., in symfony-demo project config there's a variety of rout* files, dirs, & subdir.

```
config/
    routes/
        annotations.yaml
        dev/
            twig.yaml
            web_profiler.yaml
    routes.yaml
    packages/
        dev/
            routing.yaml
        routing.yaml
```

I'm looking for the *online doc* that clarifies which routes go where, and why.

-----

The explanation is something like this:

1) routing = config for the routing component; routes = real routes
2) config/routes.yaml is the only file you edit to define the routes of your app
3) config /routes/*.yaml are the routes provided by the packages you install

**Comment by nicolas-grekas** [comment]
see https://github.com/symfony/recipes/pull/426

**Comment by javiereguiluz** [comment]
Closing in favor of the related recipes changes. Thanks!

**Comment by Pictor13** [comment]
I have the feeling this issue should be reopened.

As mentioned by @javiereguiluz , the documentation is not really clear about how many config files there are for routes, which can be defined and which are optional, what keys they support and what they are for, how they differentiate from each other...

I've been hopping for quite some time between several different documentation pages, code from different bundles and only finally ended up on this ticket.
This latter from @javiereguiluz  was the only place (on the net?) where these config-files-differences are clearly explained (as a list, rather than sporadic info into sparse examples on a long docs page or, worse, different docs pages).
Correct me if I am wrong.

[IMHO MODE ON]
The pull request is an improvement but is not sufficient.
It's just a brief comment, is not explicit as a 3 bullets list like above and it is not where a user would look for it (at least, I would have never ended up there).
You *might* read it, if you use recipes directly.
But in my case I got the EasyAdmin demo, where YAML files are already partially preconfigured and the PR comments are not present.
(stripped away? forgot? probably written before the PR?... whatever, that's not the point: the point is that the documentation should be improved, because that is where newbies go to discover Symfony things).
[/IMHO MODE ON]

Regarding the current documentation; it is quite good, but [when telling to import the `config/routing/all.xml` into the `app/config/routing.yml`](https://github.com/FriendsOfSymfony/FOSUserBundle/blob/master/Resources/doc/index.rst#step-6-import-fosuserbundle-routing-files) I got suck not being able to understand the differences and shades among the 3 different places where the routing can be configured (still, in the context of an EasyAdmin project).
In the end the `fos_user:` entry should have been added to the `app/config/routes/easy_admin.yaml` instead.
Am I missing something and there actually is a way to add it to `routing.xml`? Or is the documentation inexact? Or is there something specific going on with the config of EasyAdmin?

How do you guys see the thing?
Is there any newbie that can confirm this problem in discovering this detail?
Do you think the documentation could be improved?
