### ISSUE TITLE
Adding Usage part for Config component

### ISSUE THREAD

**Issue by ProgMiner** [symfony/symfony-docs#9293]
Hello!
I am a newbie in Symfony and it components and have be a disappointed when not find a "Usage" part for Symfony's Config component (on it's [page](https://symfony.com/doc/current/components/config.html)). Can someone adding it?
Thanks!

**Comment by javiereguiluz** [comment]
@ProgMiner welcome to the Symfony community ... and thanks for helping us improve Symfony! It's true that most components include that `Usage` section. this one, for some reason, moved that to a separate article: https://symfony.com/doc/current/components/config/definition.html

Let me ask to doc maintainers if they think we should move that article into a `Usage` section like the rest of components. Ping @xabbuh @wouterj. Thanks!

**Comment by ProgMiner** [comment]
Thanks for your quick answer! I have been check this article primarily when search for a "Usage" section. But searching and learning a resource loading is been hard to me because they are separated.

P.S: What do you mean by `Ping @xabbuh @wouterj`? I am bad in English.

**Comment by javiereguiluz** [comment]
@ProgMiner the "ping" part means that I'm calling Christian (who is called @xabbuh on GitHub) and Wouter (who is @wouterj on GitHub) to ask their opinions. They are two members of the Symfony Docs Team and they have the power to make decisions in this repository.

**Comment by ProgMiner** [comment]
If you want to know my opinion, I thought about something like that. I think it would be good if this example included are main fragments from all the articles about "Config". Or at least about loading, defining/processing and maybe caching.

**Comment by javiereguiluz** [comment]
I'm closing this old issue because we've recently change the purpose of Symfony Docs and now we only document how to use these components inside a Symfony application. The README of the repository of each Component will include a brief usage explanation, but that's all. Even if that's pending for the Config component, I'm closing this issue because we're going to do that for ALL components, so there's no need to create issues for that. Thanks!
