### ISSUE TITLE
Autoconfigure service locator tag

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony-docs#9374]
https://github.com/symfony/symfony/pull/26341

Probably it won't require any change in docs because we don't list the autoconfigured tags.

**Comment by codedmonkey** [comment]
I was just working on a PR related to this https://github.com/symfony/symfony-docs/pull/9223. I tried to think of a nice way to incorporate it, but there doesn't seem to be a way without being reduntant about the default services.yaml configuration, and since it's completely optional I'd say it doesn't need to be documented.
