### ISSUE TITLE
forms.html

### ISSUE THREAD

**Issue by readingdan** [symfony/symfony-docs#9580]
Just following the Symfony tutorial (2.8) on forms, and got stuck after copying and pasting code for DefaultController.php. I am no expert but looks like this is missing a couple of lines to get it working:

// src/AppBundle/Controller/DefaultController.php

use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;

and 

  /**
   * @Route("/")
   */

**Comment by xabbuh** [comment]
The example is focused on showing how to use forms. We omitted the routing configuration on purpose as it's not relevant when you build your forms whether you prefer annotations, YAML, XML or PHP to configure your routes. I am not sure that we should really change that.

**Comment by javiereguiluz** [comment]
@readingdan I'm sorry you had some issues while following that article. Sadly, as Christian said, we can't show all examples complete because that makes articles too long and complicate maintenance. That's why we show the first example complete and then only the things that changed since the previous example.

In some special cases we can make exceptions, so we'll keep your comment in mind in case we receive more issues about this article. Thanks!
