### ISSUE TITLE
Doc always mention to configure FosUserBundle in config.yml

### ISSUE THREAD

**Issue by ismail1432** [symfony/symfony-docs#9589]
[fos userbundle](https://symfony.com/doc/master/bundles/FOSUserBundle/index.html#step-5-configure-the-fosuserbundle) always mention to configure in `app/config/config.yml` that doesn’t exists in Sf4 and people are confuse see [here](https://stackoverflow.com/questions/49799385/symfony4-app-config-config-yml-is-missing)

**Comment by xabbuh** [comment]
The FOSUserBundle documentation is managed in [their repository](https://github.com/FriendsOfSymfony/FOSUserBundle). If you think that something can be improved, you will need to open an issue over there. That's why I am going to close here, but thank you anyway for taking the time writing the issue.

**Comment by ismail1432** [comment]
It’s a mistake sorry.
