### ISSUE TITLE
[Debug] Support any Throwable object in FlattenException

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony-docs#9636]
See https://github.com/symfony/symfony/pull/26528

@derrabus you created the original pull request. I'd like to ask you if this change is just internal to Symfony or has impact to end-user apps. If it impacts users, can you please tell us what changes must users make? Thanks a lot!

**Comment by derrabus** [comment]
@javiereguiluz Thanks for reaching out. I will have a look if the documentation has to be adjusted. But since the old methods have not (yet?) been deprecated, there is no action developers _have to_ take now.

The changes that end-users might actually see have been done in symfony/symfony#26028 already.
