### ISSUE TITLE
Broken link in session documentation 

### ISSUE THREAD

**Issue by rpodwika** [symfony/symfony-docs#9895]
Ways to reproduce:

go to https://symfony.com/doc/current/components/http_foundation/session_configuration.html

click on RedisSessionHandler

it will redirect you to https://api.symfony.com/4.1/Symfony/Component/HttpFoundation/Session/Storage/Handler/RedisSessionHandler.html which returns 404

**Comment by xabbuh** [comment]
This looks like an issue with the generation of the API docs as the class does exist (see https://github.com/symfony/symfony/tree/4.1/src/Symfony/Component/HttpFoundation/Session/Storage/Handler).

**Comment by javiereguiluz** [comment]
@rpodwika thanks for reporting this error. Indeed the problem looks like 4.1 API docs haven't been regenerated properly, because this class was added in 4.1. I've opened an issue about this in the private repo where we develop the symfony.com website and the API site, so we'll take it from here and that's why I'm closing this. Thanks!
