### ISSUE TITLE
metadatabag is breaking session laziness

### ISSUE THREAD

**Issue by cosma** [symfony/symfony-docs#9920]
Moved from here https://github.com/symfony/symfony/issues/26887

------

According to https://symfony.com/doc/3.4/reference/configuration/framework.html#metadata-update-threshold the metadata update treshold configuration is not needed anymore because
"Starting in Symfony 3.4, session data is only written when the session data has changed. Previously, you needed to set this option to avoid that behavior."
Unfortunately, this is not quite true in reality used withy the MemcachedSessionHandler which was presented here https://symfony.com/blog/new-in-symfony-3-4-session-improvements.

For consecutive calls with unchanged session, the Memcached adapter is actually using doWrite() instead of updateTimestamp() because, internally , Symfony updates at every http request the metadatabag(the update field is always changed).

So we still need to use the framework.session.metadata_update_threshold configuration to solve our problem.

**Comment by plfort** [comment]
Any news about this issue ?
I encounter the same problem using SncRedis as session handler (php 7.1): 
updateTimestamp method is never called unless we set  framework.session.metadata_update_threshold because Session\MetadataBag is always updating the session data.
It doesn't seem to me to be just a documentation error.

**Comment by xabbuh** [comment]
@plfort Would you like to work on a pull request updating the documentation?
