### ISSUE TITLE
Add link in Lock component >= 3.4 to Lock Handler

### ISSUE THREAD

**Issue by ismail1432** [symfony/symfony-docs#9922]
When you're looking for the [Lock component](http://symfony.com/doc/current/components/lock.html) you should have a link for Sf < 3.4 https://symfony.com/doc/2.8/components/filesystem/lock_handler.html

**Comment by ismail1432** [comment]
Sorry @HeahDude but What does means the `Actionnable` label :question:

**Comment by HeahDude** [comment]
It means that the issue is clear enough so that anyone willing to take care of it, knows exactly what to do and where to do it :).

**Comment by xabbuh** [comment]
I am not sure if I understand what is the suggested solution here. The Lock component was only introduced in Symfony 3.4. So we cannot link to it in the 2.8 docs.

**Comment by ismail1432** [comment]
The actual Lock component was introduced in 3.4 but before the is this [kind of lock](https://symfony.com/doc/2.8/components/filesystem/lock_handler.html). When people need documentation they go on symfony documentation then switch with the`select` for their version but actually you cannot find link for the "older" lock component...

**Comment by HeahDude** [comment]
We could add a note at the end linking the older doc, no need to edit the switch button.

**Comment by javiereguiluz** [comment]
I agree with Christian. The current policy in docs is to add the deprecation/warning messages in the versions they are introduced.

Since this was deprecated introduced in 3.4, we added the message in 3.4 (see https://symfony.com/doc/3.4/components/filesystem/lock_handler.html). We cannot add a message in 2.8 saying that this changed in future Symfony versions because that would be inconsistent with the rest of docs.

@ismail1432 I hope we explained well the reason to not make this change. If we didn't, please ask for more details. And please, keep sending proposals to improve the docs! Thanks.

**Comment by ismail1432** [comment]
no worries I totally understand @javiereguiluz 
Thanks !
