### ISSUE TITLE
Bad merge from 4.1 to 4.0

### ISSUE THREAD

**Issue by weaverryan** [symfony/symfony-docs#9945]
Hi guys!

Recently (not sure exactly when/how), the 4.1 branch was merged into the 4.0 branch. So, we need to identify when this happened, and how to fix it.

I talked with @nicolas-grekas, and he thinks that bad commit was sha: 9e860a1ff1447eebb99e39c23e5510534078387c and that we should rollback to one of its parents: sha: d6b29968b27fb1034d35159fb434dfc90c9e1680

I'm hoping to find out if a few other people agree or disagree (I will look tomorrow). IF this is the correct commit, then we can:

A) Merge current 4.0 up to 4.1/master
B) reset hard 4.0 back to sha: d6b29968b27fb1034d35159fb434dfc90c9e1680 & force push
C) manually add the missing commits to 4.0

cc @teohhanhui

**Comment by teohhanhui** [comment]
What I did to resolve a similar issue in API Platform:

1. Merge the messed up branch into the newer version branches and `master`.
2. `git reset --hard` to the clean parent commit - d6b2996 in this case.
3. `git cherry-pick` each commit that should be included, and manually resolve conflicts if necessary - it will hopefully be minimal, and at least the conflicts would make sense since we're moving forward in time.
4. `git push` to a feature branch and open an unmergeable PR for review purposes - also to make sure that Travis CI build is green.
5. `git diff` or similar to create a patch/diff file since the clean parent commit up to current `HEAD`.
6. `git checkout -b` a new branch from the current `HEAD` of the remote branch - `4.0` in this case.
7. Make sure the working directory is clean.
8. `git apply` or similar to apply the patch/diff file.
9. `git commit` and `git push` to another feature branch. This time it's mergeable so open a PR and get it merged.
10. `git merge -s ours` into the newer version branches and `master`. We don't need an actual merge as all the same contents should already be in those branches.
11. Profit???

Note that there is *no* force pushing involved at any point.

**Comment by weaverryan** [comment]
Fixed! @teohhanhui I actually did ultimately do a force push. It has obvious downsides, but was a bit simpler. And, fortunately, the force was only on the 4.0 branch, which does not have many PR's against it. Things are a bit more forgiving on the docs :)

**Comment by teohhanhui** [comment]
Well, you must remember you have many forks of the repository. Now they're all screwed. 😂
