### ISSUE TITLE
add a cookbook entry about how to have multiple kernels

### ISSUE THREAD

**Issue by lsmith77** [symfony/symfony-docs#997]
this could be based on https://github.com/liip/sf2debpkg

**Comment by stof** [comment]
Having a different kernel in prod and dev looks really weird to me.

@kbond the common use case for multiple kernel IMO is having an API and a website in the same project. The API can use a separate kernel, allowing to avoid loading a bunch of bundles it does not need (related to the website stuff) and loading other bundles which should affect only the API (FOSRestBundle for instance)

**Comment by weaverryan** [comment]
+1 for the example with a "website" (frontend) and an API. It works especially well since you can show how some API-related bundles don't need to be enabled for the "website" kernel. I don't think this entry needs to be huge - just highlight some directory structure stuff, show how you have different bundles registered (but you use some bundles on both), and *why* you would use this approach.

**Comment by weaverryan** [comment]
Boom!
