### ISSUE TITLE
[Configuration] Invalid config

### ISSUE THREAD

**Issue by CuiKeng** [symfony/symfony-docs#9998]
During development, you'll use the .env file to configure your environment variables. On your production server, it is recommended to configure these at the web server level. If you're using Apache or Nginx, you can use e.g. one of the following:
```
<VirtualHost *:80>
    # ...

    SetEnv DATABASE_URL "mysql://db_user:db_password@127.0.0.1:3306/db_name"
</VirtualHost>
```

When run bin\console cache:clear, it occur a fatal error:
```
PHP Fatal error:  Uncaught RuntimeException: APP_ENV environment variable is not defined. You need to define environment variables for configura
tion or add "symfony/dotenv" as a Composer dependency to load variables from a .env file. in E:\workspace\symfony\v7\bin\console:20
Stack trace:
#0 {main}
  thrown in E:\workspace\symfony\v7\bin\console on line 20

Fatal error: Uncaught RuntimeException: APP_ENV environment variable is not defined. You need to define environment variables for configuration
or add "symfony/dotenv" as a Composer dependency to load variables from a .env file. in E:\workspace\symfony\v7\bin\console:20
Stack trace:
#0 {main}
  thrown in E:\workspace\symfony\v7\bin\console on line 20
```

**Comment by xabbuh** [comment]
You need to set the environment variables for your CLI processes too. They don't know anything about your web server config.

**Comment by javiereguiluz** [comment]
@CuiKeng in the main deployment article you can find an explicit mention to the `APP_ENV` env var because it's the only one which is always required to avoid issues like the one you mentioned.

You can read it here: https://symfony.com/doc/current/deployment.html#b-configure-your-environment-variables  We're making a minor reword about this in #10050, so we are closing this issue as fixed. Thanks for helping us improve Symfony Docs!
